using System.Collections.Generic;
using Hardlight;
using UnityEngine;
using UnityEngine.Events;
using Unity.IL2CPP.CompilerServices;

namespace HardlightProject
{
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class MissionScorer : TimeScaledComponent_SDT
    {
        [SerializeField, Tooltip("Defines each stage of the scoring combo.")]
        private List<MissionScorerComboStage> m_comboStages = new List<MissionScorerComboStage>();
        [Tooltip("Whether or not the player can score negative points."), SerializeField]
        private bool m_allowNegativePoints;
        [SerializeField] private UnityEvent m_onAddPoints;
        [SerializeField] private UnityEvent m_onAddPointsFlat;
        [SerializeField] private UnityEvent m_onLosePoints;
        [SerializeField, Tooltip("Mission scorer streaks that have been manually assigned.")]
        private List<MissionScorerStreak> m_streaksManual;
        [Tooltip("Mission scorer streaks that have been auto generated by proximity and dont appear in the manual list."), SerializeField]
        private List<MissionScorerStreak> m_streaksAuto;
        [SerializeField, Tooltip("Mission scorer display time.")]
        private float m_displayTimer = 0.5f;

        // Original 0x06002753, 0x06002754: Read and privately write the original backing field at byte offset 140; preserve the natural compiler-generated accessor pair.
        public int PointsTotal { get; private set; }
        // Original 0x06002755, 0x06002756: Read and privately write the original backing field at byte offset 144; preserve the natural compiler-generated accessor pair.
        public int PointsAdded { get; private set; }
        // Original 0x06002757, 0x06002758: Read and privately write the original backing field at byte offset 148; preserve the natural compiler-generated accessor pair.
        public int PointsAddedRaw { get; private set; }
        // Original 0x06002759, 0x0600275a: Read and privately write the original backing field at byte offset 152; preserve the natural compiler-generated accessor pair.
        public int PointsLost { get; private set; }
        // Original 0x0600275b: Read timer at byte offset 208 and return ordered greater-than zero.
        public bool ShowPointsAdded => m_scoreTimeout > 0f;
        // Original 0x0600275c, 0x0600275d: Read and privately write the original backing field at byte offset 156; preserve the natural compiler-generated accessor pair.
        public int PointsTotalThisCombo { get; private set; }
        // Original 0x0600275e, 0x0600275f: Read and privately write the original backing field at byte offset 160; preserve the natural compiler-generated accessor pair.
        public bool PointsAddedFromCombo { get; private set; }
        // Original 0x06002760, 0x06002761: Read and privately write the original backing field at byte offset 164; preserve the natural compiler-generated accessor pair.
        public int PointsTotalThisStreak { get; private set; }
        // Original 0x06002762: Read timer at byte offset 212 and return ordered greater-than zero.
        public bool PointsAddedFromStreak => m_streakTimeout > 0f;
        // Original 0x06002763, 0x06002764: Read and privately write the original backing field at byte offset 168; preserve the natural compiler-generated accessor pair.
        public bool ComboActive { get; private set; }
        // Original 0x06002765, 0x06002766: Read and privately write the original backing field at byte offset 172; preserve the natural compiler-generated accessor pair.
        public float ComboMultiplier { get; private set; } = 1f;
        // Original 0x06002767, 0x06002768: Read and privately write the original backing field at byte offset 176; preserve the natural compiler-generated accessor pair.
        public float ComboStageMultiplier { get; private set; } = 1f;
        // Original 0x06002769, 0x0600276a: Read and privately write the original backing field at byte offset 180; preserve the natural compiler-generated accessor pair.
        public float ComboTimeout { get; private set; }
        // Original 0x0600276b, 0x0600276c: Read and privately write the original backing field at byte offset 184; preserve the natural compiler-generated accessor pair.
        public float ComboTimeoutNormalised { get; private set; }
        // Original 0x0600276d, 0x0600276e: Read and privately write the original backing field at byte offset 188; preserve the natural compiler-generated accessor pair.
        public int ComboCount { get; private set; }
        // Original 0x0600276f, 0x06002770: Read and privately write the original backing field at byte offset 192; preserve the natural compiler-generated accessor pair.
        public bool ComboAtMax { get; private set; }
        // Original 0x06002771, 0x06002772: Read and privately write the original backing field at byte offset 193; preserve the natural compiler-generated accessor pair.
        public bool ComboSuspended { get; private set; }
        private int m_comboStageIndex;
        private MissionScorerComboStage m_comboStage;
        private float m_scoreTimeout;
        private float m_streakTimeout;

        // Original 0x06002773: Call genuine TimeScaledComponent_SDT.Initialise, then reset the combo stage; native ResetComboStage is inlined. No scorer events are invoked.
        protected override void Initialise(TimeManager timeManager)
        {
            base.Initialise(timeManager);
            ResetComboStage();
        }

        // Original 0x06002774: Update manual then auto streaks before the ComboSuspended early return. Otherwise update timeout or multiplier drain, then score and streak display clocks. Keep stage division and provider float/fault semantics held.
        protected override void InternalUpdate(float deltaTime)
        {
            UpdateStreaks(deltaTime);
            if (ComboSuspended) return;
            if (ComboTimeout > 0f)
            {
                ComboTimeout -= deltaTime;
                ComboTimeoutNormalised = ComboTimeout / m_comboStage.ComboTimeLimit;
                ComboActive = true;
                if (ComboTimeout <= 0f) EndCombo();
            }
            else if (m_comboStage.DrainPerSecond > 0f && ComboMultiplier > 1f)
            {
                ComboActive = true;
                ComboMultiplier -= m_comboStage.DrainPerSecond * deltaTime;
                if (ComboMultiplier <= 1f) EndCombo();
            }
            if (m_scoreTimeout > 0f)
                m_scoreTimeout = Mathf.Max(m_scoreTimeout - deltaTime, 0f);
            if (m_streakTimeout > 0f)
            {
                m_streakTimeout -= deltaTime;
                if (m_streakTimeout <= 0f)
                {
                    m_streakTimeout = 0f;
                    PointsTotalThisStreak = 0;
                }
            }
        }

        // Original 0x06002775: Exact zero input returns before stage or event access. Store the stage multiplier, round the left-associated multiplied score, add unchecked totals, choose streak or combo display writes, then invoke m_onAddPoints.
        public void AddPoints(float pointsToAdd, bool isStreak)
        {
            if (pointsToAdd == 0f) return;
            ComboStageMultiplier = m_comboStage.ComboMultiplier;
            int points = Mathf.RoundToInt(ComboMultiplier * pointsToAdd * ComboStageMultiplier);
            PointsTotal = unchecked(PointsTotal + points);
            if (isStreak)
            {
                PointsTotalThisStreak = points;
                m_streakTimeout = m_displayTimer;
            }
            else
            {
                PointsTotalThisCombo = unchecked(PointsTotalThisCombo + points);
                PointsAdded = points;
                PointsAddedRaw = Mathf.RoundToInt(pointsToAdd);
                PointsAddedFromCombo = true;
                m_scoreTimeout = m_displayTimer;
            }
            m_onAddPoints.Invoke();
        }

        // Original 0x06002776: Exact zero input returns before event access. Round the input once without combo multiplication, add unchecked totals, select streak or combo display writes, then invoke m_onAddPointsFlat.
        public void AddPointsFlat(float pointsToAdd, bool isStreak)
        {
            if (pointsToAdd == 0f) return;
            int points = Mathf.RoundToInt(pointsToAdd);
            PointsTotal = unchecked(PointsTotal + points);
            if (isStreak)
            {
                PointsTotalThisStreak = points;
                m_streakTimeout = m_displayTimer;
            }
            else
            {
                PointsTotalThisCombo = unchecked(PointsTotalThisCombo + points);
                PointsAdded = points;
                PointsAddedRaw = points;
                PointsAddedFromCombo = false;
                m_scoreTimeout = m_displayTimer;
            }
            m_onAddPointsFlat.Invoke();
        }

        // Original 0x06002777: Round the input, subtract unchecked totals, clamp each total to zero when negative points are disabled, store PointsLost, then invoke m_onLosePoints. Zero input still reaches the callback.
        public void LosePoints(float pointsToLose)
        {
            int points = Mathf.RoundToInt(pointsToLose);
            PointsTotal = unchecked(PointsTotal - points);
            PointsTotalThisCombo = unchecked(PointsTotalThisCombo - points);
            if (!m_allowNegativePoints)
            {
                PointsTotal = Mathf.Max(PointsTotal, 0);
                PointsTotalThisCombo = Mathf.Max(PointsTotalThisCombo, 0);
            }
            PointsLost = points;
            m_onLosePoints.Invoke();
        }

        // Original 0x06002778: Apply the stage maximum to the increased multiplier, copy the stage multiplier, and increment ComboCount unchecked even for zero increase.
        public void IncreaseCombo(float increase)
        {
            ComboMultiplier = Mathf.Min(ComboMultiplier + increase, m_comboStage.MaxCombo);
            ComboStageMultiplier = m_comboStage.ComboMultiplier;
            ComboCount = unchecked(ComboCount + 1);
        }

        // Original 0x06002779: Set stage index zero, take the genuine first list item, clear ComboAtMax and PointsTotalThisCombo, then perform all six EndCombo writes. Empty/null list faults remain provider and source-form holds.
        public void ResetComboStage()
        {
            m_comboStageIndex = 0;
            m_comboStage = m_comboStages[0];
            ComboAtMax = false;
            PointsTotalThisCombo = 0;
            EndCombo();
        }

        // Original 0x0600277a: Negative or out-of-count stage index returns. Otherwise store the stage, reduce timeout to its limit, divide for normalisation, apply IncreaseCombo(0), set the final-stage flag, and clear PointsTotalThisCombo. The native zero addition is optimized away.
        public void SetComboStage(int stageIndex)
        {
            if (stageIndex < 0 || stageIndex >= m_comboStages.Count) return;
            m_comboStageIndex = stageIndex;
            m_comboStage = m_comboStages[stageIndex];
            ComboTimeout = Mathf.Min(ComboTimeout, m_comboStage.ComboTimeLimit);
            ComboTimeoutNormalised = ComboTimeout / m_comboStage.ComboTimeLimit;
            IncreaseCombo(0f);
            ComboAtMax = m_comboStageIndex == m_comboStages.Count - 1;
            PointsTotalThisCombo = 0;
        }

        // Original 0x0600277b: Increment the current stage index unchecked and tailcall SetComboStage; do not clamp or wrap the list index.
        public void NextComboStage() { SetComboStage(unchecked(m_comboStageIndex + 1)); }
        // Original 0x0600277c: Decrement the current stage index unchecked and tailcall SetComboStage; do not clamp or wrap the list index.
        public void PrevComboStage() { SetComboStage(unchecked(m_comboStageIndex - 1)); }
        // Original 0x0600277d: For an ordered multiplier above one, copy the stage time limit and store normalisation one. Both ARM b.ls and x86 jae continue on unordered/NaN input; the historical candidate ordered > guard differs. Preserve the separate bounded whole-source <= early-return successor, with exceptional float runtime parity held.
        public void ExtendCombo()
        {
            if (ComboMultiplier <= 1f) return;
            ComboTimeout = m_comboStage.ComboTimeLimit;
            ComboTimeoutNormalised = 1f;
        }
        // Original 0x0600277e: Store multipliers one and one, timeout and normalisation zero, count zero, and active false. Preserve all other state including ComboSuspended and PointsTotalThisCombo.
        public void EndCombo()
        {
            ComboMultiplier = 1f;
            ComboStageMultiplier = 1f;
            ComboTimeout = 0f;
            ComboTimeoutNormalised = 0f;
            ComboCount = 0;
            ComboActive = false;
        }
        // Original 0x0600277f: Clear only the ComboSuspended byte.
        public void ResumeTimeout() { ComboSuspended = false; }
        // Original 0x06002780: Set ComboSuspended only when timeout is unequal to zero, including native unordered input. Keep the prior byte when timeout is zero.
        public void SuspendTimeout() { if (ComboTimeout != 0f) ComboSuspended = true; }

        // Original 0x06002781: Enumerate the complete manual list then the auto list. Call genuine MissionScorerStreak.Update in source; native body inlines its time/progress writes. Preserve disposal and exceptional cleanup with foreach, and hold provider fault/concurrency parity.
        private void UpdateStreaks(float deltaTime)
        {
            foreach (MissionScorerStreak streak in m_streaksManual) streak.Update(deltaTime);
            foreach (MissionScorerStreak streak in m_streaksAuto) streak.Update(deltaTime);
        }

        // Original 0x06002782: Write both out cells zero/false before the actual MissionScorerStreakObjective type test. Try manual then auto lists with short-circuit priority. A matched objective returns whether the score is strictly positive, retaining the matched out bool even when false.
        public bool UpdateStreak(MissionScorerObjective objective, out float streakScore, out bool usesComboMultiplier)
        {
            streakScore = 0f;
            usesComboMultiplier = false;
            if (!(objective is MissionScorerStreakObjective streakObjective)) return false;
            if (UpdateStreak(streakObjective, m_streaksManual, out streakScore, out usesComboMultiplier)
                || UpdateStreak(streakObjective, m_streaksAuto, out streakScore, out usesComboMultiplier))
                return streakScore > 0f;
            return false;
        }

        // Original 0x06002783: Enumerate the supplied streak list and return true on the first genuine TryUpdateFromObjective match. Native inlines the provider membership/progress/time logic and calls genuine streak-definition GetScore on completion. On exhaustion write both out cells zero/false and return false.
        private bool UpdateStreak(MissionScorerStreakObjective streakObjective, List<MissionScorerStreak> streaks,
            out float score, out bool usesComboMultiplier)
        {
            foreach (MissionScorerStreak streak in streaks)
                if (streak.TryUpdateFromObjective(streakObjective, out score, out usesComboMultiplier)) return true;
            score = 0f;
            usesComboMultiplier = false;
            return false;
        }
        // Original 0x06002784: Allocate and initialize the genuine combo-stage list, store display time 0.5 and both multiplier ones, then call the genuine TimeScaledComponent_SDT constructor. Event and streak-list fields receive no explicit allocation; their zero defaults depend on managed allocation.
        public MissionScorer() { }
    }
}
