using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using Mono.Cecil;
using UnityEditor.Compilation;

namespace ProjectLucid
{
    public static class CodecPipelineVerification
    {
        private static void Require(bool value, string description)
        {
            if (!value) throw new InvalidOperationException(description);
        }

        private static string Hash(byte[] value)
        {
            using (var digest = SHA256.Create())
                return BitConverter.ToString(digest.ComputeHash(value));
        }

        public static int Run()
        {
            // Compare the real Bee compiler output to Unity's loaded, postprocessed
            // module. The matching MVID excludes stale outputs from earlier imports.
            var compiled = CompilationPipeline.GetAssemblies(AssembliesType.Editor)
                .Single(a => a.name == "HLAutoGenerated");
            var loaded = typeof(ClientDataAPI.LocalisedString).Assembly;
            string installed = Path.GetFullPath(loaded.Location);
            Require(installed == Path.GetFullPath(compiled.outputPath), "Loaded codec module differs from current Unity compilation output.");
            var candidates = new List<string>();
            foreach (string path in Directory.GetFiles("Library/Bee/artifacts", "HLAutoGenerated.dll", SearchOption.AllDirectories))
            {
                string response = Path.ChangeExtension(path, ".rsp");
                if (!File.Exists(response)) continue; // Processed copies have no CSC response file.
                string output = "-out:\"" + path.Replace('\\', '/') + "\"";
                Require(File.ReadLines(response).Contains(output), "Bee input differs from its actual CSC output argument.");
                using (var module = ModuleDefinition.ReadModule(path))
                    if (module.Mvid == loaded.ManifestModule.ModuleVersionId)
                        candidates.Add(path);
            }
            Require(candidates.Count > 0, "No actual Bee input matches the current loaded codec module.");
            string raw = candidates.OrderBy(p => p, StringComparer.Ordinal).First();
            byte[] input = File.ReadAllBytes(raw);
            Require(candidates.All(p => Hash(File.ReadAllBytes(p)) == Hash(input)), "Ambiguous compiler inputs for the current codec module.");
            var references = compiled.compiledAssemblyReferences.Concat(compiled.assemblyReferences.Select(a => a.outputPath))
                .Select(Path.GetFullPath).Distinct(StringComparer.Ordinal).ToArray();
            string run = Path.Combine(".cache/project-lucid/verification", "codec-pipeline-" + Guid.NewGuid().ToString("N"));
            Directory.CreateDirectory(run);
            try
            {
                string patched = Path.Combine(run, "HLAutoGenerated.dll");
                int checks = PostProcessorVerification.Run(raw, patched, references);
                Require(File.ReadAllBytes(patched).SequenceEqual(File.ReadAllBytes(installed)), "Actual Unity output is not the exact twenty-cell restoration of its Bee input.");
                Require(File.ReadAllBytes(Path.ChangeExtension(raw, ".pdb")).SequenceEqual(File.ReadAllBytes(Path.ChangeExtension(installed, ".pdb"))), "Actual Unity codec PDB changed during flag restoration.");
                foreach (Type type in new[] { typeof(ClientDataAPI.LocalisedString), typeof(ClientDataAPI.StringTable), typeof(ClientDataAPI.SupportedLanguage), typeof(ClientDataAPI.LocalisationDefinitions) })
                {
                    var targets = type.GetMethods(System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance | System.Reflection.BindingFlags.DeclaredOnly)
                        .Where(m => m.Name == "get_MessageId" || m.Name == "encodedLength" || m.Name == "decodeInto" || m.Name == "encode").ToArray();
                    Require(targets.Length == 5 && targets.All(m => m.IsFinal && m.IsVirtual && m.GetBaseDefinition() == m), "Actual loaded codec lost original final virtual new-slot methods.");
                }
                Require(typeof(EncodableMessage).GetMethods().Length == 0 && typeof(DecodableMessage).GetMethods().Length == 0, "Original marker interfaces acquired invented contracts.");
                return checks;
            }
            finally { Directory.Delete(run, true); }
        }
    }
}
