using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Mono.Cecil;
using ProjectLucid.CodeGen;
using Unity.CompilationPipeline.Common.Diagnostics;
using Unity.CompilationPipeline.Common.ILPostProcessing;

internal static class PostProcessorVerification
{
    private static int checks;
    private static byte[] original, pdb;
    private static string[] references;
    private static CodecMethodFlagsPostProcessor processor = new CodecMethodFlagsPostProcessor();
    private static void Check(bool result, string name) { if (!result) throw new Exception(name); checks++; }

    // Compilation-pipeline input fixture, not a runtime game dependency.
    private sealed class Compilation : ICompiledAssembly
    {
        public InMemoryAssembly InMemoryAssembly { get; set; }
        public string Name { get; set; }
        public string[] References { get; set; }
        public string[] Defines => new[] { "UNITY_2022_3_54", "UNITY_EDITOR" };
    }
    private static Compilation Input(byte[] pe, string[] refs = null, string name = "HLAutoGenerated") => new Compilation {
        Name = name, References = refs ?? references, InMemoryAssembly = new InMemoryAssembly(pe, pdb)
    };
    private static DefaultAssemblyResolver Resolver()
    {
        var result = new DefaultAssemblyResolver();
        foreach (string path in references) result.AddSearchDirectory(Path.GetDirectoryName(path));
        return result;
    }
    private static byte[] Mutate(Action<ModuleDefinition> action)
    {
        using (var resolver = Resolver())
        using (var stream = new MemoryStream(original))
        using (var module = ModuleDefinition.ReadModule(stream, new ReaderParameters { AssemblyResolver = resolver, ReadingMode = ReadingMode.Immediate }))
        using (var output = new MemoryStream())
        { action(module); module.Write(output); return output.ToArray(); }
    }
    private static TypeDefinition Codec(ModuleDefinition module) => module.Types.Single(t => t.FullName == "ClientDataAPI.LocalisedString");
    private static void Reject(string label, byte[] bytes, string[] refs = null)
    {
        var input = Input(bytes, refs); var result = processor.Process(input);
        Check(result != null && result.Diagnostics.Count == 1 && result.Diagnostics[0].DiagnosticType == DiagnosticType.Error, label + " must fail compilation");
        Check(ReferenceEquals(result.InMemoryAssembly, input.InMemoryAssembly) && ReferenceEquals(result.InMemoryAssembly.PeData, bytes), label + " must retain original PE");
        Check(ReferenceEquals(result.InMemoryAssembly.PdbData, pdb), label + " must retain symbols");
    }
    internal static int Run(string path, string output, string[] refs)
    {
        original = File.ReadAllBytes(path); pdb = File.ReadAllBytes(Path.ChangeExtension(path, ".pdb")); references = refs;
        Check(!ReferenceEquals(processor.GetInstance(), processor), "independent processor instance");
        var ignored = Input(original, null, "Game.Runtime");
        Check(!processor.WillProcess(ignored) && processor.Process(ignored) == null, "other original assemblies ignored");
        var result = processor.Process(Input(original));
        Check(result != null && result.Diagnostics.Count == 0, "exact source graph accepted");
        Check(result.InMemoryAssembly.PeData.Length == original.Length && original.Zip(result.InMemoryAssembly.PeData, (a,b) => a != b).Count(x => x) == 40, "exact forty flag bytes changed");
        Check(ReferenceEquals(result.InMemoryAssembly.PdbData, pdb), "PDB returned verbatim");
        Check(!ReferenceEquals(result.InMemoryAssembly.PeData, original), "input image never mutated");
        using (var a = ModuleDefinition.ReadModule(new MemoryStream(original)))
        using (var b = ModuleDefinition.ReadModule(new MemoryStream(result.InMemoryAssembly.PeData)))
        {
            Check(a.Mvid == b.Mvid && a.Types.Count == b.Types.Count, "MVID and type rows unchanged");
            var aa = a.Types.SelectMany(t => t.Methods).ToArray(); var bb = b.Types.SelectMany(t => t.Methods).ToArray();
            Check(aa.Length == bb.Length, "all method rows retained");
            int changed = 0;
            for (int i = 0; i < aa.Length; ++i)
            {
                Check(aa[i].MetadataToken == bb[i].MetadataToken && aa[i].RVA == bb[i].RVA && aa[i].FullName == bb[i].FullName, "token/RVA/signature retained " + i);
                if (aa[i].Attributes != bb[i].Attributes)
                {
                    changed++;
                    Check(bb[i].IsFinal && bb[i].IsVirtual && bb[i].IsNewSlot && (ushort)bb[i].Attributes == ((ushort)aa[i].Attributes | 0x160), "only exact native bits added");
                }
            }
            Check(changed == 20, "exact twenty flag identities");
        }
        var again = processor.Process(Input(result.InMemoryAssembly.PeData));
        Check(again.Diagnostics.Count == 0 && again.InMemoryAssembly.PeData.SequenceEqual(result.InMemoryAssembly.PeData), "already exact flags idempotent");

        Reject("wrong assembly", Mutate(m => m.Assembly.Name.Name = "Other"));
        Reject("wrong assembly version", Mutate(m => m.Assembly.Name.Version = new Version(1,0,0,0)));
        Reject("unsealed type", Mutate(m => Codec(m).IsSealed = false));
        Reject("missing codec", Mutate(m => Codec(m).Name = "MissingLocalisedString"));
        Reject("extra field", Mutate(m => Codec(m).Fields.Add(new FieldDefinition("extra", FieldAttributes.Private, m.TypeSystem.Int32))));
        Reject("changed field type", Mutate(m => Codec(m).Fields.Single(f => f.Name == "m_id").FieldType = m.TypeSystem.Int32));
        Reject("changed constant ID", Mutate(m => Codec(m).Fields.Single(f => f.Name == "ID").Constant = 42));
        Reject("changed field order", Mutate(m => { var f=Codec(m).Fields; var old=f[2]; f.RemoveAt(2); f.Insert(3,old); }));
        Reject("missing method", Mutate(m => { var t=Codec(m); var removed=t.Methods.Single(x => x.Name == "Reset"); t.Methods.Remove(removed); foreach(var method in m.Types.SelectMany(x=>x.Methods).Where(x=>x.HasBody)) foreach(var instruction in method.Body.Instructions) if (ReferenceEquals(instruction.Operand,removed)) { instruction.OpCode=Mono.Cecil.Cil.OpCodes.Nop; instruction.Operand=null; } }));
        Reject("renamed method", Mutate(m => Codec(m).Methods.Single(x => x.Name == "encodedLength").Name = "encodedSize"));
        Reject("changed return type", Mutate(m => Codec(m).Methods.Single(x => x.Name == "encodedLength").ReturnType = m.TypeSystem.Int64));
        Reject("byref removed", Mutate(m => { var p=Codec(m).Methods.Single(x=>x.Name=="decodeInto").Parameters[0]; p.ParameterType=((ByReferenceType)p.ParameterType).ElementType; }));
        Reject("out attribute", Mutate(m => Codec(m).Methods.Single(x => x.Name == "decodeInto").Parameters[0].Attributes = ParameterAttributes.Out));
        Reject("virtual without final/newslot", Mutate(m => Codec(m).Methods.Single(x => x.Name == "encodedLength").IsVirtual = true));
        Reject("partial previous restoration", Mutate(m => Codec(m).Methods.Single(x => x.Name == "encodedLength").Attributes |= (MethodAttributes)0x160));
        Reject("implementation flags", Mutate(m => Codec(m).Methods.Single(x => x.Name == "encodedLength").ImplAttributes |= MethodImplAttributes.NoInlining));
        Reject("changed marker order", Mutate(m => { var t=Codec(m); var i=t.Interfaces[0];t.Interfaces.RemoveAt(0);t.Interfaces.Add(i); }));
        Reject("property removed", Mutate(m => Codec(m).Properties.RemoveAt(1)));
        Reject("property accessor removed", Mutate(m => Codec(m).Properties[0].GetMethod = null));
        Reject("duplicate property linkage", Mutate(m => { var t=Codec(m);t.Properties[1].Name=t.Properties[2].Name;t.Properties[1].GetMethod=t.Properties[2].GetMethod;t.Properties[1].SetMethod=t.Properties[2].SetMethod; }));
        Reject("cross-type property linkage", Mutate(m => Codec(m).Properties[0].GetMethod = m.Types.Single(t=>t.FullName=="ClientDataAPI.StringTable").Properties[0].GetMethod));
        Reject("property scope differs from accessor", Mutate(m => {
            var scope=new AssemblyNameReference("netstandard",new Version(9,0,0,0));
            scope.PublicKeyToken=new byte[] {0xcc,0x7b,0x13,0xff,0xcd,0x2d,0xdd,0x51};m.AssemblyReferences.Add(scope);
            Codec(m).Properties[0].PropertyType=new TypeReference("System","Int32",m,scope,true);
        }));
        Reject("interface implementation attribute added", Mutate(m => {
            var type=new TypeReference("System.Runtime.CompilerServices","CompilerGeneratedAttribute",m,m.TypeSystem.CoreLibrary);
            var constructor=new MethodReference(".ctor",m.TypeSystem.Void,type) { HasThis=true };
            Codec(m).Interfaces[0].CustomAttributes.Add(new CustomAttribute(constructor));
        }));
        Reject("IL2CPP option changed", Mutate(m => Codec(m).CustomAttributes[0].ConstructorArguments[0] = new CustomAttributeArgument(Codec(m).CustomAttributes[0].ConstructorArguments[0].Type,3)));
        Reject("IL2CPP bool changed", Mutate(m => Codec(m).CustomAttributes[0].ConstructorArguments[1] = new CustomAttributeArgument(m.TypeSystem.Object,new CustomAttributeArgument(m.TypeSystem.Boolean,true))));
        Reject("declared scope version changed", Mutate(m => m.AssemblyReferences.Single(x=>x.Name=="netstandard").Version = new Version(9,0,0,0)));
        Reject("marker dependency missing", original, references.Where(x=>!Path.GetFileName(x).StartsWith("HLNetworking.Runtime.")).ToArray());
        Reject("empty PE", new byte[0]);
        Reject("truncated PE", original.Take(128).ToArray());

        string dependency = references.First(x => Path.GetFileName(x) == "HLNetworking.Runtime.ref.dll" || Path.GetFileName(x) == "HLNetworking.Runtime.dll");
        string wrong = Path.Combine(Path.GetDirectoryName(output), "nonempty-marker", "HLNetworking.Runtime.dll"); Directory.CreateDirectory(Path.GetDirectoryName(wrong));
        using (var marker = ModuleDefinition.ReadModule(dependency))
        {
            var type = marker.Types.Single(x => x.Name == "EncodableMessage");
            type.Methods.Add(new MethodDefinition("Invented", MethodAttributes.Public | MethodAttributes.Virtual | MethodAttributes.NewSlot | MethodAttributes.Abstract, marker.TypeSystem.Void));
            marker.Write(wrong);
        }
        Reject("invented marker contract", original, references.Select(x => Path.GetFileName(x).StartsWith("HLNetworking.Runtime.") ? wrong : x).ToArray());
        File.WriteAllBytes(output,result.InMemoryAssembly.PeData);File.WriteAllBytes(Path.ChangeExtension(output,".pdb"),result.InMemoryAssembly.PdbData);
        return checks;
    }
}
