namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200003e; serialized Int32 literals.
    public enum AbilityAimTargetType
    {
        None = 0,
        Air = -717748850,
        CatchReleaseTightrope = 1645303179,
        CatchReleaseTrampoline = 657193873,
        ChaosDashSwitch = -1629712951,
        HomingSwitch = 2112396014,
        HomingTarget = 1416560138,
        Ledge = -972465052,
        Rail = -1875445302,
        SpeedRing = 2077728114,
        SpringWide = -1641578838,
        Track = -565656087,
        Transporter = -758476861,
        Wall = -627049027
    }
}
