namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000044; serialized Int32 literals.
    public enum AbilityInputType
    {
        None = 0,
        Continuous = -26092743,
        Single = -979361952,
        SingleToggle = 1419479305,
        UntilRelease = 610156752
    }
}
