namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000042; serialized Int32 literals.
    public enum AbilityAimTransformType
    {
        None = 0,
        AimTranslate = 24510531,
        AimTranslateCameraFacing = 1039009841,
        AimTranslateRotate = -1326851684,
        AimTranslateWorldUp = -342567751,
        GroundTranslate = 2049053384,
        GroundTranslateCameraFacing = 405325295,
        GroundTranslateRotate = -1032460767
    }
}
