namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000046; serialized Int32 values.
    public enum AccessibilityFailState
    {
        Default = 602145082,
        Invincible = -819389673,
        NoFail = 809165625
    }
}
