namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000052; serialized Int32 literals.
    public enum ActorFormType
    {
        AirAbilityWithProp = 1758239437,
        Ball = -1118283248,
        CatchReleaseBall = -177138913,
        Default = 602145082,
        None = -1225125244
    }
}
