namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200004c; serialized Int32 literals.
    public enum ActorAnimationType
    {
        AirTilt = -511368675,
        BoolEnter = 1542466261,
        BoolExit = -1544332351,
        BoolSet = -879072719,
        Boss_Speed = -1928463692,
        Boss_Telegraph_Choice = 236300208,
        Boss_Use_Left = -157113000,
        Boss_Use_Right = 2079543231,
        Boss_XDirection = 2145227292,
        Boss_ZDirection = 2066235937,
        CameraXRotation = 1865480815,
        CameraYRotation = 2018242092,
        ClimbSpeedX = -715206254,
        ClimbSpeedY = -1571167996,
        DashLaunchPower = -1814131064,
        DirectionOverride = -1030618522,
        Enemy_Movement = -1508908224,
        Enemy_Movement_BoolSet = 820710750,
        Enemy_Movement_Lateral = 1176815887,
        Enemy_Movement_Turning = -768958372,
        IdleStepLeft = 1509017519,
        IdleStepRight = 1485142882,
        SetAttackTrigger = -119706263,
        TriggerEnter = -1074613321,
        TriggerExit = -1348128179,
        TriggerSet = 736681722
    }
}
