using System.Collections.Generic;
using Unity.IL2CPP.CompilerServices;

namespace Hardlight.Analytics
{
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class AnalyticsConsentStateEqualityComparer : IEqualityComparer<AnalyticsConsentState>
    {
        // Original HLAutoGenerated 060000dc/dd: compare the Int32 value; hash is that same value.
        public bool Equals(AnalyticsConsentState a, AnalyticsConsentState b) => a == b;
        public int GetHashCode(AnalyticsConsentState a) => (int)a;
        public AnalyticsConsentStateEqualityComparer() { }
    }
}
