using System.Collections.Generic;
using Unity.IL2CPP.CompilerServices;

namespace Hardlight.Analytics
{
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class AnalyticsMissionTypeEqualityComparer : IEqualityComparer<AnalyticsMissionType>
    {
        // Original HLAutoGenerated 060000e4/e5: compare the Int32 value; hash is that same value.
        public bool Equals(AnalyticsMissionType a, AnalyticsMissionType b) => a == b;
        public int GetHashCode(AnalyticsMissionType a) => (int)a;
        public AnalyticsMissionTypeEqualityComparer() { }
    }
}
