namespace Hardlight.Analytics
{
    // Original HLAutoGenerated0200003c: complete literal enum, no native bodies.
    public enum AnalyticsMissionType
    {
        Boss = -141265807,
        Challenge = 1815373889,
        Persistent = 1400675871,
        Regular = -1966407119,
    }
}
