namespace Hardlight.Analytics
{
    // Original HLAutoGenerated 0x02000038; serialized Int32 values.
    public enum AnalyticsConsentState
    {
        None = 0,
        Consented = -324521923,
        Rejected = -1147781194,
        Underage = 1042743376
    }
}
