using System.Collections.Generic;
using Unity.IL2CPP.CompilerServices;

namespace Hardlight.Analytics
{
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public static class HardlightEnumExtensions
    {
        // Original HLAutoGenerated 060000e3: build each table completely before publishing it.
        // These are mutable static fields in the original, not readonly fields or synchronized caches.
        private static Dictionary<AnalyticsConsentState, string> AnalyticsConsentStateEnumToString =
            new Dictionary<AnalyticsConsentState, string>(HardlightEnumComparers.AnalyticsConsentStateComparer)
            {
                { AnalyticsConsentState.None, "None" },
                { AnalyticsConsentState.Consented, "Consented" },
                { AnalyticsConsentState.Rejected, "Rejected" },
                { AnalyticsConsentState.Underage, "Underage" }
            };
        private static Dictionary<AnalyticsMissionType, string> AnalyticsMissionTypeEnumToString =
            new Dictionary<AnalyticsMissionType, string>(HardlightEnumComparers.AnalyticsMissionTypeComparer)
            {
                { AnalyticsMissionType.Boss, "Boss" },
                { AnalyticsMissionType.Challenge, "Challenge" },
                { AnalyticsMissionType.Persistent, "Persistent" },
                { AnalyticsMissionType.Regular, "Regular" }
            };

        // Original 060000e1/e2 boxes the enum for String.Format, then re-reads the field for set_Item.
        // Unknown values are cached through the indexer; caller changes to the existing table remain observable.
        public static string GetString(this AnalyticsConsentState value)
        {
            string text;
            if (AnalyticsConsentStateEnumToString.TryGetValue(value, out text)) return text;
            text = string.Format("0x{0:X}", value);
            AnalyticsConsentStateEnumToString[value] = text;
            return text;
        }

        public static string GetString(this AnalyticsMissionType value)
        {
            string text;
            if (AnalyticsMissionTypeEnumToString.TryGetValue(value, out text)) return text;
            text = string.Format("0x{0:X}", value);
            AnalyticsMissionTypeEnumToString[value] = text;
            return text;
        }
    }
}
