namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000056; serialized Int32 literals.
    public enum ApplicationSettings
    {
        None = 0,
        GameScene = -730590467,
        SceneOperation = -1706162214
    }
}
