namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000058; serialized Int32 literals.
    public enum AutoTestType
    {
        CycleLevels = -807588611,
        InputReachDestination = 1340754004,
        LoadLevel = 214172682
    }
}
