namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200005a; serialized Int32 literals.
    public enum BonusZoneIsNewState
    {
        None = 0,
        IsNew = -1216131765,
        Seen = 1832392787
    }
}
