namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000060; serialized Int32 literals.
    public enum BossMovementTypes
    {
        Boss_Backward = -2136179295,
        Boss_Forward = -847228250,
        Boss_Left = 1459426360,
        Boss_Right = 920744278,
        Boss_Stationary = 1693591543
    }
}
