namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200005e; serialized Int32 literals.
    public enum BossEffectTriggerTypes
    {
        None = 0,
        AttackStrike = 863959223,
        BattleStart = -406353131,
        Dead = 609180527,
        EaseInMotion = 1797805171,
        Injured = -79364008,
        MovingBecomeInvulnerable = 1184055252,
        MovingBecomeVulnerable = -996958514,
        MovingInjured = 380070044,
        Phase1To2TransitionEnd = -1542752738,
        Phase1To2TransitionStart = 1600385748,
        Phase2To3TransitionEnd = 1788792044,
        Phase2To3TransitionStart = 1381885420,
        Phase3To4TransitionEnd = -1997165201,
        Phase3To4TransitionStart = 2017893825,
        PreVulnerable = 2132606998,
        Recovery = -896536454,
        TargetingChargeAttack = 1143687086,
        TargetingChargeAttackEnd = -1451689851,
        Vulnerable = -315201363,
        WindUp = -1431654692
    }
}
