namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200005c; serialized Int32 literals.
    public enum BossAttackTypes
    {
        None = 0,
        BossCrab_Body = -99070815,
        BossCrab_LeftClaw = -1144350659,
        BossCrab_RightClaw = -755926426,
        BossFourman_FloorElectric = -354719778,
        BossFourmen_ChargeAttack = 1355926913,
        BossFourmen_LaserFence = 1313126502
    }
}
