namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000062; serialized Int32 values.
    public enum ButtonMappingType
    {
        None = 0,
        All = 1379978408,
        Primary = -671093917,
        Secondary = -1603365627
    }
}
