namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200006a; serialized Int32 literals.
    public enum CameraSettingType
    {
        ActiveCamera = 1574176304,
        HeadingOverride = 229453224,
        ProxySettingOverride = -535163133
    }
}
