namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000068; serialized Int32 values.
    public enum CameraSensitivityType
    {
        None = 0,
        High = 946861598,
        Low = -70203948,
        Medium = -915112498,
        VeryHigh = -1925819726,
        VeryLow = 1924880489
    }
}
