namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000064; serialized Int32 values.
    public enum CameraConfigurationType
    {
        None = 0,
        Default = 602145082,
        Far = 414095619,
        Near = -1088024998
    }
}
