namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200006e; serialized Int32 literals.
    public enum CameraYOverrideLayer
    {
        Cutscene = 858960670,
        Default = 602145082,
        Override = -1144036010,
        SetPiece = -1243284990
    }
}
