namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000066; serialized Int32 values.
    public enum CameraRecenterHeadingType
    {
        None = 0,
        Medium = -915112498
    }
}
