namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200006c; serialized Int32 literals.
    public enum CameraType
    {
        None = 0,
        AttachedToPoint = 1395441410,
        Bidirectional = 554924001,
        ChaosAim = -709212659,
        ChaosDash = -336621300,
        Climbing = -29053560,
        Death = -269686687,
        Default = 602145082,
        FarFreeLook = 797704553,
        Fly = 986857158,
        Gliding = 590959812,
        GroundedFarWorldSpace = -772737368,
        GroupTarget = -293108464,
        HalfPipeAir = 335681514,
        HubLevelSelect = -640752989,
        HubOrbDeposit = 1386625689,
        OffsetLeft = -600592771,
        OffsetRight = 819792627,
        OrbCollection = 541755685,
        Rail = -1875445302,
        Replay = -701444981,
        RollingFreeLookCamera = 1381420339,
        SpinDashChargeCamera = -162056224,
        SpinDashChargeCamera_Stationary = 1141279443,
        SuperFarFreeLook = -1546194871,
        WallRun = 901006308
    }
}
