namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000074; serialized Int32 literals.
    public enum CatchReleasePositionType
    {
        Free = -2075864189,
        Last = -2085504021,
        Next = -851115401,
        QuantizeClosestAngle = -166181789,
        QuantizeClosestPosition = -96326708
    }
}
