namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000076; serialized Int32 literals.
    public enum CatchReleaseRotationType
    {
        ClosestRotationLookup = 137093377,
        Free = -2075864189,
        FreeLookup = 354273513,
        Last = -2085504021,
        Next = -851115401,
        QuantizeClosestAngle = -166181789,
        QuantizeClosestPosition = -96326708
    }
}
