namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000072; serialized Int32 literals.
    public enum CatchInputReleaseType
    {
        None = 0,
        ToAir = -490796319,
        ToJump = -1276907621
    }
}
