namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200007c; serialized Int32 literals.
    public enum ChallengeZoneMaterialType
    {
        Atlas = 2057431872,
        EmissivePlatform = 1989495046,
        PlatformTop = -175964542,
        PlatformWall = -2106215696,
        Track = -565656087
    }
}
