namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200007a; serialized Int32 literals.
    public enum ChallengeZoneIdentifier
    {
        BlackAndWhite = 818740382,
        BonusZone = -1714307003,
        DarkPurple = -1199708436,
        GHZ = -965361585,
        Gold = -1899819238,
        Zone1 = 786271315,
        Zone2 = -1210786327,
        Zone3 = -1059852929,
        Zone4 = 1589082332
    }
}
