namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000087; serialized Int32 literals.
    public enum CharacterTrackingType
    {
        Active = 1142539387,
        ColliderFree = -77014468,
        ColliderTracker = 1103185330,
        SurfaceTracker = 1986424637
    }
}
