namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200007e; serialized Int32 literals.
    public enum CharacterAbilityUIType
    {
        None = 0,
        Air = -717748850,
        AirSuper = 143168528,
        Boost = 1590630951,
        BoostCapacity = 1098483541,
        ChaosAim = -709212659,
        ChaosStamina = -1660740281,
        SpinDashCharge = -1275830989
    }
}
