namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000082; serialized Int32 literals.
    public enum CharacterId
    {
        None = 0,
        Amy = 646322434,
        Cream = -791355120,
        Knuckles = -201893054,
        Rouge = 1803574436,
        Shadow = 2054273620,
        Sonic = 829665598,
        Tails = 100919481
    }
}
