namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000084; serialized Int32 literals.
    public enum CharacterStats
    {
        None = 0,
        Attack = 1221006658,
        AttackAddition = 1942535105,
        AttackBase = 2733519,
        AttackMultiplier = 923826561,
        Defence = 1373497025,
        DefenceAddition = 878169522,
        DefenceBase = -1677642872,
        DefenceMultiplier = -1973108702,
        Luck = 1599385571,
        LuckAddition = -669490366,
        LuckBase = -460788617,
        LuckMultiplier = -1347009729,
        Speed = 126731193,
        SpeedAddition = 1840931632,
        SpeedBase = 884971109,
        SpeedMultiplier = -1296044567
    }
}
