namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000080; serialized Int32 literals.
    public enum CharacterArchetype
    {
        None = 0,
        Climbing = -29053560,
        Dashing = -825660132,
        Flying = 1160987322,
        Shadow = 2054273620
    }
}
