namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200008b; serialized Int32 literals.
    public enum CollectableType
    {
        None = 0,
        BlueCoin = -64614013,
        BoostEnergy = -1361159949,
        BoostEnergyGroup = -368511499,
        ChaosEnergy = -1409458894,
        ChaosEnergyGroup = 1323288656,
        FakeRing = -86868103,
        Moon = 713446819,
        MusicTrack = 731344614,
        Orb = 1797780346,
        RedStarRing = 1571688228,
        Ring = 1186391869
    }
}
