namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000089; serialized Int32 literals.
    public enum CollectableSource
    {
        None = 0,
        DamageTaken = 433872206,
        Dropped = 305924180,
        Level = -1841172132,
        LevelRespawned = -2081560202,
        MissionReward = -1915994904,
        MissionStart = -2116862092,
        RSR = 2071323260
    }
}
