namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200008d; serialized Int32 literals.
    public enum CollectAction
    {
        None = 0,
        End = 1772392132,
        Start = -1747818304
    }
}
