namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200008f; serialized Int32 literals.
    public enum ComparisonType
    {
        None = 0,
        Equal = 637544632,
        GreaterThan = 803474623,
        GreaterThanEqual = 2070626358,
        LessThan = 1167406326,
        LessThanEqual = -784979190,
        NotEqual = -1672765598
    }
}
