using System.Collections.Generic;
using Unity.IL2CPP.CompilerServices;

namespace Hardlight
{
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class HardlightEnumComparers
    {
        // Original HLAutoGenerated0600009e/9f: readonly initializers preserve
        // BeforeFieldInit and the eleven original allocation/store positions.
        public static readonly BuildFeaturesEqualityComparer BuildFeaturesComparer = new BuildFeaturesEqualityComparer();
        public static readonly DialogPageIdentifierEqualityComparer DialogPageIdentifierComparer = new DialogPageIdentifierEqualityComparer();
        public static readonly DynamicPageEntryEqualityComparer DynamicPageEntryComparer = new DynamicPageEntryEqualityComparer();
        public static readonly GameInputEqualityComparer GameInputComparer = new GameInputEqualityComparer();
        public static readonly HLAudioTypesEqualityComparer HLAudioTypesComparer = new HLAudioTypesEqualityComparer();
        public static readonly MenuPageIdentifierEqualityComparer MenuPageIdentifierComparer = new MenuPageIdentifierEqualityComparer();
        public static readonly OverlayPageIdentifierEqualityComparer OverlayPageIdentifierComparer = new OverlayPageIdentifierEqualityComparer();
        public static readonly SubPageIdentifierEqualityComparer SubPageIdentifierComparer = new SubPageIdentifierEqualityComparer();
        public static readonly UIContainerBehaviourEqualityComparer UIContainerBehaviourComparer = new UIContainerBehaviourEqualityComparer();
        public static readonly VibrationEventEqualityComparer VibrationEventComparer = new VibrationEventEqualityComparer();
        public static readonly VibrationTypeEqualityComparer VibrationTypeComparer = new VibrationTypeEqualityComparer();
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class BuildFeaturesEqualityComparer : IEqualityComparer<BuildFeatures>
    {
        // Original 0x0600009b/0x0600009c: compare/return raw signed Int32 bits.
        public bool Equals(BuildFeatures a, BuildFeatures b) { return a == b; }
        public int GetHashCode(BuildFeatures a) { return (int)a; }
        // Original 0x0600009d: genuine Object base-only constructor.
    }

    // Complete original Int32 enum; literals have no own method credit.
    public enum BuildFeatures
    {
        ADDRESSABLES_LOG_ALL = 852488745,
        APPLE_PLUGIN_CONTROLLER = -829591276,
        ASSETBUNDLES = -1552620311,
        AUTOPLAY = 182668702,
        BUILD_DEVELOPMENT = -819537757,
        BUILD_DISTRIBUTION = -649120839,
        CRASH_REPORT_TARGET_NONE = -585780043,
        CRASH_REPORT_TARGET_PRODUCTION = -581789519,
        CRASH_REPORT_TARGET_QA = 1440316928,
        DEBUG_MENU = -943841426,
        DISABLE_NATIVE_CRASH_REPORTS = 969133102,
        DREAMTECK_SPLINES = -718875151,
        EDITOR_BOOT_FLOW = -774550052,
        GC_ENABLED = -103100648,
        HLACHIEVEMENTS = 1146533422,
        HLNOTIFICATIONS_APNS = 2072488686,
        HLNOTIFICATIONS_DISABLED = -88698752,
        ICLOUD = 1698702977,
        PREFAB_STAGE_SCENE_FIX = -1385145447,
        TVOS_PATCH_202237 = -183182728,
        USE_NATIVE_SCRIPTS_UNBUNDLED = 386292194,
        USE_PREFAB_UI = 285868814,
        USING_HLINPUT = 1382603853,
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class DialogPageIdentifierEqualityComparer : IEqualityComparer<DialogPageIdentifier>
    {
        // Original 0x060000aa/0x060000ab: compare/return raw signed Int32 bits.
        public bool Equals(DialogPageIdentifier a, DialogPageIdentifier b) { return a == b; }
        public int GetHashCode(DialogPageIdentifier a) { return (int)a; }
        // Original 0x060000ac: genuine Object base-only constructor.
    }

    // Complete original Int32 enum; literals have no own method credit.
    public enum DialogPageIdentifier
    {
        None = 0,
    }

    public class DynamicPageEntryEqualityComparer : IEqualityComparer<DynamicPageEntry>
    {
        // Original 0x060000ad/0x060000ae: compare/return raw signed Int32 bits.
        public bool Equals(DynamicPageEntry a, DynamicPageEntry b) { return a == b; }
        public int GetHashCode(DynamicPageEntry a) { return (int)a; }
        // Original 0x060000af: genuine Object base-only constructor.
    }

    // Complete original Int32 enum; literals have no own method credit.
    public enum DynamicPageEntry
    {
        None = -1225125244,
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class GameInputEqualityComparer : IEqualityComparer<GameInput>
    {
        // Original 0x060000b3/0x060000b4: compare/return raw signed Int32 bits.
        public bool Equals(GameInput a, GameInput b) { return a == b; }
        public int GetHashCode(GameInput a) { return (int)a; }
        // Original 0x060000b5: genuine Object base-only constructor.
    }

    // Complete original Int32 enum; literals have no own method credit.
    public enum GameInput
    {
        Up = 310449637,
        Down = -711622032,
        Left = -1290930909,
        Right = -1134475173,
        Tap = -385708239,
        Touch = -31649603,
        TouchRelease = -2133640155,
        PointerMove = -10328679,
        Back = -1532701828,
        TogglePauseMenu = -1921691584,
        ToggleDebugMenu = -151822342,
        ToggleCharacterSelectMenu = -1815295551,
        ScrollUp = -1416120585,
        ScrollDown = -490817049,
        CharacterMovementComposite = -299269436,
        CharacterMovementHorizontal = 1124087787,
        CharacterMovementVertical = 1378906170,
        CharacterSelectNext = 85168050,
        CharacterSelectPrev = -1109518373,
        DebugRestart = -732816511,
        DebugInfo = 1118375777,
        DebugNextInfo = -1784190173,
        DebugToggleHud = -890518523,
        DebugGamePause = -1136321503,
        DebugGameSpeedInc = 1019647874,
        DebugGameSpeedDec = -672473830,
        DebugGameSpeed = 1694068794,
        DebugClearFsmInfo = -1585513644,
        DebugRespawn = -618298903,
        BossDebugInfo = -2020747454,
        SkipMissionIntros = -749285817,
        UISubmit = 679688440,
        UIBack = 1031933631,
        UIUp = -242970151,
        UIDown = 1286823859,
        UILeft = 707471584,
        UIRight = -1097466484,
        UINext = 1415831476,
        UIPrevious = -1868058336,
        UISecondaryOption = 60201069,
        UITertiaryOption = -1973697371,
        UIQuaternaryOption = 1628466736,
        UIOptions = 1711140173,
        UILeaderboards = -1335372061,
        UICutsceneTheatre = -1545305605,
        UILoadSave = -691498275,
        UICollectionsTabBackwards = -1063646013,
        UICollectionsTabForwards = 1842779468,
        CameraMaintainHeading = 90132934,
        CameraSnapBehindTarget = 1758640220,
        CameraLeft = 1306115145,
        CameraRight = 301470804,
        CameraUp = 1084067301,
        CameraDown = 725732122,
        CameraMovementComposite = 1677837509,
        CameraMovementHorizontal = 881667899,
        CameraMovementVertical = 532651297,
        CameraMovementSecondaryComposite = 148437820,
        CameraMovementSecondaryHorizontal = -259998532,
        CameraMovementSecondaryVertical = -1072330379,
        SkipCutscene = -2085301933,
        SkipBossPhase = 153010635,
        PromptOption1 = 1965771899,
        PromptOption2 = -333308479,
        PromptContinue = 434785342,
        None = -1225125244,
        DebugToggleCharacterUI = -1368588321,
        ToggleGameSpeed = 16603278,
        UIRightSecondary = -1062754550,
        UILeftSecondary = -1028600470,
        DisableAllInput = -247637044,
        IssueTrackerClose = -6138428,
        IssueTrackerEnd = -111862399,
        SkipTheSplash = 702329143,
        ControllerConnected = 113222705,
        ReleaseCursor = 359270783,
        GamepadButtonNorth = -165875217,
        GamepadButtonEast = 1632841687,
        GamepadButtonSouth = 1797502041,
        GamepadButtonWest = -1672865761,
        GamepadDpadUp = -1919157662,
        GamepadDpadRight = 2090816408,
        GamepadDpadDown = -1847399409,
        GamepadDpadLeft = -142959780,
        KeyboardW = 666433865,
        KeyboardA = -747877352,
        KeyboardS = 550845776,
        KeyboardD = -1559840617,
        KeyboardSpace = 1193814399,
        KeyboardShiftLeft = 1299130756,
        KeyboardShiftRight = -198370100,
        KeyboardCtrlLeft = 1623496488,
        KeyboardCtrlRight = 727734449,
        KeyboardArrowUp = -1995486336,
        KeyboardArrowDown = 1103952623,
        KeyboardArrowLeft = 659852732,
        KeyboardArrowRight = -599416842,
        TouchButtonPrimary = 234956511,
        TouchButtonSecondary = 231412546,
        TouchButtonTertiary = 505897007,
        TouchZoneLeftSwipeUp = -930026960,
        TouchZoneLeftSwipeDown = 81299126,
        TouchZoneLeftSwipeLeft = 1648423397,
        TouchZoneLeftSwipeRight = -826842406,
        TouchZoneRightSwipeUp = -1420833722,
        TouchZoneRightSwipeDown = -1347371292,
        TouchZoneRightSwipeLeft = -920073801,
        TouchZoneRightSwipeRight = 1266235962,
        GameActionCancel = 807785871,
    }

    public class HLAudioTypesEqualityComparer : IEqualityComparer<HLAudioTypes>
    {
        // Original 0x060000b6/0x060000b7: compare/return raw signed Int32 bits.
        public bool Equals(HLAudioTypes a, HLAudioTypes b) { return a == b; }
        public int GetHashCode(HLAudioTypes a) { return (int)a; }
        // Original 0x060000b8: genuine Object base-only constructor.
    }

    // Complete original Int32 enum; literals have no own method credit.
    public enum HLAudioTypes
    {
        None = -1225125244,
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class MenuPageIdentifierEqualityComparer : IEqualityComparer<MenuPageIdentifier>
    {
        // Original 0x060000b9/0x060000ba: compare/return raw signed Int32 bits.
        public bool Equals(MenuPageIdentifier a, MenuPageIdentifier b) { return a == b; }
        public int GetHashCode(MenuPageIdentifier a) { return (int)a; }
        // Original 0x060000bb: genuine Object base-only constructor.
    }

    // Complete original Int32 enum; literals have no own method credit.
    public enum MenuPageIdentifier
    {
        None = 0,
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class OverlayPageIdentifierEqualityComparer : IEqualityComparer<OverlayPageIdentifier>
    {
        // Original 0x060000bc/0x060000bd: compare/return raw signed Int32 bits.
        public bool Equals(OverlayPageIdentifier a, OverlayPageIdentifier b) { return a == b; }
        public int GetHashCode(OverlayPageIdentifier a) { return (int)a; }
        // Original 0x060000be: genuine Object base-only constructor.
    }

    // Complete original Int32 enum; literals have no own method credit.
    public enum OverlayPageIdentifier
    {
        None = 0,
        general_information = 1753178996,
        general_text_entry = 2001913270,
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class SubPageIdentifierEqualityComparer : IEqualityComparer<SubPageIdentifier>
    {
        // Original 0x060000bf/0x060000c0: compare/return raw signed Int32 bits.
        public bool Equals(SubPageIdentifier a, SubPageIdentifier b) { return a == b; }
        public int GetHashCode(SubPageIdentifier a) { return (int)a; }
        // Original 0x060000c1: genuine Object base-only constructor.
    }

    // Complete original Int32 enum; literals have no own method credit.
    public enum SubPageIdentifier
    {
        None = 0,
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class UIContainerBehaviourEqualityComparer : IEqualityComparer<UIContainerBehaviour>
    {
        // Original 0x060000c2/0x060000c3: compare/return raw signed Int32 bits.
        public bool Equals(UIContainerBehaviour a, UIContainerBehaviour b) { return a == b; }
        public int GetHashCode(UIContainerBehaviour a) { return (int)a; }
        // Original 0x060000c4: genuine Object base-only constructor.
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class VibrationEventEqualityComparer : IEqualityComparer<VibrationEvent>
    {
        // Original 0x060000c5/0x060000c6: compare/return raw signed Int32 bits.
        public bool Equals(VibrationEvent a, VibrationEvent b) { return a == b; }
        public int GetHashCode(VibrationEvent a) { return (int)a; }
        // Original 0x060000c7: genuine Object base-only constructor.
    }

    // Complete original Int32 enum; literals have no own method credit.
    public enum VibrationEvent
    {
        None = 0,
        DefaultSelection = 890026456,
        LongPressSelection = -1688333712,
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class VibrationTypeEqualityComparer : IEqualityComparer<VibrationType>
    {
        // Original 0x060000c8/0x060000c9: compare/return raw signed Int32 bits.
        public bool Equals(VibrationType a, VibrationType b) { return a == b; }
        public int GetHashCode(VibrationType a) { return (int)a; }
        // Original 0x060000ca: genuine Object base-only constructor.
    }

    // Complete original Int32 enum; literals have no own method credit.
    public enum VibrationType
    {
        ImpactHeavy = 1827081371,
        ImpactLight = 2110532147,
        ImpactMedium = -1291822547,
        None = -1225125244,
        NotificationFailure = -1035786528,
        NotificationSuccess = -1931937133,
        NotificationWarning = -1550403097,
        Selection = 764997063,
    }

}
