namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000091; serialized Int32 literals.
    public enum CutsceneTriggerType
    {
        None = 0,
        EndCredits = 1012908021,
        OnBossPhaseChanged = 436454596,
        OnFirstTimeUserExperience = 515562715,
        OnLevelEntered = 1677083852,
        OnLevelSelected = 1477237002,
        OnMissionCompleted = 1289295332,
        OnPreFTUE = -1023738455,
        OnPreFTUEPartII = -1202694892,
        OnResultsScreenClosed = -302145006,
        OnStoryCompleted = -1189723638,
        OnStoryCompletedPartII = 1900204192,
        OnStoryIntroMovie = -1998946443,
        OnTriggerVolumeEntered = -215111142,
        OnTriggerVolumeEnteredA = -62216746,
        OnTriggerVolumeEnteredB = 1698952300,
        OnTriggerVolumeEnteredC = 306496762,
        OnTriggerVolumeEnteredD = -1944039079,
        OnTriggerVolumeEnteredE = -81305137,
        OnTriggerVolumeEnteredF = 1647194229,
        OnTriggerVolumeEnteredG = 355008739,
        PreMainMenu = 814128972,
        QueueOnly = 1282561693
    }
}
