namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000093; serialized Int32 literals.
    public enum DamageAction
    {
        None = 0,
        HardFailure = -79012507,
        Knockback = 395657665,
        ReturnDamage = 680174195,
        Stumble = 1465431465
    }
}
