namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000095; serialized Int32 literals.
    public enum DirectionModifierType
    {
        Acceleration = 280691604,
        Constant = -223955349,
        Override = -1144036010,
        Speed = 126731193
    }
}
