namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000099; serialized Int32 literals.
    public enum DreamPowerStoreIsNewState
    {
        None = 0,
        IsNew = -1216131765,
        Seen = 1832392787
    }
}
