namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000097; serialized Int32 literals.
    public enum DreamPowerStoreBandType
    {
        None = 0,
        Band1 = -2021058974,
        Band2 = 511723480,
        Band3 = 1770485582,
        Band4 = -136060179
    }
}
