namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200009b; serialized Int32 literals.
    public enum EnemyType
    {
        BuzzBomberBlind = 1830085438,
        BuzzBomberPatrol = 1548971855,
        BuzzBomberStatic = -681024485,
        Caterkiller = -1065967328,
        Crabmeat = -168170620,
        EggPawn = 1390775171,
        Motobug = -338720403
    }
}
