namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200009f; serialized Int32 literals.
    public enum EntityActivationType
    {
        ChaosEnergyCollectable = -1839350601,
        Collectable = -1437085034,
        CollectableNoRespawn = 252198587,
        CollectableResetOnly = -374863333,
        CutsceneWait = 1329718479,
        Enemy = -214669338,
        LevelVisibility = 106832432,
        Platform = 10400632
    }
}
