namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200009d; serialized Int32 literals.
    public enum EntityActivationLogicType
    {
        CharacterRespawn = 970087518,
        CutsceneWait = 1329718479,
        Distance = 626981170,
        LevelActivate = -1170915883,
        LevelRestart = 229708490,
        MissionActivate = -822031679,
        PlatformReset = 1342395744,
        Time = -1493267954
    }
}
