using System.Collections.Generic;
using Unity.IL2CPP.CompilerServices;

namespace HardlightProject
{
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class AbilityAimTargetTypeEqualityComparer : IEqualityComparer<AbilityAimTargetType>
    {
        // HLAutoGenerated 0x060000e7: native compares the raw Int32 values.
        public bool Equals(AbilityAimTargetType a, AbilityAimTargetType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060000e8: native returns the raw signed Int32.
        public int GetHashCode(AbilityAimTargetType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060000e9: native delegates only to Object constructor.
        public AbilityAimTargetTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class AbilityAimTransformTypeEqualityComparer : IEqualityComparer<AbilityAimTransformType>
    {
        // HLAutoGenerated 0x06000158: native compares the raw Int32 values.
        public bool Equals(AbilityAimTransformType a, AbilityAimTransformType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000159: native returns the raw signed Int32.
        public int GetHashCode(AbilityAimTransformType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600015a: native delegates only to Object constructor.
        public AbilityAimTransformTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class AbilityInputTypeEqualityComparer : IEqualityComparer<AbilityInputType>
    {
        // HLAutoGenerated 0x0600015b: native compares the raw Int32 values.
        public bool Equals(AbilityInputType a, AbilityInputType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600015c: native returns the raw signed Int32.
        public int GetHashCode(AbilityInputType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600015d: native delegates only to Object constructor.
        public AbilityInputTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class AccessibilityFailStateEqualityComparer : IEqualityComparer<AccessibilityFailState>
    {
        // HLAutoGenerated 0x0600015e: native compares the raw Int32 values.
        public bool Equals(AccessibilityFailState a, AccessibilityFailState b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600015f: native returns the raw signed Int32.
        public int GetHashCode(AccessibilityFailState a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000160: native delegates only to Object constructor.
        public AccessibilityFailStateEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class AchievementIdentifierEqualityComparer : IEqualityComparer<AchievementIdentifier>
    {
        // HLAutoGenerated 0x06000161: native compares the raw Int32 values.
        public bool Equals(AchievementIdentifier a, AchievementIdentifier b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000162: native returns the raw signed Int32.
        public int GetHashCode(AchievementIdentifier a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000163: native delegates only to Object constructor.
        public AchievementIdentifierEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class ActorAbilityTypeEqualityComparer : IEqualityComparer<ActorAbilityType>
    {
        // HLAutoGenerated 0x06000164: native compares the raw Int32 values.
        public bool Equals(ActorAbilityType a, ActorAbilityType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000165: native returns the raw signed Int32.
        public int GetHashCode(ActorAbilityType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000166: native delegates only to Object constructor.
        public ActorAbilityTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class ActorAnimationTypeEqualityComparer : IEqualityComparer<ActorAnimationType>
    {
        // HLAutoGenerated 0x06000167: native compares the raw Int32 values.
        public bool Equals(ActorAnimationType a, ActorAnimationType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000168: native returns the raw signed Int32.
        public int GetHashCode(ActorAnimationType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000169: native delegates only to Object constructor.
        public ActorAnimationTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class ActorAttachPointTypeEqualityComparer : IEqualityComparer<ActorAttachPointType>
    {
        // HLAutoGenerated 0x0600016a: native compares the raw Int32 values.
        public bool Equals(ActorAttachPointType a, ActorAttachPointType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600016b: native returns the raw signed Int32.
        public int GetHashCode(ActorAttachPointType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600016c: native delegates only to Object constructor.
        public ActorAttachPointTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class ActorAudioTypesEqualityComparer : IEqualityComparer<ActorAudioTypes>
    {
        // HLAutoGenerated 0x0600016d: native compares the raw Int32 values.
        public bool Equals(ActorAudioTypes a, ActorAudioTypes b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600016e: native returns the raw signed Int32.
        public int GetHashCode(ActorAudioTypes a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600016f: native delegates only to Object constructor.
        public ActorAudioTypesEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class ActorFormTypeEqualityComparer : IEqualityComparer<ActorFormType>
    {
        // HLAutoGenerated 0x06000170: native compares the raw Int32 values.
        public bool Equals(ActorFormType a, ActorFormType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000171: native returns the raw signed Int32.
        public int GetHashCode(ActorFormType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000172: native delegates only to Object constructor.
        public ActorFormTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class ActorParticleTriggerTypeEqualityComparer : IEqualityComparer<ActorParticleTriggerType>
    {
        // HLAutoGenerated 0x06000173: native compares the raw Int32 values.
        public bool Equals(ActorParticleTriggerType a, ActorParticleTriggerType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000174: native returns the raw signed Int32.
        public int GetHashCode(ActorParticleTriggerType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000175: native delegates only to Object constructor.
        public ActorParticleTriggerTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class ApplicationSettingsEqualityComparer : IEqualityComparer<ApplicationSettings>
    {
        // HLAutoGenerated 0x06000176: native compares the raw Int32 values.
        public bool Equals(ApplicationSettings a, ApplicationSettings b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000177: native returns the raw signed Int32.
        public int GetHashCode(ApplicationSettings a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000178: native delegates only to Object constructor.
        public ApplicationSettingsEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class AutoTestTypeEqualityComparer : IEqualityComparer<AutoTestType>
    {
        // HLAutoGenerated 0x06000179: native compares the raw Int32 values.
        public bool Equals(AutoTestType a, AutoTestType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600017a: native returns the raw signed Int32.
        public int GetHashCode(AutoTestType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600017b: native delegates only to Object constructor.
        public AutoTestTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class BonusZoneIsNewStateEqualityComparer : IEqualityComparer<BonusZoneIsNewState>
    {
        // HLAutoGenerated 0x0600017c: native compares the raw Int32 values.
        public bool Equals(BonusZoneIsNewState a, BonusZoneIsNewState b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600017d: native returns the raw signed Int32.
        public int GetHashCode(BonusZoneIsNewState a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600017e: native delegates only to Object constructor.
        public BonusZoneIsNewStateEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class BossAttackTypesEqualityComparer : IEqualityComparer<BossAttackTypes>
    {
        // HLAutoGenerated 0x0600017f: native compares the raw Int32 values.
        public bool Equals(BossAttackTypes a, BossAttackTypes b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000180: native returns the raw signed Int32.
        public int GetHashCode(BossAttackTypes a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000181: native delegates only to Object constructor.
        public BossAttackTypesEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class BossEffectTriggerTypesEqualityComparer : IEqualityComparer<BossEffectTriggerTypes>
    {
        // HLAutoGenerated 0x06000182: native compares the raw Int32 values.
        public bool Equals(BossEffectTriggerTypes a, BossEffectTriggerTypes b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000183: native returns the raw signed Int32.
        public int GetHashCode(BossEffectTriggerTypes a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000184: native delegates only to Object constructor.
        public BossEffectTriggerTypesEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class BossMovementTypesEqualityComparer : IEqualityComparer<BossMovementTypes>
    {
        // HLAutoGenerated 0x06000185: native compares the raw Int32 values.
        public bool Equals(BossMovementTypes a, BossMovementTypes b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000186: native returns the raw signed Int32.
        public int GetHashCode(BossMovementTypes a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000187: native delegates only to Object constructor.
        public BossMovementTypesEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class ButtonMappingTypeEqualityComparer : IEqualityComparer<ButtonMappingType>
    {
        // HLAutoGenerated 0x06000188: native compares the raw Int32 values.
        public bool Equals(ButtonMappingType a, ButtonMappingType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000189: native returns the raw signed Int32.
        public int GetHashCode(ButtonMappingType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600018a: native delegates only to Object constructor.
        public ButtonMappingTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class CameraConfigurationTypeEqualityComparer : IEqualityComparer<CameraConfigurationType>
    {
        // HLAutoGenerated 0x0600018b: native compares the raw Int32 values.
        public bool Equals(CameraConfigurationType a, CameraConfigurationType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600018c: native returns the raw signed Int32.
        public int GetHashCode(CameraConfigurationType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600018d: native delegates only to Object constructor.
        public CameraConfigurationTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class CameraRecenterHeadingTypeEqualityComparer : IEqualityComparer<CameraRecenterHeadingType>
    {
        // HLAutoGenerated 0x0600018e: native compares the raw Int32 values.
        public bool Equals(CameraRecenterHeadingType a, CameraRecenterHeadingType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600018f: native returns the raw signed Int32.
        public int GetHashCode(CameraRecenterHeadingType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000190: native delegates only to Object constructor.
        public CameraRecenterHeadingTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class CameraSensitivityTypeEqualityComparer : IEqualityComparer<CameraSensitivityType>
    {
        // HLAutoGenerated 0x06000191: native compares the raw Int32 values.
        public bool Equals(CameraSensitivityType a, CameraSensitivityType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000192: native returns the raw signed Int32.
        public int GetHashCode(CameraSensitivityType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000193: native delegates only to Object constructor.
        public CameraSensitivityTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class CameraSettingTypeEqualityComparer : IEqualityComparer<CameraSettingType>
    {
        // HLAutoGenerated 0x06000194: native compares the raw Int32 values.
        public bool Equals(CameraSettingType a, CameraSettingType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000195: native returns the raw signed Int32.
        public int GetHashCode(CameraSettingType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000196: native delegates only to Object constructor.
        public CameraSettingTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class CameraTypeEqualityComparer : IEqualityComparer<CameraType>
    {
        // HLAutoGenerated 0x06000197: native compares the raw Int32 values.
        public bool Equals(CameraType a, CameraType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000198: native returns the raw signed Int32.
        public int GetHashCode(CameraType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000199: native delegates only to Object constructor.
        public CameraTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class CameraYOverrideLayerEqualityComparer : IEqualityComparer<CameraYOverrideLayer>
    {
        // HLAutoGenerated 0x0600019a: native compares the raw Int32 values.
        public bool Equals(CameraYOverrideLayer a, CameraYOverrideLayer b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600019b: native returns the raw signed Int32.
        public int GetHashCode(CameraYOverrideLayer a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600019c: native delegates only to Object constructor.
        public CameraYOverrideLayerEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class CascadeObjectTypeEqualityComparer : IEqualityComparer<CascadeObjectType>
    {
        // HLAutoGenerated 0x0600019d: native compares the raw Int32 values.
        public bool Equals(CascadeObjectType a, CascadeObjectType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600019e: native returns the raw signed Int32.
        public int GetHashCode(CascadeObjectType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600019f: native delegates only to Object constructor.
        public CascadeObjectTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class CatchInputReleaseTypeEqualityComparer : IEqualityComparer<CatchInputReleaseType>
    {
        // HLAutoGenerated 0x060001a0: native compares the raw Int32 values.
        public bool Equals(CatchInputReleaseType a, CatchInputReleaseType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001a1: native returns the raw signed Int32.
        public int GetHashCode(CatchInputReleaseType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001a2: native delegates only to Object constructor.
        public CatchInputReleaseTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class CatchReleasePositionTypeEqualityComparer : IEqualityComparer<CatchReleasePositionType>
    {
        // HLAutoGenerated 0x060001a3: native compares the raw Int32 values.
        public bool Equals(CatchReleasePositionType a, CatchReleasePositionType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001a4: native returns the raw signed Int32.
        public int GetHashCode(CatchReleasePositionType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001a5: native delegates only to Object constructor.
        public CatchReleasePositionTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class CatchReleaseRotationTypeEqualityComparer : IEqualityComparer<CatchReleaseRotationType>
    {
        // HLAutoGenerated 0x060001a6: native compares the raw Int32 values.
        public bool Equals(CatchReleaseRotationType a, CatchReleaseRotationType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001a7: native returns the raw signed Int32.
        public int GetHashCode(CatchReleaseRotationType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001a8: native delegates only to Object constructor.
        public CatchReleaseRotationTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class ChallengesIsNewStateEqualityComparer : IEqualityComparer<ChallengesIsNewState>
    {
        // HLAutoGenerated 0x060001a9: native compares the raw Int32 values.
        public bool Equals(ChallengesIsNewState a, ChallengesIsNewState b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001aa: native returns the raw signed Int32.
        public int GetHashCode(ChallengesIsNewState a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001ab: native delegates only to Object constructor.
        public ChallengesIsNewStateEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class ChallengeZoneIdentifierEqualityComparer : IEqualityComparer<ChallengeZoneIdentifier>
    {
        // HLAutoGenerated 0x060001ac: native compares the raw Int32 values.
        public bool Equals(ChallengeZoneIdentifier a, ChallengeZoneIdentifier b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001ad: native returns the raw signed Int32.
        public int GetHashCode(ChallengeZoneIdentifier a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001ae: native delegates only to Object constructor.
        public ChallengeZoneIdentifierEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class ChallengeZoneMaterialTypeEqualityComparer : IEqualityComparer<ChallengeZoneMaterialType>
    {
        // HLAutoGenerated 0x060001af: native compares the raw Int32 values.
        public bool Equals(ChallengeZoneMaterialType a, ChallengeZoneMaterialType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001b0: native returns the raw signed Int32.
        public int GetHashCode(ChallengeZoneMaterialType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001b1: native delegates only to Object constructor.
        public ChallengeZoneMaterialTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class CharacterAbilityUITypeEqualityComparer : IEqualityComparer<CharacterAbilityUIType>
    {
        // HLAutoGenerated 0x060001b2: native compares the raw Int32 values.
        public bool Equals(CharacterAbilityUIType a, CharacterAbilityUIType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001b3: native returns the raw signed Int32.
        public int GetHashCode(CharacterAbilityUIType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001b4: native delegates only to Object constructor.
        public CharacterAbilityUITypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class CharacterArchetypeEqualityComparer : IEqualityComparer<CharacterArchetype>
    {
        // HLAutoGenerated 0x060001b5: native compares the raw Int32 values.
        public bool Equals(CharacterArchetype a, CharacterArchetype b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001b6: native returns the raw signed Int32.
        public int GetHashCode(CharacterArchetype a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001b7: native delegates only to Object constructor.
        public CharacterArchetypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class CharacterIdEqualityComparer : IEqualityComparer<CharacterId>
    {
        // HLAutoGenerated 0x060001b8: native compares the raw Int32 values.
        public bool Equals(CharacterId a, CharacterId b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001b9: native returns the raw signed Int32.
        public int GetHashCode(CharacterId a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001ba: native delegates only to Object constructor.
        public CharacterIdEqualityComparer()
        {
        }
    }

    public class CharacterStatsEqualityComparer : IEqualityComparer<CharacterStats>
    {
        // HLAutoGenerated 0x060001bb: native compares the raw Int32 values.
        public bool Equals(CharacterStats a, CharacterStats b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001bc: native returns the raw signed Int32.
        public int GetHashCode(CharacterStats a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001bd: native delegates only to Object constructor.
        public CharacterStatsEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class CharacterTrackingTypeEqualityComparer : IEqualityComparer<CharacterTrackingType>
    {
        // HLAutoGenerated 0x060001c0: native compares the raw Int32 values.
        public bool Equals(CharacterTrackingType a, CharacterTrackingType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001c1: native returns the raw signed Int32.
        public int GetHashCode(CharacterTrackingType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001c2: native delegates only to Object constructor.
        public CharacterTrackingTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class CollectableSourceEqualityComparer : IEqualityComparer<CollectableSource>
    {
        // HLAutoGenerated 0x060001c3: native compares the raw Int32 values.
        public bool Equals(CollectableSource a, CollectableSource b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001c4: native returns the raw signed Int32.
        public int GetHashCode(CollectableSource a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001c5: native delegates only to Object constructor.
        public CollectableSourceEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class CollectableTypeEqualityComparer : IEqualityComparer<CollectableType>
    {
        // HLAutoGenerated 0x060001c6: native compares the raw Int32 values.
        public bool Equals(CollectableType a, CollectableType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001c7: native returns the raw signed Int32.
        public int GetHashCode(CollectableType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001c8: native delegates only to Object constructor.
        public CollectableTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class CollectActionEqualityComparer : IEqualityComparer<CollectAction>
    {
        // HLAutoGenerated 0x060001c9: native compares the raw Int32 values.
        public bool Equals(CollectAction a, CollectAction b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001ca: native returns the raw signed Int32.
        public int GetHashCode(CollectAction a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001cb: native delegates only to Object constructor.
        public CollectActionEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class ComparisonTypeEqualityComparer : IEqualityComparer<ComparisonType>
    {
        // HLAutoGenerated 0x060001cc: native compares the raw Int32 values.
        public bool Equals(ComparisonType a, ComparisonType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001cd: native returns the raw signed Int32.
        public int GetHashCode(ComparisonType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001ce: native delegates only to Object constructor.
        public ComparisonTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class CutsceneTriggerTypeEqualityComparer : IEqualityComparer<CutsceneTriggerType>
    {
        // HLAutoGenerated 0x060001cf: native compares the raw Int32 values.
        public bool Equals(CutsceneTriggerType a, CutsceneTriggerType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001d0: native returns the raw signed Int32.
        public int GetHashCode(CutsceneTriggerType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001d1: native delegates only to Object constructor.
        public CutsceneTriggerTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class DamageActionEqualityComparer : IEqualityComparer<DamageAction>
    {
        // HLAutoGenerated 0x060001d2: native compares the raw Int32 values.
        public bool Equals(DamageAction a, DamageAction b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001d3: native returns the raw signed Int32.
        public int GetHashCode(DamageAction a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001d4: native delegates only to Object constructor.
        public DamageActionEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class DirectionModifierTypeEqualityComparer : IEqualityComparer<DirectionModifierType>
    {
        // HLAutoGenerated 0x060001d5: native compares the raw Int32 values.
        public bool Equals(DirectionModifierType a, DirectionModifierType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001d6: native returns the raw signed Int32.
        public int GetHashCode(DirectionModifierType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001d7: native delegates only to Object constructor.
        public DirectionModifierTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class DreamPowerStoreBandTypeEqualityComparer : IEqualityComparer<DreamPowerStoreBandType>
    {
        // HLAutoGenerated 0x060001d8: native compares the raw Int32 values.
        public bool Equals(DreamPowerStoreBandType a, DreamPowerStoreBandType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001d9: native returns the raw signed Int32.
        public int GetHashCode(DreamPowerStoreBandType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001da: native delegates only to Object constructor.
        public DreamPowerStoreBandTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class DreamPowerStoreIsNewStateEqualityComparer : IEqualityComparer<DreamPowerStoreIsNewState>
    {
        // HLAutoGenerated 0x060001db: native compares the raw Int32 values.
        public bool Equals(DreamPowerStoreIsNewState a, DreamPowerStoreIsNewState b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001dc: native returns the raw signed Int32.
        public int GetHashCode(DreamPowerStoreIsNewState a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001dd: native delegates only to Object constructor.
        public DreamPowerStoreIsNewStateEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class EnemyTypeEqualityComparer : IEqualityComparer<EnemyType>
    {
        // HLAutoGenerated 0x060001de: native compares the raw Int32 values.
        public bool Equals(EnemyType a, EnemyType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001df: native returns the raw signed Int32.
        public int GetHashCode(EnemyType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001e0: native delegates only to Object constructor.
        public EnemyTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class EntityActivationLogicTypeEqualityComparer : IEqualityComparer<EntityActivationLogicType>
    {
        // HLAutoGenerated 0x060001e1: native compares the raw Int32 values.
        public bool Equals(EntityActivationLogicType a, EntityActivationLogicType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001e2: native returns the raw signed Int32.
        public int GetHashCode(EntityActivationLogicType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001e3: native delegates only to Object constructor.
        public EntityActivationLogicTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class EntityActivationTypeEqualityComparer : IEqualityComparer<EntityActivationType>
    {
        // HLAutoGenerated 0x060001e4: native compares the raw Int32 values.
        public bool Equals(EntityActivationType a, EntityActivationType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001e5: native returns the raw signed Int32.
        public int GetHashCode(EntityActivationType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001e6: native delegates only to Object constructor.
        public EntityActivationTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class FadeTransitionTypeEqualityComparer : IEqualityComparer<FadeTransitionType>
    {
        // HLAutoGenerated 0x060001e7: native compares the raw Int32 values.
        public bool Equals(FadeTransitionType a, FadeTransitionType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001e8: native returns the raw signed Int32.
        public int GetHashCode(FadeTransitionType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001e9: native delegates only to Object constructor.
        public FadeTransitionTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class FullscreenShaderParametersTypeEqualityComparer : IEqualityComparer<FullscreenShaderParametersType>
    {
        // HLAutoGenerated 0x060001ea: native compares the raw Int32 values.
        public bool Equals(FullscreenShaderParametersType a, FullscreenShaderParametersType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001eb: native returns the raw signed Int32.
        public int GetHashCode(FullscreenShaderParametersType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001ec: native delegates only to Object constructor.
        public FullscreenShaderParametersTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class GameActionEqualityComparer : IEqualityComparer<GameAction>
    {
        // HLAutoGenerated 0x060001ed: native compares the raw Int32 values.
        public bool Equals(GameAction a, GameAction b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001ee: native returns the raw signed Int32.
        public int GetHashCode(GameAction a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001ef: native delegates only to Object constructor.
        public GameActionEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class GameplayModifierTypeEqualityComparer : IEqualityComparer<GameplayModifierType>
    {
        // HLAutoGenerated 0x060001f0: native compares the raw Int32 values.
        public bool Equals(GameplayModifierType a, GameplayModifierType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001f1: native returns the raw signed Int32.
        public int GetHashCode(GameplayModifierType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001f2: native delegates only to Object constructor.
        public GameplayModifierTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class GlobalConstantTypeEqualityComparer : IEqualityComparer<GlobalConstantType>
    {
        // HLAutoGenerated 0x060001f3: native compares the raw Int32 values.
        public bool Equals(GlobalConstantType a, GlobalConstantType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001f4: native returns the raw signed Int32.
        public int GetHashCode(GlobalConstantType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001f5: native delegates only to Object constructor.
        public GlobalConstantTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class GravitySurfaceTypeEqualityComparer : IEqualityComparer<GravitySurfaceType>
    {
        // HLAutoGenerated 0x060001f6: native compares the raw Int32 values.
        public bool Equals(GravitySurfaceType a, GravitySurfaceType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001f7: native returns the raw signed Int32.
        public int GetHashCode(GravitySurfaceType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001f8: native delegates only to Object constructor.
        public GravitySurfaceTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class HalfPipeTypeEqualityComparer : IEqualityComparer<HalfPipeType>
    {
        // HLAutoGenerated 0x060001f9: native compares the raw Int32 values.
        public bool Equals(HalfPipeType a, HalfPipeType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001fa: native returns the raw signed Int32.
        public int GetHashCode(HalfPipeType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001fb: native delegates only to Object constructor.
        public HalfPipeTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class HazardTypeEqualityComparer : IEqualityComparer<HazardType>
    {
        // HLAutoGenerated 0x060001fc: native compares the raw Int32 values.
        public bool Equals(HazardType a, HazardType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x060001fd: native returns the raw signed Int32.
        public int GetHashCode(HazardType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x060001fe: native delegates only to Object constructor.
        public HazardTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class HLAudioClipIdentifierEqualityComparer : IEqualityComparer<HLAudioClipIdentifier>
    {
        // HLAutoGenerated 0x060001ff: native compares the raw Int32 values.
        public bool Equals(HLAudioClipIdentifier a, HLAudioClipIdentifier b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000200: native returns the raw signed Int32.
        public int GetHashCode(HLAudioClipIdentifier a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000201: native delegates only to Object constructor.
        public HLAudioClipIdentifierEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class HLAudioMixerGroupIdentifierEqualityComparer : IEqualityComparer<HLAudioMixerGroupIdentifier>
    {
        // HLAutoGenerated 0x06000202: native compares the raw Int32 values.
        public bool Equals(HLAudioMixerGroupIdentifier a, HLAudioMixerGroupIdentifier b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000203: native returns the raw signed Int32.
        public int GetHashCode(HLAudioMixerGroupIdentifier a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000204: native delegates only to Object constructor.
        public HLAudioMixerGroupIdentifierEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class HLAudioMixerIdentifierEqualityComparer : IEqualityComparer<HLAudioMixerIdentifier>
    {
        // HLAutoGenerated 0x06000205: native compares the raw Int32 values.
        public bool Equals(HLAudioMixerIdentifier a, HLAudioMixerIdentifier b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000206: native returns the raw signed Int32.
        public int GetHashCode(HLAudioMixerIdentifier a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000207: native delegates only to Object constructor.
        public HLAudioMixerIdentifierEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class HLAudioSourceIdentifierEqualityComparer : IEqualityComparer<HLAudioSourceIdentifier>
    {
        // HLAutoGenerated 0x06000208: native compares the raw Int32 values.
        public bool Equals(HLAudioSourceIdentifier a, HLAudioSourceIdentifier b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000209: native returns the raw signed Int32.
        public int GetHashCode(HLAudioSourceIdentifier a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600020a: native delegates only to Object constructor.
        public HLAudioSourceIdentifierEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class HLAudioSourceTransitionEqualityComparer : IEqualityComparer<HLAudioSourceTransition>
    {
        // HLAutoGenerated 0x0600020b: native compares the raw Int32 values.
        public bool Equals(HLAudioSourceTransition a, HLAudioSourceTransition b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600020c: native returns the raw signed Int32.
        public int GetHashCode(HLAudioSourceTransition a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600020d: native delegates only to Object constructor.
        public HLAudioSourceTransitionEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class HLCutsceneIdentifierEqualityComparer : IEqualityComparer<HLCutsceneIdentifier>
    {
        // HLAutoGenerated 0x0600020e: native compares the raw Int32 values.
        public bool Equals(HLCutsceneIdentifier a, HLCutsceneIdentifier b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600020f: native returns the raw signed Int32.
        public int GetHashCode(HLCutsceneIdentifier a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000210: native delegates only to Object constructor.
        public HLCutsceneIdentifierEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class HomingTargetTypeEqualityComparer : IEqualityComparer<HomingTargetType>
    {
        // HLAutoGenerated 0x06000211: native compares the raw Int32 values.
        public bool Equals(HomingTargetType a, HomingTargetType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000212: native returns the raw signed Int32.
        public int GetHashCode(HomingTargetType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000213: native delegates only to Object constructor.
        public HomingTargetTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class InputModifierTypeEqualityComparer : IEqualityComparer<InputModifierType>
    {
        // HLAutoGenerated 0x06000214: native compares the raw Int32 values.
        public bool Equals(InputModifierType a, InputModifierType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000215: native returns the raw signed Int32.
        public int GetHashCode(InputModifierType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000216: native delegates only to Object constructor.
        public InputModifierTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class IntroSequenceIdentifierEqualityComparer : IEqualityComparer<IntroSequenceIdentifier>
    {
        // HLAutoGenerated 0x06000217: native compares the raw Int32 values.
        public bool Equals(IntroSequenceIdentifier a, IntroSequenceIdentifier b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000218: native returns the raw signed Int32.
        public int GetHashCode(IntroSequenceIdentifier a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000219: native delegates only to Object constructor.
        public IntroSequenceIdentifierEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class LeaderboardIdentifierEqualityComparer : IEqualityComparer<LeaderboardIdentifier>
    {
        // HLAutoGenerated 0x0600021a: native compares the raw Int32 values.
        public bool Equals(LeaderboardIdentifier a, LeaderboardIdentifier b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600021b: native returns the raw signed Int32.
        public int GetHashCode(LeaderboardIdentifier a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600021c: native delegates only to Object constructor.
        public LeaderboardIdentifierEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class LevelRendererIdentifierEqualityComparer : IEqualityComparer<LevelRendererIdentifier>
    {
        // HLAutoGenerated 0x0600021d: native compares the raw Int32 values.
        public bool Equals(LevelRendererIdentifier a, LevelRendererIdentifier b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600021e: native returns the raw signed Int32.
        public int GetHashCode(LevelRendererIdentifier a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600021f: native delegates only to Object constructor.
        public LevelRendererIdentifierEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class LevelSetupTypesEqualityComparer : IEqualityComparer<LevelSetupTypes>
    {
        // HLAutoGenerated 0x06000220: native compares the raw Int32 values.
        public bool Equals(LevelSetupTypes a, LevelSetupTypes b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000221: native returns the raw signed Int32.
        public int GetHashCode(LevelSetupTypes a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000222: native delegates only to Object constructor.
        public LevelSetupTypesEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class LightspeedDashTypeEqualityComparer : IEqualityComparer<LightspeedDashType>
    {
        // HLAutoGenerated 0x06000223: native compares the raw Int32 values.
        public bool Equals(LightspeedDashType a, LightspeedDashType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000224: native returns the raw signed Int32.
        public int GetHashCode(LightspeedDashType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000225: native delegates only to Object constructor.
        public LightspeedDashTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class MacDeviceGenerationEqualityComparer : IEqualityComparer<MacDeviceGeneration>
    {
        // HLAutoGenerated 0x06000226: native compares the raw Int32 values.
        public bool Equals(MacDeviceGeneration a, MacDeviceGeneration b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000227: native returns the raw signed Int32.
        public int GetHashCode(MacDeviceGeneration a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000228: native delegates only to Object constructor.
        public MacDeviceGenerationEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class MaterialManipulationTriggerTypeEqualityComparer : IEqualityComparer<MaterialManipulationTriggerType>
    {
        // HLAutoGenerated 0x06000229: native compares the raw Int32 values.
        public bool Equals(MaterialManipulationTriggerType a, MaterialManipulationTriggerType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600022a: native returns the raw signed Int32.
        public int GetHashCode(MaterialManipulationTriggerType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600022b: native delegates only to Object constructor.
        public MaterialManipulationTriggerTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class MissionIsNewStateEqualityComparer : IEqualityComparer<MissionIsNewState>
    {
        // HLAutoGenerated 0x0600022c: native compares the raw Int32 values.
        public bool Equals(MissionIsNewState a, MissionIsNewState b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600022d: native returns the raw signed Int32.
        public int GetHashCode(MissionIsNewState a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600022e: native delegates only to Object constructor.
        public MissionIsNewStateEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class MissionScorerObjectiveTypeEqualityComparer : IEqualityComparer<MissionScorerObjectiveType>
    {
        // HLAutoGenerated 0x0600022f: native compares the raw Int32 values.
        public bool Equals(MissionScorerObjectiveType a, MissionScorerObjectiveType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000230: native returns the raw signed Int32.
        public int GetHashCode(MissionScorerObjectiveType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000231: native delegates only to Object constructor.
        public MissionScorerObjectiveTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class MissionScorerStreakIdentifierEqualityComparer : IEqualityComparer<MissionScorerStreakIdentifier>
    {
        // HLAutoGenerated 0x06000232: native compares the raw Int32 values.
        public bool Equals(MissionScorerStreakIdentifier a, MissionScorerStreakIdentifier b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000233: native returns the raw signed Int32.
        public int GetHashCode(MissionScorerStreakIdentifier a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000234: native delegates only to Object constructor.
        public MissionScorerStreakIdentifierEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class MissionTypeEqualityComparer : IEqualityComparer<MissionType>
    {
        // HLAutoGenerated 0x06000235: native compares the raw Int32 values.
        public bool Equals(MissionType a, MissionType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000236: native returns the raw signed Int32.
        public int GetHashCode(MissionType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000237: native delegates only to Object constructor.
        public MissionTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class MusicStoppedReasonEqualityComparer : IEqualityComparer<MusicStoppedReason>
    {
        // HLAutoGenerated 0x06000238: native compares the raw Int32 values.
        public bool Equals(MusicStoppedReason a, MusicStoppedReason b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000239: native returns the raw signed Int32.
        public int GetHashCode(MusicStoppedReason a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600023a: native delegates only to Object constructor.
        public MusicStoppedReasonEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class NotificationTimerTypeEqualityComparer : IEqualityComparer<NotificationTimerType>
    {
        // HLAutoGenerated 0x0600023b: native compares the raw Int32 values.
        public bool Equals(NotificationTimerType a, NotificationTimerType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600023c: native returns the raw signed Int32.
        public int GetHashCode(NotificationTimerType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600023d: native delegates only to Object constructor.
        public NotificationTimerTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class NotificationTypeEqualityComparer : IEqualityComparer<NotificationType>
    {
        // HLAutoGenerated 0x0600023e: native compares the raw Int32 values.
        public bool Equals(NotificationType a, NotificationType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600023f: native returns the raw signed Int32.
        public int GetHashCode(NotificationType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000240: native delegates only to Object constructor.
        public NotificationTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class OrnamentCategoryEqualityComparer : IEqualityComparer<OrnamentCategory>
    {
        // HLAutoGenerated 0x06000241: native compares the raw Int32 values.
        public bool Equals(OrnamentCategory a, OrnamentCategory b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000242: native returns the raw signed Int32.
        public int GetHashCode(OrnamentCategory a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000243: native delegates only to Object constructor.
        public OrnamentCategoryEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class OrnamentIdentifierEqualityComparer : IEqualityComparer<OrnamentIdentifier>
    {
        // HLAutoGenerated 0x06000244: native compares the raw Int32 values.
        public bool Equals(OrnamentIdentifier a, OrnamentIdentifier b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000245: native returns the raw signed Int32.
        public int GetHashCode(OrnamentIdentifier a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000246: native delegates only to Object constructor.
        public OrnamentIdentifierEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class OutroSequenceIdentifierEqualityComparer : IEqualityComparer<OutroSequenceIdentifier>
    {
        // HLAutoGenerated 0x06000247: native compares the raw Int32 values.
        public bool Equals(OutroSequenceIdentifier a, OutroSequenceIdentifier b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000248: native returns the raw signed Int32.
        public int GetHashCode(OutroSequenceIdentifier a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000249: native delegates only to Object constructor.
        public OutroSequenceIdentifierEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class ParticleEffectTypeEqualityComparer : IEqualityComparer<ParticleEffectType>
    {
        // HLAutoGenerated 0x0600024a: native compares the raw Int32 values.
        public bool Equals(ParticleEffectType a, ParticleEffectType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600024b: native returns the raw signed Int32.
        public int GetHashCode(ParticleEffectType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600024c: native delegates only to Object constructor.
        public ParticleEffectTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class PersistentObjectIdentifierTypeEqualityComparer : IEqualityComparer<PersistentObjectIdentifierType>
    {
        // HLAutoGenerated 0x0600024d: native compares the raw Int32 values.
        public bool Equals(PersistentObjectIdentifierType a, PersistentObjectIdentifierType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600024e: native returns the raw signed Int32.
        public int GetHashCode(PersistentObjectIdentifierType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600024f: native delegates only to Object constructor.
        public PersistentObjectIdentifierTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class PlatformAssetTypesEqualityComparer : IEqualityComparer<PlatformAssetTypes>
    {
        // HLAutoGenerated 0x06000250: native compares the raw Int32 values.
        public bool Equals(PlatformAssetTypes a, PlatformAssetTypes b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000251: native returns the raw signed Int32.
        public int GetHashCode(PlatformAssetTypes a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000252: native delegates only to Object constructor.
        public PlatformAssetTypesEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class PlatformComponentTypesEqualityComparer : IEqualityComparer<PlatformComponentTypes>
    {
        // HLAutoGenerated 0x06000253: native compares the raw Int32 values.
        public bool Equals(PlatformComponentTypes a, PlatformComponentTypes b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000254: native returns the raw signed Int32.
        public int GetHashCode(PlatformComponentTypes a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000255: native delegates only to Object constructor.
        public PlatformComponentTypesEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class PlayerProgressionTypesEqualityComparer : IEqualityComparer<PlayerProgressionTypes>
    {
        // HLAutoGenerated 0x06000256: native compares the raw Int32 values.
        public bool Equals(PlayerProgressionTypes a, PlayerProgressionTypes b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000257: native returns the raw signed Int32.
        public int GetHashCode(PlayerProgressionTypes a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000258: native delegates only to Object constructor.
        public PlayerProgressionTypesEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class ProjectileTypeEqualityComparer : IEqualityComparer<ProjectileType>
    {
        // HLAutoGenerated 0x06000259: native compares the raw Int32 values.
        public bool Equals(ProjectileType a, ProjectileType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600025a: native returns the raw signed Int32.
        public int GetHashCode(ProjectileType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600025b: native delegates only to Object constructor.
        public ProjectileTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class PromptSlotTypeEqualityComparer : IEqualityComparer<PromptSlotType>
    {
        // HLAutoGenerated 0x0600025c: native compares the raw Int32 values.
        public bool Equals(PromptSlotType a, PromptSlotType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600025d: native returns the raw signed Int32.
        public int GetHashCode(PromptSlotType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600025e: native delegates only to Object constructor.
        public PromptSlotTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class RailTypeEqualityComparer : IEqualityComparer<RailType>
    {
        // HLAutoGenerated 0x0600025f: native compares the raw Int32 values.
        public bool Equals(RailType a, RailType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000260: native returns the raw signed Int32.
        public int GetHashCode(RailType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000261: native delegates only to Object constructor.
        public RailTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class RankTypeEqualityComparer : IEqualityComparer<RankType>
    {
        // HLAutoGenerated 0x06000262: native compares the raw Int32 values.
        public bool Equals(RankType a, RankType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000263: native returns the raw signed Int32.
        public int GetHashCode(RankType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000264: native delegates only to Object constructor.
        public RankTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class ReplayModeEqualityComparer : IEqualityComparer<ReplayMode>
    {
        // HLAutoGenerated 0x06000265: native compares the raw Int32 values.
        public bool Equals(ReplayMode a, ReplayMode b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000266: native returns the raw signed Int32.
        public int GetHashCode(ReplayMode a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000267: native delegates only to Object constructor.
        public ReplayModeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class RewardTrackTypeEqualityComparer : IEqualityComparer<RewardTrackType>
    {
        // HLAutoGenerated 0x06000268: native compares the raw Int32 values.
        public bool Equals(RewardTrackType a, RewardTrackType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000269: native returns the raw signed Int32.
        public int GetHashCode(RewardTrackType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600026a: native delegates only to Object constructor.
        public RewardTrackTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class ScreenControlsGroupEqualityComparer : IEqualityComparer<ScreenControlsGroup>
    {
        // HLAutoGenerated 0x0600026b: native compares the raw Int32 values.
        public bool Equals(ScreenControlsGroup a, ScreenControlsGroup b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600026c: native returns the raw signed Int32.
        public int GetHashCode(ScreenControlsGroup a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600026d: native delegates only to Object constructor.
        public ScreenControlsGroupEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class SurfaceCrossSectionTypeEqualityComparer : IEqualityComparer<SurfaceCrossSectionType>
    {
        // HLAutoGenerated 0x0600026e: native compares the raw Int32 values.
        public bool Equals(SurfaceCrossSectionType a, SurfaceCrossSectionType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600026f: native returns the raw signed Int32.
        public int GetHashCode(SurfaceCrossSectionType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000270: native delegates only to Object constructor.
        public SurfaceCrossSectionTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class SurfacePathTypeEqualityComparer : IEqualityComparer<SurfacePathType>
    {
        // HLAutoGenerated 0x06000271: native compares the raw Int32 values.
        public bool Equals(SurfacePathType a, SurfacePathType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000272: native returns the raw signed Int32.
        public int GetHashCode(SurfacePathType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000273: native delegates only to Object constructor.
        public SurfacePathTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class TerrainEffectTypeEqualityComparer : IEqualityComparer<TerrainEffectType>
    {
        // HLAutoGenerated 0x06000274: native compares the raw Int32 values.
        public bool Equals(TerrainEffectType a, TerrainEffectType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000275: native returns the raw signed Int32.
        public int GetHashCode(TerrainEffectType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000276: native delegates only to Object constructor.
        public TerrainEffectTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class TerrainMetadataTypeEqualityComparer : IEqualityComparer<TerrainMetadataType>
    {
        // HLAutoGenerated 0x06000277: native compares the raw Int32 values.
        public bool Equals(TerrainMetadataType a, TerrainMetadataType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000278: native returns the raw signed Int32.
        public int GetHashCode(TerrainMetadataType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000279: native delegates only to Object constructor.
        public TerrainMetadataTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class TerrainTrackerTypeEqualityComparer : IEqualityComparer<TerrainTrackerType>
    {
        // HLAutoGenerated 0x0600027a: native compares the raw Int32 values.
        public bool Equals(TerrainTrackerType a, TerrainTrackerType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600027b: native returns the raw signed Int32.
        public int GetHashCode(TerrainTrackerType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600027c: native delegates only to Object constructor.
        public TerrainTrackerTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class TimeCategoryEqualityComparer : IEqualityComparer<TimeCategory>
    {
        // HLAutoGenerated 0x0600027d: native compares the raw Int32 values.
        public bool Equals(TimeCategory a, TimeCategory b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600027e: native returns the raw signed Int32.
        public int GetHashCode(TimeCategory a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600027f: native delegates only to Object constructor.
        public TimeCategoryEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class TransporterTypeEqualityComparer : IEqualityComparer<TransporterType>
    {
        // HLAutoGenerated 0x06000280: native compares the raw Int32 values.
        public bool Equals(TransporterType a, TransporterType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000281: native returns the raw signed Int32.
        public int GetHashCode(TransporterType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000282: native delegates only to Object constructor.
        public TransporterTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class UIShowTypeEqualityComparer : IEqualityComparer<UIShowType>
    {
        // HLAutoGenerated 0x06000283: native compares the raw Int32 values.
        public bool Equals(UIShowType a, UIShowType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000284: native returns the raw signed Int32.
        public int GetHashCode(UIShowType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000285: native delegates only to Object constructor.
        public UIShowTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class UIWidgetButtonChallengeRewardSizeEqualityComparer : IEqualityComparer<UIWidgetButtonChallengeRewardSize>
    {
        // HLAutoGenerated 0x06000286: native compares the raw Int32 values.
        public bool Equals(UIWidgetButtonChallengeRewardSize a, UIWidgetButtonChallengeRewardSize b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000287: native returns the raw signed Int32.
        public int GetHashCode(UIWidgetButtonChallengeRewardSize a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000288: native delegates only to Object constructor.
        public UIWidgetButtonChallengeRewardSizeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public class ValidationErrorSeverityEqualityComparer : IEqualityComparer<ValidationErrorSeverity>
    {
        // HLAutoGenerated 0x06000289: native compares the raw Int32 values.
        public bool Equals(ValidationErrorSeverity a, ValidationErrorSeverity b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600028a: native returns the raw signed Int32.
        public int GetHashCode(ValidationErrorSeverity a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600028b: native delegates only to Object constructor.
        public ValidationErrorSeverityEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class ValidationErrorTypesEqualityComparer : IEqualityComparer<ValidationErrorTypes>
    {
        // HLAutoGenerated 0x0600028c: native compares the raw Int32 values.
        public bool Equals(ValidationErrorTypes a, ValidationErrorTypes b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x0600028d: native returns the raw signed Int32.
        public int GetHashCode(ValidationErrorTypes a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600028e: native delegates only to Object constructor.
        public ValidationErrorTypesEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class ValidationObjectTypesEqualityComparer : IEqualityComparer<ValidationObjectTypes>
    {
        // HLAutoGenerated 0x0600028f: native compares the raw Int32 values.
        public bool Equals(ValidationObjectTypes a, ValidationObjectTypes b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000290: native returns the raw signed Int32.
        public int GetHashCode(ValidationObjectTypes a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000291: native delegates only to Object constructor.
        public ValidationObjectTypesEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class ValueTypeEqualityComparer : IEqualityComparer<ValueType>
    {
        // HLAutoGenerated 0x06000292: native compares the raw Int32 values.
        public bool Equals(ValueType a, ValueType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000293: native returns the raw signed Int32.
        public int GetHashCode(ValueType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000294: native delegates only to Object constructor.
        public ValueTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class WaypointContainerTypeEqualityComparer : IEqualityComparer<WaypointContainerType>
    {
        // HLAutoGenerated 0x06000295: native compares the raw Int32 values.
        public bool Equals(WaypointContainerType a, WaypointContainerType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000296: native returns the raw signed Int32.
        public int GetHashCode(WaypointContainerType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x06000297: native delegates only to Object constructor.
        public WaypointContainerTypeEqualityComparer()
        {
        }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class WaypointTypeEqualityComparer : IEqualityComparer<WaypointType>
    {
        // HLAutoGenerated 0x06000298: native compares the raw Int32 values.
        public bool Equals(WaypointType a, WaypointType b)
        {
            return a == b;
        }

        // HLAutoGenerated 0x06000299: native returns the raw signed Int32.
        public int GetHashCode(WaypointType a)
        {
            return (int)a;
        }

        // HLAutoGenerated 0x0600029a: native delegates only to Object constructor.
        public WaypointTypeEqualityComparer()
        {
        }
    }
}
