namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000a1; serialized Int32 literals.
    public enum FadeTransitionType
    {
        Black = -2127657113,
        White = 1248129259
    }
}
