namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000a3; serialized Int32 literals.
    public enum FullscreenShaderParametersType
    {
        BoostEnter = 2055737483,
        BoostExit = 1866313973,
        ChaosControlEnter = 1301315605,
        ChaosControlExit = -1349067234,
        ChaosShift = 1168193895,
        ChaosShiftAim = -1169953358,
        DashPadEnter = 1014357974,
        Default = 602145082,
        DreamCollisionTriggerEnter = 1654154562,
        DreamCollisionTriggerExit = -938537438,
        PostRespawn = 1399051934,
        Respawn = 674544010,
        TakeDamage = 1465192659
    }
}
