namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000a5; serialized Int32 literals.
    public enum GameAction
    {
        None = 0,
        CharacterAirActivate = -867581389,
        CharacterAirCancel = 1889499408,
        CharacterAirStompAttack = -1985919783,
        CharacterBoost = 141215273,
        CharacterBurstAttack = 2005397571,
        CharacterHomingAttack = 916659036,
        CharacterHomingAttackOneShot = -998821882,
        CharacterJump = 2025929064,
        CharacterLightspeedDash = -952628489,
        CharacterMovementDown = 2071926807,
        CharacterMovementHorizontal = 1124087787,
        CharacterMovementLeft = 501706564,
        CharacterMovementRight = 1863931450,
        CharacterMovementUp = -1936968251,
        CharacterMovementVertical = 1378906170,
        CharacterRailTarget = 984712371,
        CharacterRoll = -238613072,
        CharacterSpinDashCharge = -440339759
    }
}
