namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000a7; serialized Int32 literals.
    public enum GameplayModifierType
    {
        ApplyGravity = 1690142046,
        AutoRail = 221673637,
        ControlsEnabled = -1037175699,
        FormLocked = 399335950,
        FreeLookHeadingOverride = 1691736251,
        GravityMultiplier = -487776313,
        GripReset = 149996441,
        HoverData = 1801486397,
        Invulnerable = 1553824060,
        MaxVelocityFromInfluence = -873258961,
        StickyControlsAvailable = -1977363446,
        SwitchAvailable = 904429376,
        TargetingAvailable = -1652673035
    }
}
