namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000a9; serialized Int32 literals.
    public enum GlobalConstantType
    {
        Character = 675762468,
        Input = -796717160,
        Mission = 1356723161
    }
}
