namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000af; serialized Int32 literals.
    public enum HazardType
    {
        Bomb = 1231383388,
        BossCrabClawWave = -1968462880,
        BossDamageDealer = 775910867,
        BossFourmanLaserFence = -1914317872,
        BossInvulnerableArea = -230631363,
        BossVulnerableArea = -2106633563,
        DeathPlane = 1044572640,
        Enemy = -214669338,
        GuardianProjectile = 1122792832,
        GuardianProjectileReturnable = 2130078912,
        Laser = -504915581,
        Projectile = -929324883,
        SpikeTrap = -1974585981
    }
}
