namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000b7; serialized Int32 literals.
    public enum HLAudioSourceIdentifier
    {
        None = 0,
        Ambient = -2085887187,
        Background = 1208506000,
        BackgroundOneShot1 = -2053821571,
        BackgroundOneShot2 = 480017095,
        BackgroundOneShot3 = 1805339217,
        BackgroundOneShot4 = -167780366,
        BackgroundOneShot5 = -2097615004,
        Jukebox = 1007517959,
        Sfx = -1378384063,
        Ui = 1995095333,
        UiBackground = -645205249
    }
}
