namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000b3; serialized Int32 literals.
    public enum HLAudioMixerGroupIdentifier
    {
        Ambient = -2085887187,
        Boss = -141265807,
        Character = 675762468,
        Master = 571382703,
        Music = -973529339,
        MusicMaster = -1304143467,
        Pickups = 419028598,
        SFXMaster = -1043185749,
        SFXSlowDown = 136020838,
        UI = 1995095333,
        VO = -1264301101,
        VOInGame = 1085891055,
        VOIntroOutroBoss = -1210535939,
        VOReverie = 1349536068,
        VOZ4 = 721156875
    }
}
