namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000bd; serialized Int32 literals.
    public enum HomingTargetType
    {
        Boss = -141265807,
        CatchRelease = 1172797550,
        CatchReleaseTightrope = 1645303179,
        CatchReleaseTrampoline = 657193873,
        ChaosDashSwitch = -1629712951,
        Enemy = -214669338,
        HomingSwitch = 2112396014,
        LightspeedDash = -1861442283,
        Rail = -1875445302,
        Ring = 1186391869,
        SpeedRing = 2077728114,
        Spring = 1681468432,
        SpringWide = -1641578838,
        Transporter = -758476861
    }
}
