namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000bf; serialized Int32 values.
    public enum InputModifierType
    {
        High = 946861598,
        Low = -70203948,
        Medium = -915112498
    }
}
