namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000c1; serialized Int32 literals.
    public enum IntroSequenceIdentifier
    {
        IntroRail = 1428356155,
        WalkThroughGate = -903991510
    }
}
