namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000c3; serialized Int32 literals.
    public enum LeaderboardIdentifier
    {
        None = 0,
        TailsChallenge_HourlyQA = -1689533555,
        TailsChallenges_Daily = 267051890,
        TailsChallenges_Weekly = -1537373569,
        TimeTrials_B1AXMX = 1137205418,
        TimeTrials_B1AXMX_QA = -516518578,
        TimeTrials_Z1A1M5 = -666366698,
        TimeTrials_Z1A1M5_QA = 278469739,
        TimeTrials_Z1A2M5 = -636570801,
        TimeTrials_Z1A2M5_QA = -1777504571,
        TimeTrials_Z1A3M3 = 850361421,
        TimeTrials_Z1A3M3_QA = 2017125052,
        TimeTrials_Z2A1M5 = -1612154938,
        TimeTrials_Z2A1M5_QA = -1642718328,
        TimeTrials_Z2A2M4 = -357959415,
        TimeTrials_Z2A2M4_QA = -1606545853,
        TimeTrials_Z2A3M4 = -345271490,
        TimeTrials_Z2A3M4_QA = 1801641446,
        TimeTrials_Z3A1M5 = -1568121226,
        TimeTrials_Z3A1M5_QA = 1388059414,
        TimeTrials_Z3A2M5 = -1597054929,
        TimeTrials_Z3A2M5_QA = -735549000,
        TimeTrials_Z3A3M5 = -1593013736,
        TimeTrials_Z3A3M5_QA = 527743517,
        TimeTrials_Z4A1M5 = 279478886,
        TimeTrials_Z4A1M5_QA = 1484329487,
        TimeTrials_Z4A2M5 = 317602879,
        TimeTrials_Z4A2M5_QA = -554868575,
        TimeTrials_Z4A3M5 = 321672712,
        TimeTrials_Z4A3M5_QA = 363967236
    }
}
