namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000c7; serialized Int32 literals.
    public enum LevelSetupTypes
    {
        BonusZone1 = 1475437797,
        Hub = 556364600,
        Standard = 691778612,
        Zone1 = 786271315,
        Zone1Boss = -252141401,
        Zone2 = -1210786327,
        Zone2Boss = -1218913673,
        Zone3 = -1059852929,
        Zone3Boss = -1975979065,
        Zone4 = 1589082332,
        Zone4Boss = 941109207
    }
}
