namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000c5; serialized Int32 literals.
    public enum LevelRendererIdentifier
    {
        Character = 675762468,
        CharacterAccessory01 = -626053635,
        CharacterAccessory02 = 1134984263,
        CharacterAccessory03 = 882986193,
        CharacterCheese = 86499681,
        DreamGateExit02Pfx = -1121666482,
        DreamGateExitPfx = 1281158565,
        DreamMoon = 199370574,
        DreamMoonInnerMoon = -1468863052,
        DreamMoonOuterGold = -1655562118,
        DreamMoonOuterRim = -1142480054,
        DreamOrb = -1147032754,
        DreamOrbPfx = 956910040,
        zone4_interactable_vanishingplatform = 174175861
    }
}
