namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000cb; serialized Int32 literals.
    public enum MacDeviceGeneration
    {
        Future = -940832271,
        High = 946861598,
        Low = -70203948,
        Medium = -915112498,
        Ultra = -99653792,
        VeryLow = 1924880489
    }
}
