namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000cd; serialized Int32 literals.
    public enum MaterialManipulationTriggerType
    {
        Boss4PunchFloor = -1636316954
    }
}
