namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000d3; serialized Int32 literals.
    public enum MissionScorerStreakIdentifier
    {
        CollectableMinor = 570394467,
        DamageableObject = -281178690,
        EnemyAir = 1944159831,
        EnemyGround = -989784848,
        LightSpeedDash = -1861442283
    }
}
