namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000d1; serialized Int32 literals.
    public enum MissionScorerObjectiveType
    {
        CrateLarge_Zone1 = -1584068226,
        CrateLarge_Zone2 = 949770436,
        CrateLarge_Zone3 = 1335584850,
        CrateLarge_Zone4 = -771752463,
        CrateLarge_Zone5 = -1493643929,
        Crate_Zone1 = -2107774531,
        Crate_Zone2 = 458536967,
        Crate_Zone3 = 1817413777,
        Crate_Zone4 = -231269070,
        Crate_Zone5 = -2060440156,
        Enemy_BuzzBomber_Patrol = 692777349,
        Enemy_BuzzBomber_Static = -1569588527,
        Enemy_Caterkiller_Patrol = -1925037834,
        Enemy_Crabmeat_Patrol = -4602935,
        Enemy_Crabmeat_Static = 1954728093,
        Enemy_Eggpawn_HomeRadius = 563423944,
        Enemy_Eggpawn_Static = -1626664411,
        Enemy_Motobug_Patrol = -512994427,
        Enemy_Motobug_Static = 1784109265,
        ProximityTarget = 341735889,
        ProximityTargetDream = -1324918542,
        ProximityTargetGold = -1420687747,
        Ring = 1186391869,
        RingCircleFlight_10 = -2028087329,
        RingCircleFlight_15 = -143187120,
        RingTargetable = -2090084921,
        Ring_RailVariant = -356241140,
        SpeedCheck = -763646937
    }
}
