namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000cf; serialized Int32 literals.
    public enum MissionIsNewState
    {
        None = 0,
        IsNew = -1216131765,
        Seen = 1832392787
    }
}
