namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000d5; serialized Int32 literals.
    public enum MissionType
    {
        BlueCoins = -2043677499,
        Default = 602145082,
        Jukebox = 1007517959,
        RedStarRings = -834909552
    }
}
