namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000d7; serialized Int32 literals.
    public enum MusicStoppedReason
    {
        Completed = -2117747330,
        Deselected = 614042296,
        Menu_Exit = 649771604,
        Paused = 1236694754,
        Skipped = 467406055
    }
}
