namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000db; serialized Int32 values.
    public enum NotificationType
    {
        ChallengeRefresh = -517856104,
        LapsedPlayer = 1549041558
    }
}
