namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000d9; serialized Int32 literals.
    public enum NotificationTimerType
    {
        OnChallengeRefresh = 974318058,
        ThirtyDaysFromNow = 2138338946
    }
}
