namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000dd; serialized Int32 literals.
    public enum OrnamentCategory
    {
        Achievement = -460385562,
        Challenge = 1815373889,
        Story = -469943945
    }
}
