namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000e1; serialized Int32 literals.
    public enum OutroSequenceIdentifier
    {
        Default = 602145082,
        Moon = 713446819,
        MoonReplay = 178166781,
        Replay = -701444981
    }
}
