namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000e5; serialized Int32 literals.
    public enum PersistentObjectIdentifierType
    {
        FTUE_Barrier_Switch = 1888733037,
        FTUE_GateKey_1 = 1315327459,
        FTUE_GateKey_2 = -680584103,
        FTUE_GateKey_3 = -1603785521,
        Zone1Act1_GateKey_1 = 1854295806,
        Zone1Act1_GateKey_2 = -141615292,
        Zone1Act1_GateKey_3 = -2138558510,
        Zone1Act3_GateKey_1 = 921368383,
        Zone1Act3_GateKey_2 = -1344035195,
        Zone1Act3_GateKey_3 = -656108013,
        Zone2Act1_EndBarrier_Trigger = -425334255,
        Zone2Act1_GateKey_1 = 2147165319,
        Zone2Act1_GateKey_2 = -420317891,
        Zone2Act1_GateKey_3 = -1846196821,
        Zone2Act1_GooRoom_Switch = -1195321879,
        Zone2Act1_Intro_Switch = 1039643022,
        Zone2Act2_QuarterPipeTurns_Switch = -1090947988,
        Zone2Act3_GateKey_1 = 664247622,
        Zone2Act3_GateKey_2 = -1096889092,
        Zone2Act3_GateKey_3 = -912655254,
        Zone3Act1_GateKey_1 = -973013137,
        Zone3Act1_GateKey_2 = 1594470101,
        Zone3Act1_GateKey_3 = 672046659,
        Zone3Act1_TrackRing_Switch = -1733165446,
        Zone3Act1_TutorialSkip = -343300429,
        Zone3Act2_HedgeMaze_Switch_Left = -1197303158,
        Zone3Act2_HedgeMaze_Switch_Middle = 860836464,
        Zone3Act2_HedgeMaze_Switch_Right = 325123192,
        Zone3Act3_GateKey_1 = -1637071186,
        Zone3Act3_GateKey_2 = 124065556,
        Zone3Act3_GateKey_3 = 1885480834,
        Zone4Act1_ButtonPuzzle_1 = -845598174,
        Zone4Act1_ButtonPuzzle_2 = 1418748824,
        Zone4Act1_ButtonPuzzle_3 = 597119758,
        Zone4Act2_GateKey_1 = -991717772,
        Zone4Act2_GateKey_2 = 1575667662,
        Zone4Act2_GateKey_3 = 720238424
    }
}
