namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000e9; serialized Int32 literals.
    public enum PlatformComponentTypes
    {
        Center = 1341641565,
        Corner = 238617981,
        CornerFlat = 876184315,
        Edge = -1133723347,
        Edge2 = -1917558476,
        Edge4 = 1691862017,
        Edge6 = -1965447891,
        InnerCorner = 980281801
    }
}
