namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000e7; serialized Int32 literals.
    public enum PlatformAssetTypes
    {
        None = 0,
        Debug = 1678670568,
        FactoryBlue = -1569732075,
        Grass = -1599692100,
        Stone = 294336613,
        Zone4 = 1589082332,
        Zone4Boss = 941109207
    }
}
