namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000eb; serialized Int32 literals.
    public enum PlayerProgressionTypes
    {
        BlueCoins = -2043677499,
        BonusZone1 = 1475437797,
        ChallengesFeatureUnlocked = 979966388,
        CharacterArchetype = 1876712185,
        CharacterSkin = -586459296,
        DreamPowerStore = -956412352,
        DreamPowerStoreBand1 = -1080670251,
        DreamPowerStoreBand2 = 647960175,
        DreamPowerStoreBand3 = 1368925945,
        DreamPowerStoreBand4 = -805522598,
        DreamPowerStoreItem = 300041463,
        Level = -1841172132,
        MissionGroup = 1936338494,
        MusicTrack = 731344614,
        Ornament = -1825035775,
        RewardTrack = -131369679,
        RewardTracksFeature = -2075139551
    }
}
