namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000ed; serialized Int32 literals.
    public enum ProjectileType
    {
        BuzzBomberProjectile = -779126459,
        GuardianKillerProjectile = 729954528,
        GuardianKillerStraightProjectile = -1018195575,
        GuardianReturnableProjectile = -64358761,
        GuardianReturnableStraightProjectile = -1309233230,
        NightmareEggmanSingleAscendingProjectile = 1626062266,
        NightmareEggmanSingleGravityCylinderBottomProjectile = -1297758686,
        NightmareEggmanSingleGravityCylinderLeftProjectile = -37204484,
        NightmareEggmanSingleGravityCylinderRightProjectile = -1010267407,
        NightmareEggmanSingleGravityCylinderTopProjectile = -640499151,
        NightmareEggmanSingleSpiralProjectile = -730243131,
        NightmareEggmanSingleStraightProjectile = 1620120979,
        NightmareEggmanSingleSwoopLeftRightProjectile = 236526209,
        NightmareEggmanSingleSwoopRightLeftProjectile = 2085139656,
        NightmareEggmanSingleVerticalSplineProjectile = -1913259210,
        NightmareEggmanTrioSpiralProjectile = 1236980226
    }
}
