namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000ef; serialized Int32 literals.
    public enum PromptSlotType
    {
        CTABonusLevels = 1464326728,
        CTAChallenges = 936849901,
        CTAOutfits = 1835214156,
        CTAPowers = 1102108581,
        CTARewards = -394606992,
        CTAShadowRewards = -606432406,
        CTAStyleRewards = 2034592165,
        GameHUDFixedPosition = -1965312549,
        GameHUDLowerMiddlePosition = 2132444668,
        GameHUDLowerPosition = 328972576,
        GameHUDMiddlePosition = 1928780454,
        GameHUDUpperMiddePosition = 1257787819,
        OnScreenControlsCameraZone = -1506835422
    }
}
