namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000f3; serialized Int32 literals.
    public enum RankType
    {
        None = 0,
        A = 740712820,
        B = -1255198514,
        C = -1037565864,
        D = 1548523003,
        S = -543223748
    }
}
