namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000f5; serialized Int32 literals.
    public enum ReplayMode
    {
        Off = 1122295862,
        Playback = -951563343,
        Record = -1808554008
    }
}
