namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000f7; serialized Int32 literals.
    public enum RewardTrackType
    {
        Adventure = 632844063,
        Outfits = -1400767250,
        Shadow = 2054273620
    }
}
