namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000f9; serialized Int32 literals.
    public enum ScreenControlsGroup
    {
        None = 0,
        Default = 602145082,
        InAir = -1032634697
    }
}
