namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000fd; serialized Int32 literals.
    public enum SurfacePathType
    {
        AnimCurve = -390959672,
        Ellipse = -1933998193,
        Line = 410953405,
        SineCurve = 1236644549,
        Spiral = -484936360,
        User = 1157219330
    }
}
