namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000fb; serialized Int32 literals.
    public enum SurfaceCrossSectionType
    {
        None = 0,
        Ellipse = -1933998193,
        Plane = -921169713
    }
}
