namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000101; serialized Int32 literals.
    public enum TerrainMetadataType
    {
        CameraOverride = 793647998,
        Climbable = -898501920,
        Effects = -2001650353,
        HalfPipe = 633057627,
        Tracker = 1826171722
    }
}
