namespace HardlightProject
{
    // Original HLAutoGenerated 0x020000ff; serialized Int32 literals.
    public enum TerrainEffectType
    {
        BouncyCastle = 1104714536,
        ClimbingWall = 863623331,
        Dirt = 1359868925,
        Glass = 274760208,
        Grass = -1599692100,
        ImpactDream = 2089383563,
        Metal = -926299770,
        Sand = 1762689114,
        Zone5 = 699418698
    }
}
