namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000103; serialized Int32 literals.
    public enum TerrainTrackerType
    {
        Broad = -1711278638,
        Narrow = -1842417965,
        Normal = 780292253,
        RunDownBuilding = -1815898205
    }
}
