namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000105; serialized Int32 literals.
    public enum TimeCategory
    {
        Camera = 874239612,
        CameraSystem = 1448652095,
        Effects = -2001650353,
        EnemyMovement = -870455447,
        Environment = 886747957,
        GameplayUnscaled = -1867633850,
        PlayerAnimation = 962018048,
        PlayerMovement = -172618227,
        PlayerPhysics = 1739680676,
        System = -968218126,
        UnityGlobal = -1580400188
    }
}
