namespace Hardlight
{
    // Original HLAutoGenerated enum: seven exact Int32 literals, no own methods.
    public enum UIContainerBehaviour
    {
        None = 0,
        Debug = 1678670568,
        Free = -2075864189,
        Linked = -1728062059,
        Single = -979361952,
        Stack = 1224951333,
        Transition = 58017178
    }
}
