namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000109; serialized Int32 literals.
    public enum UIShowType
    {
        Hidden = -2024091196,
        Locked = -438963992,
        Unlocked = 952597924
    }
}
