namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200010b; serialized Int32 literals.
    public enum UIWidgetButtonChallengeRewardSize
    {
        Large = 1371542769,
        Medium = -915112498,
        Small = 2112804700,
        Special = -1932444154
    }
}
