namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200010f; serialized Int32 literals.
    public enum ValidationErrorTypes
    {
        Animator = 1500770747,
        Audio = 282463194,
        AutoPlay = 182668702,
        CameraTrigger = 1066705457,
        CharacterCollision = -708524636,
        Collider = -202299804,
        DreamteckComponent = -977779999,
        Enemy = -214669338,
        EntityActivation = -1398295449,
        Generic = 1458937910,
        GravityTrigger = -418296049,
        HomingTarget = 1416560138,
        Layer = -328197035,
        Platform = 10400632,
        PostProcessing = 1883894019,
        RigidbodyForceTrigger = -1157612009,
        SimplifiedBody = 1863151097,
        Surface = 2096865163,
        TimeScaledComponent = -407814520,
        Total = -897262575,
        Track = -565656087,
        Transform = -863018819
    }
}
