namespace HardlightProject
{
    // Original HLAutoGenerated 0x0200010d; serialized Int32 literals.
    public enum ValidationErrorSeverity
    {
        Error = 1433829694,
        Exception = -990613635,
        Log = -429402704,
        Warning = -2131452637
    }
}
