namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000111; serialized Int32 literals.
    public enum ValidationObjectTypes
    {
        Prefab = -1458713211,
        Scene = -774712683
    }
}
