namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000113; serialized Int32 literals.
    public enum ValueType
    {
        Boolean = 1245677965,
        Float = -1056021542,
        Integer = -1699370258,
        String = -1850111280
    }
}
