namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000115; serialized Int32 literals.
    public enum WaypointContainerType
    {
        Compass = -1866691160,
        ScreenSpace = 102050233
    }
}
