namespace HardlightProject
{
    // Original HLAutoGenerated 0x02000117; serialized Int32 literals.
    public enum WaypointType
    {
        Checkpoint = -77589122,
        DreamFragment = -856035975,
        DreamPortal = 1366431580,
        EggmanAirship = 268624403,
        EndGoal = 126629452,
        Enemy = -214669338,
        Eye = 455097028,
        Generic = 1458937910,
        Key = -473426212,
        KeyGate = -504128165,
        Moon = 713446819,
        Orb = 1797780346,
        OrbCompass = -1225274643,
        SubGoal = -439117760
    }
}
