using System.Collections.Generic;
using UnityEngine;
using Unity.IL2CPP.CompilerServices;

namespace Hardlight
{
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [CreateAssetMenu(fileName = "TimeCategoryConfiguration", menuName = "Hardlight/HLUnityCore/TimeCategoryConfiguration", order = 0)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class TimeCategoryConfiguration : SystemConfigurationAsset
    {
        [SerializeField] private float m_defaultTimescale = 1f;
        [Tooltip("TimeCategories in priority order"), SerializeField]
        private List<TimeCategoryObject> m_categoriesPrioritised = new List<TimeCategoryObject>();
        [SerializeField] private TimeCategoryObject m_unityGlobalTime;
        [SerializeField] private bool m_generatesLookupStrings;
        [SerializeField] private string m_autoGeneratedClassName = "CLASS_NAME";
        [SerializeField] private string m_autoGeneratedLookupFolder = "PATH";
        [SerializeField] private string m_autoGeneratedNamespace = "NAMESPACE";

        // Original 06000e7a..7c / ARM64 1b1ab80..90; retain the live list.
        public float DefaultTimescale => m_defaultTimescale;
        public TimeCategoryObject UnityGlobalTime => m_unityGlobalTime;
        public IEnumerable<TimeCategoryObject> PrioritisedCategories => m_categoriesPrioritised;
        // 06000e7d / 1b1ab98 is an original empty override, not validation added by reconstruction.
        public override void Validate() { }
        // 06000e7e / 1b1ab9c calls genuine AddUnique; removal 06000e7f / 1b1abf8 removes one match.
        public void AddCategory(TimeCategoryObject categoryObject) { m_categoriesPrioritised.AddUnique(categoryObject); }
        public void RemoveCategory(TimeCategoryObject categoryObject) { m_categoriesPrioritised.Remove(categoryObject); }
        // 06000e80 / 1b1ac54: own field initializers precede the genuine base's constructor.
        public TimeCategoryConfiguration() { }
    }

    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [CreateAssetMenu(fileName = "TimeCategoryObject", menuName = "Hardlight/HLUnityCore/TimeCategoryObject")]
    [Il2CppSetOption(Option.NullChecks, false)]
    public class TimeCategoryObject : ScriptableObjectWithGuid
    {
        // Complete original fieldless type; 06000e81 / ARM64 1b1adc4.
        public TimeCategoryObject() { }
    }
}
