using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Security.Cryptography;
using Hardlight;
using UnityEngine;
namespace ProjectLucid.Verification
{
 public static partial class HLHapticsVerification
 {
  sealed class SourcePin {public readonly string Path,Sha;public readonly int Bytes;public SourcePin(string path,string sha,int bytes){Path=path;Sha=sha;Bytes=bytes;}}
  static SourcePin[] ProviderSourcePins() => TentativeProviderSourcePins();
  static FieldInfo ExactField(Type type,string name,int flags,Type fieldType)
  {
   FieldInfo field=type.GetField(name,Declared);Require(field!=null&&field.DeclaringType==type&&(int)field.Attributes==flags&&field.FieldType==fieldType,"exact genuine provider field "+type+"::"+name);return field;
  }
  static FieldInfo RefField(object reference,string name)
  {
   Type type=reference.GetType();while(type!=null && (!type.IsGenericType||type.GetGenericTypeDefinition()!=typeof(SystemRef<>)))type=type.BaseType;
   Require(type!=null&&type.Assembly==typeof(ProcessManager).Assembly,"genuine closed SystemRef owner");return type.GetField(name,Declared);
  }
  static void CheckProviderSourcesAndShapes()
  {
   string root=Directory.GetParent(Application.dataPath).FullName;
   foreach(SourcePin pin in ProviderSourcePins()) {byte[] bytes=File.ReadAllBytes(System.IO.Path.Combine(root,pin.Path));using(SHA256 sha=SHA256.Create())Require(bytes.Length==pin.Bytes&&string.Concat(sha.ComputeHash(bytes).Select(x=>x.ToString("x2")))==pin.Sha,"complete frozen provider source "+pin.Path);}
   Type core=typeof(ProcessManager);Require(core.Assembly.GetName().Name=="HLUnityCore.Runtime"&&core.GetFields(Declared).Length==5,"whole five static ProcessManager fields");
   Type info=core.GetNestedType("SystemInfo",BindingFlags.NonPublic);Require(info!=null&&info.Assembly==core.Assembly&&info.GetFields(Declared).Length==2,"genuine complete SystemInfo");
   Type cache=info.GetField("SystemRefDictionary",Declared).FieldType;Require(cache.IsGenericType&&cache.GetGenericTypeDefinition()==typeof(Dictionary<,>)&&cache.GetGenericArguments()[0]==typeof(string)&&cache.GetGenericArguments()[1].FullName=="Hardlight.ISystemRef"&&cache.GetGenericArguments()[1].Assembly==core.Assembly,"genuine typed-cache provider/interface");
   ExactField(info,"SystemRef",38,typeof(SystemRef));ExactField(info,"SystemRefDictionary",38,cache);
   ExactField(core,"s_systemDictionary",49,typeof(Dictionary<,>).MakeGenericType(typeof(string),info));ExactField(core,"s_systemActionLookup",49,typeof(Dictionary<SystemAction,Dictionary<ISystem,Action<object>>>));ExactField(core,"s_actionList",49,typeof(List<Action<object>>));ExactField(core,"s_systemActionInProgress",17,typeof(bool));
   Type logger=core.GetNestedType("ProcessManagerLogger",BindingFlags.NonPublic);Require(logger!=null&&logger.Assembly==core.Assembly,"genuine logger");ExactField(core,"s_logger",49,logger);
   Type reference=typeof(SystemRef<>);Require(reference.GetFields(Declared).Length==6,"whole SystemRef six fields");Type t=reference.GetGenericArguments()[0];
   ExactField(reference,"OnSystemStartup",1,typeof(Action<>).MakeGenericType(t));ExactField(reference,"OnSystemShutdown",1,typeof(Action<>).MakeGenericType(t));ExactField(reference,"m_actionOnSystemValid",1,typeof(FastAction<>).MakeGenericType(t));ExactField(reference,"m_systemName",33,typeof(string));ExactField(reference,"m_system",1,t);ExactField(reference,"m_isystem",1,typeof(ISystem));
   Type fast=typeof(FastActionBase<,>);Require(fast.GetFields(Declared).Length==4,"whole genuine FastAction mutation state");Type action=fast.GetGenericArguments()[1];
   ExactField(fast,"m_invocationList",36,typeof(List<>).MakeGenericType(action));ExactField(fast,"m_invocationActive",4,typeof(bool));ExactField(fast,"m_removedList",33,typeof(List<>).MakeGenericType(action));ExactField(fast,"m_addedList",33,typeof(List<>).MakeGenericType(action));
   CheckEnum(typeof(VibrationEvent),new[]{"None","DefaultSelection","LongPressSelection"},new[]{0,890026456,-1688333712});
   CheckEnum(typeof(VibrationType),new[]{"ImpactHeavy","ImpactLight","ImpactMedium","None","NotificationFailure","NotificationSuccess","NotificationWarning","Selection"},new[]{1827081371,2110532147,-1291822547,-1225125244,-1035786528,-1931937133,-1550403097,764997063});
  }
  static void CheckEnum(Type type,string[] names,int[] values)
  {
   Require(type.Assembly==typeof(VibrationEvent).Assembly&&type.Assembly.GetName().Name=="HLAutoGenerated"&&Enum.GetUnderlyingType(type)==typeof(int),"genuine enum provider");FieldInfo[] fields=type.GetFields(Declared).Where(x=>x.IsLiteral).OrderBy(x=>x.MetadataToken).ToArray();Require(fields.Length==names.Length,"whole enum literal count");for(int i=0;i<fields.Length;i++)Require(fields[i].Name==names[i]&&(int)fields[i].GetRawConstantValue()==values[i],"whole ordered original enum bits");
  }
  static bool Same(object a,object b) => a==null?b==null:a.GetType().IsValueType?a.Equals(b):ReferenceEquals(a,b);
  sealed class SharedSnapshot
  {
   readonly List<Action> checks=new List<Action>();readonly HashSet<object> visited=new HashSet<object>(ReferenceComparer.Instance);
   readonly IDictionary registry;readonly List<DictionaryEntry> rows;object allowedRef;
   public SharedSnapshot(object target)
   {
    Type pm=typeof(ProcessManager);registry=(IDictionary)pm.GetField("s_systemDictionary",Declared).GetValue(null);rows=Entries(registry);allowedRef=target==null?null:target.GetType().GetField("SystemRef",Declared).GetValue(target);
    Watch(()=>pm.GetField("s_systemDictionary",Declared).GetValue(null),registry,"registry identity");
    foreach(DictionaryEntry row in rows)CaptureInfo(row.Value);
    foreach(string name in new[]{"s_systemActionLookup","s_actionList","s_systemActionInProgress","s_logger"})
    {FieldInfo field=pm.GetField(name,Declared);object value=field.GetValue(null);Watch(()=>field.GetValue(null),value,"static "+name);if(name=="s_systemActionLookup")CaptureActions((IDictionary)value);else if(name=="s_actionList")CaptureList((IList)value);}
   }
   public static List<DictionaryEntry> Entries(IDictionary dictionary){var rows=new List<DictionaryEntry>();foreach(DictionaryEntry row in dictionary)rows.Add(row);return rows;}
   void Watch(Func<object> read,object expected,string label){checks.Add(()=>Require(Same(read(),expected),"shared identity/value "+label));}
   void CaptureDictionary(IDictionary dictionary)
   {
    List<DictionaryEntry> expected=Entries(dictionary);checks.Add(()=>{List<DictionaryEntry> actual=Entries(dictionary);Require(actual.Count==expected.Count,"shared dictionary count");for(int i=0;i<actual.Count;i++)Require(Same(actual[i].Key,expected[i].Key)&&Same(actual[i].Value,expected[i].Value),"shared ordered key/value identities");});
   }
   void CaptureList(IList list)
   {
    if(!visited.Add(list))return;object[] expected=new object[list.Count];list.CopyTo(expected,0);checks.Add(()=>{Require(list.Count==expected.Length,"shared queue/list count");for(int i=0;i<expected.Length;i++)Require(Same(list[i],expected[i]),"shared ordered queue/list element identity");});foreach(object item in expected)if(item is Delegate d)CaptureDelegate(d);
   }
   void CaptureDelegate(Delegate value)
   {
    if(!visited.Add(value))return;Delegate[] parts=value.GetInvocationList();checks.Add(()=>{Delegate[] actual=value.GetInvocationList();Require(actual.Length==parts.Length,"complete delegate invocation count");for(int i=0;i<actual.Length;i++)Require(actual[i].Method==parts[i].Method&&ReferenceEquals(actual[i].Target,parts[i].Target),"complete ordered delegate method/target");});
   }
   void CaptureActions(IDictionary dictionary)
   {
    CaptureDictionary(dictionary);foreach(DictionaryEntry row in Entries(dictionary)){IDictionary callbacks=(IDictionary)row.Value;CaptureDictionary(callbacks);foreach(DictionaryEntry callback in Entries(callbacks))if(callback.Value is Delegate d)CaptureDelegate(d);}
   }
   void CaptureInfo(object info)
   {
    Require(info!=null&&info.GetType()==typeof(ProcessManager).GetNestedType("SystemInfo",BindingFlags.NonPublic),"genuine registry row shape");
    foreach(FieldInfo field in info.GetType().GetFields(Declared)) {object value=field.GetValue(info);Watch(()=>field.GetValue(info),value,"SystemInfo "+field.Name);if(field.Name=="SystemRef")CaptureRef(value);else {IDictionary cache=(IDictionary)value;CaptureDictionary(cache);foreach(DictionaryEntry entry in Entries(cache))if(entry.Value!=null)CaptureRef(entry.Value);}}
   }
   void CaptureRef(object reference)
   {
    if(!visited.Add(reference))return;
    foreach(string name in new[]{"OnSystemStartup","OnSystemShutdown","m_actionOnSystemValid","m_systemName","m_system","m_isystem"})
    {FieldInfo field=RefField(reference,name);Require(field!=null,"complete genuine SystemRef field");object value=field.GetValue(reference);if(!ReferenceEquals(reference,allowedRef)||(name!="m_system"&&name!="m_isystem"))Watch(()=>field.GetValue(reference),value,"SystemRef "+name);if(value is Delegate d)CaptureDelegate(d);if(name=="m_actionOnSystemValid"&&value!=null)CaptureFast(value);}
   }
   void CaptureFast(object fast)
   {
    if(!visited.Add(fast))return;Type owner=fast.GetType();while(owner!=null&&(!owner.IsGenericType||owner.GetGenericTypeDefinition()!=typeof(FastActionBase<,>)))owner=owner.BaseType;Require(owner!=null&&owner.Assembly==typeof(ProcessManager).Assembly,"genuine deferred FastAction base");
    foreach(FieldInfo field in owner.GetFields(Declared)) {object value=field.GetValue(fast);Watch(()=>field.GetValue(fast),value,"FastAction "+field.Name);if(value is IList list)CaptureList(list);}
   }
   public void IncludeOwnedInfo(object info){allowedRef=info.GetType().GetField("SystemRef",Declared).GetValue(info);CaptureInfo(info);}
   public void Check(object newlyOwnedInfo)
   {
    foreach(Action check in checks)check();List<DictionaryEntry> actual=Entries(registry);bool originallyAbsent=rows.All(x=>!Equals(x.Key,typeof(VibrationManager).ToString()));Require(actual.Count==rows.Count+(originallyAbsent&&newlyOwnedInfo!=null?1:0),"registry exact count except one proven owned row");
    for(int i=0;i<rows.Count;i++)Require(Same(actual[i].Key,rows[i].Key)&&Same(actual[i].Value,rows[i].Value),"all preexisting ordered registry rows exact");
    if(actual.Count>rows.Count)Require(Equals(actual[actual.Count-1].Key,typeof(VibrationManager).ToString())&&ReferenceEquals(actual[actual.Count-1].Value,newlyOwnedInfo),"exact sole newly owned default row");
   }
  }
  sealed class ReferenceComparer:IEqualityComparer<object>{public static readonly ReferenceComparer Instance=new ReferenceComparer();public new bool Equals(object a,object b)=>ReferenceEquals(a,b);public int GetHashCode(object x)=>System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(x);}
  static readonly object OwnLeaseLock=new object();static bool OwnLeaseBusy;static object OwnedDefaultInfo,OwnedDefaultRef,OwnedDefaultCache,OwnedDefaultKey;
  sealed class ManagerLease:IDisposable
  {
   public GameObject Host;public VibrationManager Manager;public readonly List<Coroutine> Handles=new List<Coroutine>();public readonly List<IDisposable> Iterators=new List<IDisposable>();public readonly List<UnityEngine.Object> Assets=new List<UnityEngine.Object>();
   SharedSnapshot shared;object beforeTarget;bool active,closed,ownsLock;object newInfo;
   public static ManagerLease Acquire()
   {
    CheckWholeContract();var lease=new ManagerLease();try{lease.Preflight();lease.Host=new GameObject("HLHaptics original owned fixture");lease.Host.SetActive(false);lease.Manager=lease.Host.AddComponent<VibrationManager>();lease.CheckShared();Require(!lease.Manager.IsAvailable&&!lease.Manager.VibrationEnabledInSettings&&(bool)ManagerField("m_debugInEditor").GetValue(lease.Manager)==false&&ManagerField("m_vibrationEventDefinitions").GetValue(lease.Manager)==null,"actual inactive lifecycle defaults before setup");return lease;}catch(Exception error){lease.CloseWith(error);throw;}
   }
   void Preflight()
   {
    lock(OwnLeaseLock){Require(!OwnLeaseBusy,"another suite-owned manager lease is active");OwnLeaseBusy=true;ownsLock=true;}
    Type pm=typeof(ProcessManager);Require(!(bool)pm.GetField("s_systemActionInProgress",Declared).GetValue(null),"preflight holds during genuine shared dispatch");IDictionary registry=(IDictionary)pm.GetField("s_systemDictionary",Declared).GetValue(null);string name=typeof(VibrationManager).ToString();beforeTarget=registry.Contains(name)?registry[name]:null;
    if(beforeTarget!=null)
    {
     Require(ReferenceEquals(beforeTarget,OwnedDefaultInfo),"preflight rejects every foreign default row, including inert rows");object reference=InfoRef(beforeTarget),cache=InfoCache(beforeTarget);DictionaryEntry row=SharedSnapshot.Entries(registry).Single(x=>Equals(x.Key,name));Require(ReferenceEquals(reference,OwnedDefaultRef)&&ReferenceEquals(cache,OwnedDefaultCache)&&ReferenceEquals(row.Key,OwnedDefaultKey),"exact prior suite-owned inert provenance");CheckTarget(beforeTarget,null);
    }
    else Require(OwnedDefaultInfo==null,"prior owned row unexpectedly absent");shared=new SharedSnapshot(beforeTarget);
   }
   static object InfoRef(object info)=>info.GetType().GetField("SystemRef",Declared).GetValue(info);
   static object InfoCache(object info)=>info.GetType().GetField("SystemRefDictionary",Declared).GetValue(info);
   static void CheckTarget(object info,VibrationManager manager)
   {
    object reference=InfoRef(info);Require(((IDictionary)InfoCache(info)).Count==0,"owned target typed-cache must remain empty");foreach(string name in new[]{"OnSystemStartup","OnSystemShutdown","m_actionOnSystemValid"})Require(RefField(reference,name).GetValue(reference)==null,"reject target callbacks/deferred-valid object before activation "+name);
    Require(ReferenceEquals(RefField(reference,"m_system").GetValue(reference),manager)&&ReferenceEquals(RefField(reference,"m_isystem").GetValue(reference),manager)&&Equals(RefField(reference,"m_systemName").GetValue(reference),typeof(VibrationManager).ToString()),"exact owned target receiver/name state");
   }
   public void Activate(bool debug)
   {
    CheckShared();JsonUtility.FromJsonOverwrite(debug?"{\"m_debugInEditor\":true}":"{\"m_debugInEditor\":false}",Manager);Require((bool)ManagerField("m_debugInEditor").GetValue(Manager)==debug,"actual authentic debug JSON restoration");CheckShared();Host.SetActive(true);active=true;
    IDictionary registry=(IDictionary)typeof(ProcessManager).GetField("s_systemDictionary",Declared).GetValue(null);string name=typeof(VibrationManager).ToString();Require(registry.Contains(name),"genuine Awake registered exact default row");object info=registry[name];Require(beforeTarget==null||ReferenceEquals(info,beforeTarget),"existing suite-owned row identity retained");CheckTarget(info,Manager);
    if(beforeTarget==null){newInfo=info;shared.Check(newInfo);OwnedDefaultInfo=info;OwnedDefaultRef=InfoRef(info);OwnedDefaultCache=InfoCache(info);OwnedDefaultKey=SharedSnapshot.Entries(registry).Single(x=>Equals(x.Key,name)).Key;shared.IncludeOwnedInfo(info);}
    Require(Manager.IsAvailable==debug&&!(bool)ManagerField("m_debugInEditor").GetValue(Manager)&&!Manager.VibrationEnabledInSettings,"Awake availability before debug clear/settings unchanged");CheckShared();
   }
   public void CheckShared(){Require(shared!=null,"completed shared preflight snapshot");shared.Check(newInfo);if(active){IDictionary registry=(IDictionary)typeof(ProcessManager).GetField("s_systemDictionary",Declared).GetValue(null);DictionaryEntry row=SharedSnapshot.Entries(registry).Single(x=>Equals(x.Key,typeof(VibrationManager).ToString()));Require(ReferenceEquals(row.Key,OwnedDefaultKey)&&ReferenceEquals(row.Value,OwnedDefaultInfo)&&ReferenceEquals(InfoRef(row.Value),OwnedDefaultRef)&&ReferenceEquals(InfoCache(row.Value),OwnedDefaultCache),"whole owned provenance remains exact");}if(active)CheckTarget(beforeTarget??newInfo,Manager);else if(beforeTarget!=null)CheckTarget(beforeTarget,null);}
   public void Track(Coroutine handle){Require(handle!=null,"genuine owned coroutine handle");if(!Handles.Any(x=>ReferenceEquals(x,handle)))Handles.Add(handle);}
   public void Track(IEnumerator iterator){if(iterator is IDisposable disposable)Iterators.Add(disposable);}
   public void Dispose(){CloseWith(null);}
   public void CloseWith(Exception primary)
   {
    if(closed){if(primary!=null)throw primary;return;}closed=true;var errors=new List<Exception>();if(primary!=null)errors.Add(primary);
    foreach(Coroutine handle in Handles)try{if(Manager!=null)Manager.StopCoroutine(handle);}catch(Exception e){errors.Add(e);}foreach(IDisposable iterator in Iterators)try{iterator.Dispose();}catch(Exception e){errors.Add(e);}
    try{if(Host!=null)UnityEngine.Object.DestroyImmediate(Host);}catch(Exception e){errors.Add(e);}
    foreach(UnityEngine.Object asset in Assets)try{UnityEngine.Object.DestroyImmediate(asset);}catch(Exception e){errors.Add(e);}
    try
    {
     if(shared!=null)
     {
      object info=beforeTarget??newInfo;
      if(info!=null&&ReferenceEquals(RefField(InfoRef(info),"m_isystem").GetValue(InfoRef(info)),Manager))
      {errors.Add(new InvalidOperationException("First lifecycle failure: owned destruction did not revoke its registered identity"));ProcessManager.UnregisterSystem(Manager);}
      shared.Check(newInfo);if(info!=null)CheckTarget(info,null);
     }
    }catch(Exception e){errors.Add(e);}finally{if(ownsLock)lock(OwnLeaseLock){OwnLeaseBusy=false;ownsLock=false;}}
    if(errors.Count!=0)throw new AggregateException("Original HLHaptics first body and independent cleanup observations",errors);
   }
  }
  static FieldInfo ManagerField(string name)=>typeof(VibrationManager).GetField(name,Declared);
  static void WithManager(Action<ManagerLease> body){ManagerLease lease=ManagerLease.Acquire();Exception error=null;try{body(lease);}catch(Exception e){error=e;}lease.CloseWith(error);}
 }
}
