using UnityEngine;
using UnityEngine.Serialization;
using Unity.IL2CPP.CompilerServices;

namespace Hardlight
{
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public sealed class InputMonitorConfiguration : SingleScriptableObject
    {
        public const string DefaultFileName = "InputMonitorConfiguration";
        [SerializeField] private string m_configurationFolder = "Assets/Dash Assets/Configuration/";
        [SerializeField] private string m_activeInputBindingsFolder = "Assets/Dash Assets/Configuration/ActiveInputBindings/";
        [SerializeField] private string m_inputBindingsFolder = "Assets/Dash Assets/Configuration/InputBindings/";
        [SerializeField] private string m_inputMonitorsFolder = "Assets/Dash Assets/Configuration/InputMonitors/";
        [SerializeField] private string m_autoGeneratedCodeFolderPath = "Plugins/AutoGenerated";
        [SerializeField] private string m_autoGeneratedNamespace = "Hardlight";
        [SerializeField] private string m_autoGeneratedInputEnumComparerClassName = "HardlightEnumComparers";
        [SerializeField]
        [Tooltip("Path to the module's Plugin directory. Relative to the Assets/ folder. Will use the default path if not set.")]
        [FormerlySerializedAs("m_pluginLocation")]
        private string m_pluginLocationOverride = "";

        public string ConfigurationFolderPath { get { return m_configurationFolder; } } // 0600019f
        public string ActiveInputBindingsFolder { get { return m_activeInputBindingsFolder; } } // 060001a0
        public string InputBindingsFolder { get { return m_inputBindingsFolder; } } // 060001a1
        public string InputMonitorsFolder { get { return m_inputMonitorsFolder; } } // 060001a2
        public string AutoGeneratedCodeFolderPath { get { return m_autoGeneratedCodeFolderPath; } } // 060001a3
        public string AutoGeneratedNamespace { get { return m_autoGeneratedNamespace; } } // 060001a4
        public string AutoGeneratedInputEnumComparerClassName { get { return m_autoGeneratedInputEnumComparerClassName; } } // 060001a5
        public string PluginLocationOverride { get { return m_pluginLocationOverride; } } // 060001a6
        public InputMonitorConfiguration() { } // 060001a7: eight original stores before genuine base.
    }
}
