using System;
using Unity.IL2CPP.CompilerServices;

namespace ClientDataAPI
{
    // Original HLAutoGenerated 0x02000005. All own fields/bodies retained.
    // Shipped EncodableMessage/DecodableMessage have zero methods. The five
    // original Final+Virtual methods compile as ordinary methods here; this
    // stripped interface/method-flag boundary is explicit, not metadata parity.
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public sealed class LocalisedString : EncodableMessage, DecodableMessage
    {
        // 0x04000006; original field order/native offset 0.
        public const int ID = -1700661691;
        // 0x04000007; original field order/native offset 0.
        public static readonly int NUM_ARGS_DEFAULT = 0;
        // 0x04000008; original field order/native offset 16.
        private string m_id;
        // 0x04000009; original field order/native offset 24.
        private string m_content;
        // 0x0400000a; original field order/native offset 32.
        private int m_numArgs;
        // 0x0400000b; original field order/native offset 8.
        private static LocalisedString s_encodeInstance = new LocalisedString();
        // 0x0400000c; original field order/native offset 36.
        private bool m_poolAcquired;
        // 0x0400000d; original field order/native offset 16.
        private static int s_poolNumAcquired = 0;
        // 0x0400000e; original field order/native offset 20.
        private static int s_poolSize = 20;
        // 0x0400000f; original field order/native offset 24.
        private static LocalisedString[] s_poolInstances = new LocalisedString[s_poolSize];

        // 0x06000006; original ARM64 0x19dafb4 (get_MessageId).
        public int MessageId { get => ID; }

        // 0x06000007; original ARM64 0x19dafc0 (get_Id).
        // 0x06000008; original ARM64 0x19dafc8 (set_Id).
        public string Id { get => m_id; set => m_id = value; }

        // 0x06000009; original ARM64 0x19dafd0 (get_Content).
        // 0x0600000a; original ARM64 0x19dafd8 (set_Content).
        public string Content { get => m_content; set => m_content = value; }

        // 0x0600000b; original ARM64 0x19dafe0 (get_NumArgs).
        // 0x0600000c; original ARM64 0x19dafe8 (set_NumArgs).
        public int NumArgs { get => m_numArgs; set => m_numArgs = value; }

        // 0x0600000d; original ARM64 0x19daff0 (GetEncodingInstance).
        public static LocalisedString GetEncodingInstance()
        {
            s_encodeInstance.Reset();
            return s_encodeInstance;
        }

        // 0x0600000e; original ARM64 0x19dae6c (.ctor).
        public LocalisedString()
        {
            m_poolAcquired = false;
            Reset();
        }

        // 0x0600000f; original ARM64 0x19db07c (Reset).
        public void Reset()
        {
            m_id = null;
            m_content = null;
            m_numArgs = 0;
        }

        // 0x06000010; original ARM64 0x19db0b8 (PoolAcquire).
        public static LocalisedString PoolAcquire()
        {
            if (s_poolNumAcquired < s_poolSize)
            {
                for (int i = s_poolNumAcquired; i < s_poolSize; ++i)
                {
                    LocalisedString instance = s_poolInstances[i];
                    if (instance == null)
                    {
                        instance = new LocalisedString();
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        s_poolInstances[i] = instance;
                        return instance;
                    }
                    if (!instance.m_poolAcquired)
                    {
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        instance.Reset();
                        return instance;
                    }
                }
                for (int i = 0; i < s_poolNumAcquired; ++i)
                {
                    LocalisedString instance = s_poolInstances[i];
                    if (instance == null)
                    {
                        instance = new LocalisedString();
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        s_poolInstances[i] = instance;
                        return instance;
                    }
                    if (!instance.m_poolAcquired)
                    {
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        instance.Reset();
                        return instance;
                    }
                }
            }
            return new LocalisedString();
        }

        // 0x06000011; original ARM64 0x19db340 (PoolRelease).
        public void PoolRelease()
        {
            if (m_poolAcquired)
            {
                m_poolAcquired = false;
                s_poolNumAcquired = unchecked(s_poolNumAcquired - 1);
            }
        }

        // 0x06000012; original ARM64 0x19db3b4 (PoolNumAcquired).
        public static int PoolNumAcquired() => s_poolNumAcquired;

        // 0x06000013; original ARM64 0x19db430 (PoolResize).
        public static void PoolResize(int poolSize)
        {
            for (int i = 0; i < s_poolSize; ++i)
            {
                LocalisedString instance = s_poolInstances[i];
                if (instance != null) instance.m_poolAcquired = false;
            }
            s_poolSize = poolSize;
            s_poolInstances = new LocalisedString[poolSize];
            s_poolNumAcquired = 0;
        }

        // 0x06000014; original ARM64 0x19db540 (encodedLength).
        public int encodedLength()
        {
            if (m_id == null) throw new NullReferenceException();
            int length = NetworkBuffer.stringLength(m_id);
            if (m_content == null) throw new NullReferenceException();
            length = unchecked(length + NetworkBuffer.stringLength(m_content) + 2);
            if (m_numArgs != 0)
                length = unchecked(length + NetworkBuffer.varInt32Length(m_numArgs) + 1);
            return length;
        }

        // 0x06000015; original ARM64 0x19db5d8 (encode).
        public byte[] encode()
        {
            int length = encodedLength();
            byte[] data = new byte[length];
            NetworkBuffer buffer = new NetworkBuffer(data, 0, length);
            encode(ref buffer, length);
            return data;
        }

        // 0x06000016; original ARM64 0x19db79c (encode).
        public void encode(ref NetworkBuffer buffer) => encode(ref buffer, encodedLength());

        // 0x06000017; original ARM64 0x19db67c (encode).
        private void encode(ref NetworkBuffer buffer, int length)
        {
            if (m_id == null) throw new NullReferenceException();
            int start = buffer.Offset;
            buffer.writeInt32(1);
            buffer.writeString(m_id);
            if (m_content == null) throw new NullReferenceException();
            buffer.writeInt32(2);
            buffer.writeString(m_content);
            if (m_numArgs != 0) { buffer.writeInt32(3); buffer.writeInt32(m_numArgs); }
            if (buffer.Offset != unchecked(start + length)) throw new IndexOutOfRangeException();
        }

        // 0x06000018; original ARM64 0x19db7cc (decode).
        public static LocalisedString decode(byte[] data)
        {
            NetworkBuffer buffer = new NetworkBuffer(data, 0, data.Length);
            return decode(ref buffer);
        }

        // 0x06000019; original ARM64 0x19db964 (decode).
        public static LocalisedString decode(byte[] data, int offset, int length)
        {
            NetworkBuffer buffer = new NetworkBuffer(data, offset, length);
            return decode(ref buffer);
        }

        // 0x0600001a; original ARM64 0x19dba74 (decode).
        public static LocalisedString decode(ref NetworkBuffer buffer, int length)
        {
            NetworkBuffer child = buffer.SubRange(buffer.Offset, length);
            buffer.skip(length);
            return decode(ref child);
        }

        // 0x0600001b; original ARM64 0x19db8cc (decode).
        public static LocalisedString decode(ref NetworkBuffer buffer)
        {
            LocalisedString instance = new LocalisedString();
            instance.decodeInto(ref buffer);
            return instance;
        }

        // 0x0600001c; original ARM64 0x19dbb90 (decodeInto).
        public void decodeInto(ref NetworkBuffer buffer)
        {
            int previousTag = int.MinValue;
            while (buffer.Remaining > 0)
            {
                int tag = buffer.readVarInt32();
                if (tag < previousTag) throw new IndexOutOfRangeException();
                previousTag = tag;
                switch (tag)
                {
                    case 1: m_id = buffer.readString(); break;
                    case 2: m_content = buffer.readString(); break;
                    case 3: m_numArgs = buffer.readInt32(); break;
                    default:
                        if (tag <= 2) throw new IndexOutOfRangeException();
                        buffer.skip(buffer.Remaining);
                        break;
                }
            }
        }

        // 0x0600001d; original ARM64 0x19dbcd8 (.cctor).
        // BeforeFieldInit static initializer is emitted from the ordered field initializers above.
    }
}
