using System;
using Unity.IL2CPP.CompilerServices;

namespace ClientDataAPI
{
    // Original HLAutoGenerated 0x02000008. All own fields/bodies retained.
    // Shipped EncodableMessage/DecodableMessage have zero methods. The five
    // original Final+Virtual methods compile as ordinary methods here; this
    // stripped interface/method-flag boundary is explicit, not metadata parity.
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.NullChecks, false)]
    public sealed class LocalisationDefinitions : EncodableMessage, DecodableMessage
    {
        // 0x04000025; original field order/native offset 0.
        public const int ID = 1007235840;
        // 0x04000026; original field order/native offset 16.
        private SupportedLanguage[] m_supportedLanguages;
        // 0x04000027; original field order/native offset 24.
        private StringTable m_stringTable;
        // 0x04000028; original field order/native offset 0.
        private static LocalisationDefinitions s_encodeInstance = new LocalisationDefinitions();
        // 0x04000029; original field order/native offset 32.
        private bool m_poolAcquired;
        // 0x0400002a; original field order/native offset 8.
        private static int s_poolNumAcquired = 0;
        // 0x0400002b; original field order/native offset 12.
        private static int s_poolSize = 20;
        // 0x0400002c; original field order/native offset 16.
        private static LocalisationDefinitions[] s_poolInstances = new LocalisationDefinitions[s_poolSize];

        // 0x0600004e; original ARM64 0x19ddb00 (get_MessageId).
        public int MessageId { get => ID; }

        // 0x0600004f; original ARM64 0x19ddb0c (get_SupportedLanguages).
        // 0x06000050; original ARM64 0x19ddb14 (set_SupportedLanguages).
        public SupportedLanguage[] SupportedLanguages { get => m_supportedLanguages; set => m_supportedLanguages = value; }

        // 0x06000051; original ARM64 0x19ddb1c (get_StringTable).
        // 0x06000052; original ARM64 0x19ddb24 (set_StringTable).
        public StringTable StringTable { get => m_stringTable; set => m_stringTable = value; }

        // 0x06000053; original ARM64 0x19ddb2c (GetEncodingInstance).
        public static LocalisationDefinitions GetEncodingInstance()
        {
            s_encodeInstance.Reset();
            return s_encodeInstance;
        }

        // 0x06000054; original ARM64 0x19daf2c (.ctor).
        public LocalisationDefinitions()
        {
            m_poolAcquired = false;
            Reset();
        }

        // 0x06000055; original ARM64 0x19ddbb4 (Reset).
        public void Reset()
        {
            m_supportedLanguages = null;
            m_stringTable = null;
        }

        // 0x06000056; original ARM64 0x19ddbe8 (PoolAcquire).
        public static LocalisationDefinitions PoolAcquire()
        {
            if (s_poolNumAcquired < s_poolSize)
            {
                for (int i = s_poolNumAcquired; i < s_poolSize; ++i)
                {
                    LocalisationDefinitions instance = s_poolInstances[i];
                    if (instance == null)
                    {
                        instance = new LocalisationDefinitions();
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        s_poolInstances[i] = instance;
                        return instance;
                    }
                    if (!instance.m_poolAcquired)
                    {
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        instance.Reset();
                        return instance;
                    }
                }
                for (int i = 0; i < s_poolNumAcquired; ++i)
                {
                    LocalisationDefinitions instance = s_poolInstances[i];
                    if (instance == null)
                    {
                        instance = new LocalisationDefinitions();
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        s_poolInstances[i] = instance;
                        return instance;
                    }
                    if (!instance.m_poolAcquired)
                    {
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        instance.Reset();
                        return instance;
                    }
                }
            }
            return new LocalisationDefinitions();
        }

        // 0x06000057; original ARM64 0x19dde30 (PoolRelease).
        public void PoolRelease()
        {
            if (m_poolAcquired)
            {
                m_poolAcquired = false;
                s_poolNumAcquired = unchecked(s_poolNumAcquired - 1);
            }
        }

        // 0x06000058; original ARM64 0x19ddea4 (PoolNumAcquired).
        public static int PoolNumAcquired() => s_poolNumAcquired;

        // 0x06000059; original ARM64 0x19ddf20 (PoolResize).
        public static void PoolResize(int poolSize)
        {
            for (int i = 0; i < s_poolSize; ++i)
            {
                LocalisationDefinitions instance = s_poolInstances[i];
                if (instance != null) instance.m_poolAcquired = false;
            }
            s_poolSize = poolSize;
            s_poolInstances = new LocalisationDefinitions[poolSize];
            s_poolNumAcquired = 0;
        }

        // 0x0600005a; original ARM64 0x19de030 (encodedLength).
        public int encodedLength()
        {
            if (m_supportedLanguages == null) throw new NullReferenceException();
            int length = unchecked(NetworkBuffer.varInt32Length(m_supportedLanguages.Length) + 1);
            for (int i = 0; i < m_supportedLanguages.Length; ++i)
            {
                if (m_supportedLanguages[i] == null) length = unchecked(length + 1);
                else
                {
                    int childLength = m_supportedLanguages[i].encodedLength();
                    length = unchecked(length + NetworkBuffer.varInt32Length(unchecked(childLength + 1)) + childLength);
                }
            }
            if (m_stringTable == null) throw new NullReferenceException();
            int tableLength = m_stringTable.encodedLength();
            return unchecked(length + NetworkBuffer.varInt32Length(tableLength) + tableLength + 1);
        }

        // 0x0600005b; original ARM64 0x19de178 (encode).
        public byte[] encode()
        {
            int length = encodedLength();
            byte[] data = new byte[length];
            NetworkBuffer buffer = new NetworkBuffer(data, 0, length);
            encode(ref buffer, length);
            return data;
        }

        // 0x0600005c; original ARM64 0x19de45c (encode).
        public void encode(ref NetworkBuffer buffer) => encode(ref buffer, encodedLength());

        // 0x0600005d; original ARM64 0x19de21c (encode).
        private void encode(ref NetworkBuffer buffer, int length)
        {
            if (m_supportedLanguages == null) throw new NullReferenceException();
            int start = buffer.Offset;
            buffer.writeInt32(1);
            buffer.writeInt32(m_supportedLanguages.Length);
            for (int i = 0; i < m_supportedLanguages.Length; ++i)
            {
                if (m_supportedLanguages[i] == null) buffer.writeInt32(0);
                else
                {
                    buffer.writeInt32(unchecked(m_supportedLanguages[i].encodedLength() + 1));
                    m_supportedLanguages[i].encode(ref buffer);
                }
            }
            if (m_stringTable == null) throw new NullReferenceException();
            buffer.writeInt32(2);
            buffer.writeInt32(m_stringTable.encodedLength());
            m_stringTable.encode(ref buffer);
            if (buffer.Offset != unchecked(start + length)) throw new IndexOutOfRangeException();
        }

        // 0x0600005e; original ARM64 0x19de48c (decode).
        public static LocalisationDefinitions decode(byte[] data)
        {
            NetworkBuffer buffer = new NetworkBuffer(data, 0, data.Length);
            return decode(ref buffer);
        }

        // 0x0600005f; original ARM64 0x19de61c (decode).
        public static LocalisationDefinitions decode(byte[] data, int offset, int length)
        {
            NetworkBuffer buffer = new NetworkBuffer(data, offset, length);
            return decode(ref buffer);
        }

        // 0x06000060; original ARM64 0x19de728 (decode).
        public static LocalisationDefinitions decode(ref NetworkBuffer buffer, int length)
        {
            NetworkBuffer child = buffer.SubRange(buffer.Offset, length);
            buffer.skip(length);
            return decode(ref child);
        }

        // 0x06000061; original ARM64 0x19de588 (decode).
        public static LocalisationDefinitions decode(ref NetworkBuffer buffer)
        {
            LocalisationDefinitions instance = new LocalisationDefinitions();
            instance.decodeInto(ref buffer);
            return instance;
        }

        // 0x06000062; original ARM64 0x19de840 (decodeInto).
        public void decodeInto(ref NetworkBuffer buffer)
        {
            int previousTag = int.MinValue;
            while (buffer.Remaining > 0)
            {
                int tag = buffer.readVarInt32();
                if (tag < previousTag) throw new IndexOutOfRangeException();
                previousTag = tag;
                switch (tag)
                {
                    case 1:
                        m_supportedLanguages = new SupportedLanguage[buffer.readInt32()];
                        for (int i = 0; i < m_supportedLanguages.Length; ++i)
                        {
                            int childLength = buffer.readInt32();
                            m_supportedLanguages[i] = childLength == 0 ? null : SupportedLanguage.decode(ref buffer, unchecked(childLength - 1));
                        }
                        break;
                    case 2: m_stringTable = StringTable.decode(ref buffer, buffer.readInt32()); break;
                    default:
                        if (tag <= 1) throw new IndexOutOfRangeException();
                        buffer.skip(buffer.Remaining);
                        break;
                }
            }
        }

        // 0x06000063; original ARM64 0x19deb40 (.cctor).
        // BeforeFieldInit static initializer is emitted from the ordered field initializers above.
    }
}
