using System;
using Unity.IL2CPP.CompilerServices;

namespace ClientDataAPI
{
    // Original HLAutoGenerated 0x02000006. All own fields/bodies retained.
    // Shipped EncodableMessage/DecodableMessage have zero methods. The five
    // original Final+Virtual methods compile as ordinary methods here; this
    // stripped interface/method-flag boundary is explicit, not metadata parity.
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public sealed class StringTable : EncodableMessage, DecodableMessage
    {
        // 0x04000010; original field order/native offset 0.
        public const int ID = 146798109;
        // 0x04000011; original field order/native offset 0.
        public static readonly int LANGUAGE_DEFAULT = 0;
        // 0x04000012; original field order/native offset 16.
        private int m_language;
        // 0x04000013; original field order/native offset 24.
        private LocalisedString[] m_strings;
        // 0x04000014; original field order/native offset 32.
        private string m_hash;
        // 0x04000015; original field order/native offset 8.
        private static StringTable s_encodeInstance = new StringTable();
        // 0x04000016; original field order/native offset 40.
        private bool m_poolAcquired;
        // 0x04000017; original field order/native offset 16.
        private static int s_poolNumAcquired = 0;
        // 0x04000018; original field order/native offset 20.
        private static int s_poolSize = 20;
        // 0x04000019; original field order/native offset 24.
        private static StringTable[] s_poolInstances = new StringTable[s_poolSize];

        // 0x0600001e; original ARM64 0x19dbdbc (get_MessageId).
        public int MessageId { get => ID; }

        // 0x0600001f; original ARM64 0x19dbdc8 (get_Language).
        // 0x06000020; original ARM64 0x19dbdd0 (set_Language).
        public int Language { get => m_language; set => m_language = value; }

        // 0x06000021; original ARM64 0x19dbdd8 (get_Strings).
        // 0x06000022; original ARM64 0x19dbde0 (set_Strings).
        public LocalisedString[] Strings { get => m_strings; set => m_strings = value; }

        // 0x06000023; original ARM64 0x19dbde8 (get_Hash).
        // 0x06000024; original ARM64 0x19dbdf0 (set_Hash).
        public string Hash { get => m_hash; set => m_hash = value; }

        // 0x06000025; original ARM64 0x19dbdf8 (GetEncodingInstance).
        public static StringTable GetEncodingInstance()
        {
            s_encodeInstance.Reset();
            return s_encodeInstance;
        }

        // 0x06000026; original ARM64 0x19daeb8 (.ctor).
        public StringTable()
        {
            m_poolAcquired = false;
            Reset();
        }

        // 0x06000027; original ARM64 0x19dbe84 (Reset).
        public void Reset()
        {
            m_language = 0;
            m_strings = null;
            m_hash = null;
        }

        // 0x06000028; original ARM64 0x19dbebc (PoolAcquire).
        public static StringTable PoolAcquire()
        {
            if (s_poolNumAcquired < s_poolSize)
            {
                for (int i = s_poolNumAcquired; i < s_poolSize; ++i)
                {
                    StringTable instance = s_poolInstances[i];
                    if (instance == null)
                    {
                        instance = new StringTable();
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        s_poolInstances[i] = instance;
                        return instance;
                    }
                    if (!instance.m_poolAcquired)
                    {
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        instance.Reset();
                        return instance;
                    }
                }
                for (int i = 0; i < s_poolNumAcquired; ++i)
                {
                    StringTable instance = s_poolInstances[i];
                    if (instance == null)
                    {
                        instance = new StringTable();
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        s_poolInstances[i] = instance;
                        return instance;
                    }
                    if (!instance.m_poolAcquired)
                    {
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        instance.Reset();
                        return instance;
                    }
                }
            }
            return new StringTable();
        }

        // 0x06000029; original ARM64 0x19dc10c (PoolRelease).
        public void PoolRelease()
        {
            if (m_poolAcquired)
            {
                m_poolAcquired = false;
                s_poolNumAcquired = unchecked(s_poolNumAcquired - 1);
            }
        }

        // 0x0600002a; original ARM64 0x19dc180 (PoolNumAcquired).
        public static int PoolNumAcquired() => s_poolNumAcquired;

        // 0x0600002b; original ARM64 0x19dc1fc (PoolResize).
        public static void PoolResize(int poolSize)
        {
            for (int i = 0; i < s_poolSize; ++i)
            {
                StringTable instance = s_poolInstances[i];
                if (instance != null) instance.m_poolAcquired = false;
            }
            s_poolSize = poolSize;
            s_poolInstances = new StringTable[poolSize];
            s_poolNumAcquired = 0;
        }

        // 0x0600002c; original ARM64 0x19dc30c (encodedLength).
        public int encodedLength()
        {
            int length = m_language == 0 ? 1 : unchecked(NetworkBuffer.varInt32Length(m_language) + 2);
            if (m_strings == null) throw new NullReferenceException();
            length = unchecked(length + NetworkBuffer.varInt32Length(m_strings.Length));
            for (int i = 0; i < m_strings.Length; ++i)
            {
                if (m_strings[i] == null) length = unchecked(length + 1);
                else
                {
                    int childLength = m_strings[i].encodedLength();
                    length = unchecked(length + NetworkBuffer.varInt32Length(unchecked(childLength + 1)) + childLength);
                }
            }
            if (m_hash == null) throw new NullReferenceException();
            return unchecked(length + NetworkBuffer.stringLength(m_hash) + 1);
        }

        // 0x0600002d; original ARM64 0x19dc424 (encode).
        public byte[] encode()
        {
            int length = encodedLength();
            byte[] data = new byte[length];
            NetworkBuffer buffer = new NetworkBuffer(data, 0, length);
            encode(ref buffer, length);
            return data;
        }

        // 0x0600002e; original ARM64 0x19dc688 (encode).
        public void encode(ref NetworkBuffer buffer) => encode(ref buffer, encodedLength());

        // 0x0600002f; original ARM64 0x19dc4c8 (encode).
        private void encode(ref NetworkBuffer buffer, int length)
        {
            int start = buffer.Offset;
            if (m_language != 0) { buffer.writeInt32(1); buffer.writeInt32(m_language); }
            if (m_strings == null) throw new NullReferenceException();
            buffer.writeInt32(2);
            buffer.writeInt32(m_strings.Length);
            for (int i = 0; i < m_strings.Length; ++i)
            {
                if (m_strings[i] == null) buffer.writeInt32(0);
                else
                {
                    buffer.writeInt32(unchecked(m_strings[i].encodedLength() + 1));
                    m_strings[i].encode(ref buffer);
                }
            }
            if (m_hash == null) throw new NullReferenceException();
            buffer.writeInt32(3);
            buffer.writeString(m_hash);
            if (buffer.Offset != unchecked(start + length)) throw new IndexOutOfRangeException();
        }

        // 0x06000030; original ARM64 0x19dc6b8 (decode).
        public static StringTable decode(byte[] data)
        {
            NetworkBuffer buffer = new NetworkBuffer(data, 0, data.Length);
            return decode(ref buffer);
        }

        // 0x06000031; original ARM64 0x19dc850 (decode).
        public static StringTable decode(byte[] data, int offset, int length)
        {
            NetworkBuffer buffer = new NetworkBuffer(data, offset, length);
            return decode(ref buffer);
        }

        // 0x06000032; original ARM64 0x19dc960 (decode).
        public static StringTable decode(ref NetworkBuffer buffer, int length)
        {
            NetworkBuffer child = buffer.SubRange(buffer.Offset, length);
            buffer.skip(length);
            return decode(ref child);
        }

        // 0x06000033; original ARM64 0x19dc7b8 (decode).
        public static StringTable decode(ref NetworkBuffer buffer)
        {
            StringTable instance = new StringTable();
            instance.decodeInto(ref buffer);
            return instance;
        }

        // 0x06000034; original ARM64 0x19dca7c (decodeInto).
        public void decodeInto(ref NetworkBuffer buffer)
        {
            int previousTag = int.MinValue;
            while (buffer.Remaining > 0)
            {
                int tag = buffer.readVarInt32();
                if (tag < previousTag) throw new IndexOutOfRangeException();
                previousTag = tag;
                switch (tag)
                {
                    case 1: m_language = buffer.readInt32(); break;
                    case 2:
                        m_strings = new LocalisedString[buffer.readInt32()];
                        for (int i = 0; i < m_strings.Length; ++i)
                        {
                            int childLength = buffer.readInt32();
                            m_strings[i] = childLength == 0 ? null : LocalisedString.decode(ref buffer, unchecked(childLength - 1));
                        }
                        break;
                    case 3: m_hash = buffer.readString(); break;
                    default:
                        if (tag <= 2) throw new IndexOutOfRangeException();
                        buffer.skip(buffer.Remaining);
                        break;
                }
            }
        }

        // 0x06000035; original ARM64 0x19dcd88 (.cctor).
        // BeforeFieldInit static initializer is emitted from the ordered field initializers above.
    }
}
