using System;
using Unity.IL2CPP.CompilerServices;

namespace ClientDataAPI
{
    // Original HLAutoGenerated 0x02000007. All own fields/bodies retained.
    // Shipped EncodableMessage/DecodableMessage have zero methods. The five
    // original Final+Virtual methods compile as ordinary methods here; this
    // stripped interface/method-flag boundary is explicit, not metadata parity.
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    public sealed class SupportedLanguage : EncodableMessage, DecodableMessage
    {
        // 0x0400001a; original field order/native offset 0.
        public const int ID = -1632469498;
        // 0x0400001b; original field order/native offset 0.
        public static readonly int LANGUAGE_DEFAULT = 0;
        // 0x0400001c; original field order/native offset 4.
        public static readonly int LOCALISED_NAME_DEFAULT = 0;
        // 0x0400001d; original field order/native offset 16.
        private int m_language;
        // 0x0400001e; original field order/native offset 20.
        private int m_localisedName;
        // 0x0400001f; original field order/native offset 24.
        private bool m_isRTL;
        // 0x04000020; original field order/native offset 8.
        private static SupportedLanguage s_encodeInstance = new SupportedLanguage();
        // 0x04000021; original field order/native offset 25.
        private bool m_poolAcquired;
        // 0x04000022; original field order/native offset 16.
        private static int s_poolNumAcquired = 0;
        // 0x04000023; original field order/native offset 20.
        private static int s_poolSize = 20;
        // 0x04000024; original field order/native offset 24.
        private static SupportedLanguage[] s_poolInstances = new SupportedLanguage[s_poolSize];

        // 0x06000036; original ARM64 0x19dce6c (get_MessageId).
        public int MessageId { get => ID; }

        // 0x06000037; original ARM64 0x19dce78 (get_Language).
        // 0x06000038; original ARM64 0x19dce80 (set_Language).
        public int Language { get => m_language; set => m_language = value; }

        // 0x06000039; original ARM64 0x19dce88 (get_LocalisedName).
        // 0x0600003a; original ARM64 0x19dce90 (set_LocalisedName).
        public int LocalisedName { get => m_localisedName; set => m_localisedName = value; }

        // 0x0600003b; original ARM64 0x19dce98 (get_IsRTL).
        // 0x0600003c; original ARM64 0x19dcea0 (set_IsRTL).
        public bool IsRTL { get => m_isRTL; set => m_isRTL = value; }

        // 0x0600003d; original ARM64 0x19dcea8 (GetEncodingInstance).
        public static SupportedLanguage GetEncodingInstance()
        {
            s_encodeInstance.Reset();
            return s_encodeInstance;
        }

        // 0x0600003e; original ARM64 0x19daf00 (.ctor).
        public SupportedLanguage()
        {
            m_poolAcquired = false;
            Reset();
        }

        // 0x0600003f; original ARM64 0x19dcf14 (Reset).
        public void Reset()
        {
            m_isRTL = false;
            m_language = 0;
            m_localisedName = 0;
        }

        // 0x06000040; original ARM64 0x19dcf20 (PoolAcquire).
        public static SupportedLanguage PoolAcquire()
        {
            if (s_poolNumAcquired < s_poolSize)
            {
                for (int i = s_poolNumAcquired; i < s_poolSize; ++i)
                {
                    SupportedLanguage instance = s_poolInstances[i];
                    if (instance == null)
                    {
                        instance = new SupportedLanguage();
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        s_poolInstances[i] = instance;
                        return instance;
                    }
                    if (!instance.m_poolAcquired)
                    {
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        instance.Reset();
                        return instance;
                    }
                }
                for (int i = 0; i < s_poolNumAcquired; ++i)
                {
                    SupportedLanguage instance = s_poolInstances[i];
                    if (instance == null)
                    {
                        instance = new SupportedLanguage();
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        s_poolInstances[i] = instance;
                        return instance;
                    }
                    if (!instance.m_poolAcquired)
                    {
                        instance.m_poolAcquired = true;
                        s_poolNumAcquired = unchecked(s_poolNumAcquired + 1);
                        instance.Reset();
                        return instance;
                    }
                }
            }
            return new SupportedLanguage();
        }

        // 0x06000041; original ARM64 0x19dd148 (PoolRelease).
        public void PoolRelease()
        {
            if (m_poolAcquired)
            {
                m_poolAcquired = false;
                s_poolNumAcquired = unchecked(s_poolNumAcquired - 1);
            }
        }

        // 0x06000042; original ARM64 0x19dd1bc (PoolNumAcquired).
        public static int PoolNumAcquired() => s_poolNumAcquired;

        // 0x06000043; original ARM64 0x19dd238 (PoolResize).
        public static void PoolResize(int poolSize)
        {
            for (int i = 0; i < s_poolSize; ++i)
            {
                SupportedLanguage instance = s_poolInstances[i];
                if (instance != null) instance.m_poolAcquired = false;
            }
            s_poolSize = poolSize;
            s_poolInstances = new SupportedLanguage[poolSize];
            s_poolNumAcquired = 0;
        }

        // 0x06000044; original ARM64 0x19dd348 (encodedLength).
        public int encodedLength()
        {
            int length = 0;
            if (m_language != 0) length = unchecked(NetworkBuffer.varInt32Length(m_language) + 1);
            if (m_localisedName != 0) length = unchecked(length + NetworkBuffer.varInt32Length(m_localisedName) + 1);
            if (m_isRTL) length = unchecked(length + 1);
            return length;
        }

        // 0x06000045; original ARM64 0x19dd3a8 (encode).
        public byte[] encode()
        {
            int length = encodedLength();
            byte[] data = new byte[length];
            NetworkBuffer buffer = new NetworkBuffer(data, 0, length);
            encode(ref buffer, length);
            return data;
        }

        // 0x06000046; original ARM64 0x19dd568 (encode).
        public void encode(ref NetworkBuffer buffer) => encode(ref buffer, encodedLength());

        // 0x06000047; original ARM64 0x19dd48c (encode).
        private void encode(ref NetworkBuffer buffer, int length)
        {
            int start = buffer.Offset;
            if (m_language != 0) { buffer.writeInt32(0); buffer.writeInt32(m_language); }
            if (m_localisedName != 0) { buffer.writeInt32(1); buffer.writeInt32(m_localisedName); }
            if (m_isRTL) buffer.writeInt32(2);
            if (buffer.Offset != unchecked(start + length)) throw new IndexOutOfRangeException();
        }

        // 0x06000048; original ARM64 0x19dd5dc (decode).
        public static SupportedLanguage decode(byte[] data)
        {
            NetworkBuffer buffer = new NetworkBuffer(data, 0, data.Length);
            return decode(ref buffer);
        }

        // 0x06000049; original ARM64 0x19dd734 (decode).
        public static SupportedLanguage decode(byte[] data, int offset, int length)
        {
            NetworkBuffer buffer = new NetworkBuffer(data, offset, length);
            return decode(ref buffer);
        }

        // 0x0600004a; original ARM64 0x19dd824 (decode).
        public static SupportedLanguage decode(ref NetworkBuffer buffer, int length)
        {
            NetworkBuffer child = buffer.SubRange(buffer.Offset, length);
            buffer.skip(length);
            return decode(ref child);
        }

        // 0x0600004b; original ARM64 0x19dd6bc (decode).
        public static SupportedLanguage decode(ref NetworkBuffer buffer)
        {
            SupportedLanguage instance = new SupportedLanguage();
            instance.decodeInto(ref buffer);
            return instance;
        }

        // 0x0600004c; original ARM64 0x19dd920 (decodeInto).
        public void decodeInto(ref NetworkBuffer buffer)
        {
            int previousTag = int.MinValue;
            while (buffer.Remaining > 0)
            {
                int tag = buffer.readVarInt32();
                if (tag < previousTag) throw new IndexOutOfRangeException();
                previousTag = tag;
                switch (tag)
                {
                    case 0: m_language = buffer.readInt32(); break;
                    case 1: m_localisedName = buffer.readInt32(); break;
                    case 2: m_isRTL = true; break;
                    default:
                        if (tag <= 1) throw new IndexOutOfRangeException();
                        buffer.skip(buffer.Remaining);
                        break;
                }
            }
        }

        // 0x0600004d; original ARM64 0x19dda3c (.cctor).
        // BeforeFieldInit static initializer is emitted from the ordered field initializers above.
    }
}
