using System;
using System.Reflection;
using Hardlight;
using HardlightProject;
namespace ProjectLucid
{
    // Original Actor static-key registry, not an Actor/controller or gameplay fixture.
    public static class ActorFSMKeyVerification
    {
        private static readonly string[] FieldNames = { "AbilitiesInUse",
            "AbilityHeading",
            "StateRemainTimer",
            "IsCollectingOrb",
            "OutroSequenceType",
            "SkipLevelEnter",
            "IsEnteringLevel",
            "IsExitingLevel",
            "SwapInIsInProgress",
            "SwapOutIsInProgress",
            "InterruptDyingState",
            "FullscreenEffectDictionary",
            "SwitchAvailableOverrideHandle",
            "AbilityDefinitionOverride",
            "StaminaUIDisabled",
            "FormLockedOverrideHandle",
            "SpeedLockCanBeExceeded",
            "ActiveAnimationLookup",
            "BoostSwitchStamina",
            "BoostSwitchRatio",
            "BoostSwitchAbility",
            "AirProjectedBufferDisabled",
            "AirProjectedBufferTimer",
            "AirDecelerationDisabled",
            "AirControlsLockTimeEnd",
            "AirAbilitiesReset",
            "AirAbilityActive",
            "AirAbilityBlendVelocity",
            "AirAbilityBlendGravity",
            "AirAbilityDirectionOverrideAnimationElapsedSeconds",
            "AirAbilityInterruptTimer",
            "AirAbilityElapsedTime",
            "AirAbilityActiveCount",
            "AirLedgeBufferTimer",
            "AirLedgeBufferFromRail",
            "LastRespawnPoint",
            "IsOutOfBounds",
            "InHardFailureState",
            "TriggerDyingState",
            "InDyingStateTime",
            "RespawnTeleportRequired",
            "RespawnTeleportToAir",
            "RespawnEffectsComplete",
            "RespawnRetainVelocity",
            "RespawnInvulnerableDuration",
            "RespawnAnimationPlaying",
            "ShieldDamageHitPoints",
            "JumpElapsedTime",
            "IsJumping",
            "JumpDirection",
            "JumpingExitedGround",
            "JumpAngleExtra",
            "JumpOnRailTracker",
            "JumpOnRailCanTurnAround",
            "JumpOnRailMagnetism",
            "JumpOnRailDistanceMax",
            "JumpOnRailAngleCosineMax",
            "JumpDecelerationDisabled",
            "CanQueueJump",
            "CanQueueBoost",
            "JumpFaceVelocityDirection",
            "TurnInputInverted",
            "TurnTrackerActive",
            "TurnCameraActive",
            "TurnCameraRotation",
            "TurnCameraStickyControls",
            "TurnCameraInput",
            "TurnCameraInputRelative",
            "GroundGripMotion",
            "GroundGripTime",
            "GroundGripValue",
            "GroundGripRestoreTimer",
            "GroundBoostRestoreTimer",
            "HomingTargetType",
            "HomingTargetTime",
            "HomingTargetInnerVolumeOnly",
            "HomingAttackActionTimestamp",
            "HomingAttackOneShotActive",
            "HomingRailSwitchObject",
            "HomingRailSwitchSpeed",
            "RailActive",
            "RailActiveLastTime",
            "RailSwitchNeighbour",
            "RailSwitchTimeElapsed",
            "RailSwitchStartPosition",
            "RailSwitchStartVelocity",
            "RailSwitchResumeSpeed",
            "RailIsValid",
            "RailTransferYVelocity",
            "RailTurnAroundInProgress",
            "RailTurnAroundCooldown",
            "RailAutoAttach",
            "RailTargetTime",
            "RailTargetCancelled",
            "RailToCamera",
            "TransporterActive",
            "TransporterIsValid",
            "TransporterAutoAttach",
            "RollingActive",
            "GravityDisabledModifierHandle",
            "GravityMultiplierModifierHandle",
            "ClimbingEdgePassed",
            "ClimbingNonMountableEdgeNormal",
            "ClimbingLastKnownPosition",
            "ClimbingLastKnownRotation",
            "ClimbingLastCollider",
            "ClimbingEnterWhenDirectionOverrideEnds",
            "ClimbingMaintainCurrentVelocityOnEnter",
            "ClimbingWorldVelocityAtTerrainEnter",
            "ClimbingEnterCollisionNormal",
            "ClimbingInvalid",
            "ClimbingLastTimestamp",
            "LedgeMountTimeElapsed",
            "LedgeMountFinished",
            "HalfPipeColliderActive",
            "HalfPipeColliderUpdate",
            "HalfPipeColliderPosition",
            "HalfPipeColliderNormal",
            "HalfPipeColliderSpeedForward",
            "HalfPipeColliderEntrySide",
            "HalfPipeGravityOnEnter",
            "HalfPipeAirMotionIndex",
            "HalfPipeAirMotionNormal",
            "HalfPipeAirLeaveTime",
            "HalfPipeTransferActive",
            "HalfPipeTransferNormalStart",
            "HalfPipeTransferRotationTime",
            "GroundInputDirection",
            "GroundCameraSettingsSet",
            "GroundLandingSpeed",
            "GroundLandingTime",
            "GroundLedgePosition",
            "GroundLedgeTime",
            "FreeLookHeadingOverrideHandle",
            "CameraProxySettingHandle",
            "CameraHeadingOverrideDisabled",
            "HoverHeadingDirection",
            "HoverDampingVelocity",
            "IsIdle",
            "InputOverrideModifierHandle",
            "EnemyDeadTimer",
            "EnemyFireProjectileTurnComplete",
            "EnemyFireProjectileWindUpComplete",
            "LightspeedDashTarget",
            "LightspeedDashInvulnerable",
            "BurstAttackDurationTimer",
            "CatchReleaseActive",
            "ChaosControlActive",
            "OneShotCanTriggerJump",
            "OneShotCanTriggerBoost",
            "SpinDashChargeTime" };
        private static readonly string[] NativeLiterals = { "AbilitiesInUse",
            "AbilityHeading",
            "StateRemainTimer",
            "IsCollectingOrb",
            "OutroSequenceType",
            "SkipLevelEnter",
            "IsEnteringLevel",
            "IsExitingLevel",
            "SwapInIsInProgress",
            "SwapOutIsInProgress",
            "InterruptDyingState",
            "FullscreenEffectDictionary",
            "SwitchAvailableOverrideHandle",
            "AbilityDefinitionOverride",
            "StaminaUIDisabled",
            "FormLockedOverrideHandle",
            "SpeedLockCanBeExceeded",
            "ActiveAnimationLookup",
            "BoostSwitchStamina",
            "BoostSwitchRatio",
            "BoostSwitchAbility",
            "AirProjectedBufferDisabled",
            "AirProjectedBufferTimer",
            "AirDecelerationDisabled",
            "AirControlsLockTimeEnd",
            "AirAbilitiesReset",
            "AirAbilityActive",
            "AirAbilityBlendVelocity",
            "AirAbilityBlendGravity",
            "AirAbilityDirectionOverrideAnimationElapsedSeconds",
            "AirAbilityInterruptTimer",
            "AirAbilityElapsedTime",
            "AirAbilityActiveCount",
            "AirLedgeBufferTimer",
            "AirLedgeBufferFromRail",
            "LastRespawnPoint",
            "IsOutOfBounds",
            "InHardFailureState",
            "TriggerDyingState",
            "InDyingStateTime",
            "RespawnTeleportRequired",
            "RespawnTeleportToAir",
            "RespawnEffectsComplete",
            "RespawnRetainVelocity",
            "RespawnInvulnerableDuration",
            "RespawnAnimationPlaying",
            "ShieldDamageHitPoints",
            "JumpElapsedTime",
            "IsJumping",
            "JumpDirection",
            "JumpingExitedGround",
            "JumpAngleExtra",
            "JumpOnRailTracker",
            "JumpOnRailCanTurnAround",
            "JumpOnRailMagnetism",
            "JumpOnRailDistanceMax",
            "JumpOnRailAngleCosineMax",
            "JumpDecelerationDisabled",
            "CanQueueJump",
            "CanQueueBoost",
            "JumpFaceVelocityDirection",
            "TurnInputInverted",
            "TurnTrackerActive",
            "TurnCameraActive",
            "TurnCameraRotation",
            "TurnCameraStickyControls",
            "TurnCameraInput",
            "TurnCameraInputRelative",
            "GroundGripMotion",
            "GroundGripTime",
            "GroundGripValue",
            "GroundGripRestoreTimer",
            "GroundBoostRestoreTimer",
            "HomingTargetType",
            "HomingTargetTime",
            "HomingTargetInnerVolumeOnly",
            "HomingAttackActionTimestamp",
            "HomingAttackOneShotActive",
            "HomingRailSwitchObject",
            "HomingRailSwitchSpeed",
            "RailActive",
            "RailActiveLastTime",
            "RailSwitchNeighbour",
            "RailSwitchTimeElapsed",
            "RailSwitchStartPosition",
            "RailSwitchStartVelocity",
            "RailSwitchResumeSpeed",
            "RailIsValid",
            "RailTransferYVelocity",
            "RailTurnAroundInProgress",
            "RailTurnAroundCooldown",
            "RailAutoAttach",
            "RailTargetTime",
            "RailTargetCancelled",
            "RailToCamera",
            "TransporterActive",
            "RailIsValid",
            "TransporterAutoAttach",
            "RollingActive",
            "GravityDisabledModifierHandle",
            "GravityMultiplierModifierHandle",
            "ClimbingEdgePassed",
            "ClimbingNonMountableEdgeNormal",
            "ClimbingLastKnownPosition",
            "ClimbingLastKnownRotation",
            "ClimbingLastCollider",
            "ClimbingEnterWhenDirectionOverrideEnds",
            "ClimbingMaintainCurrentVelocityOnEnter",
            "ClimbingWorldVelocityAtTerrainEnter",
            "ClimbingEnterCollisionNormal",
            "ClimbingInvalid",
            "ClimbingLastTimestamp",
            "LedgeMountTimeElapsed",
            "LedgeMountFinished",
            "HalfPipeColliderActive",
            "HalfPipeColliderUpdate",
            "HalfPipeColliderPosition",
            "HalfPipeColliderNormal",
            "HalfPipeColliderSpeedForward",
            "HalfPipeColliderEntrySide",
            "HalfPipeGravityOnEnter",
            "HalfPipeAirMotionIndex",
            "HalfPipeAirMotionNormal",
            "HalfPipeAirLeaveTime",
            "HalfPipeTransferActive",
            "HalfPipeTransferNormalStart",
            "HalfPipeTransferRotationTime",
            "GroundInputDirection",
            "GroundCameraSettingsSet",
            "GroundLandingSpeed",
            "GroundLandingTime",
            "GroundLedgePosition",
            "GroundLedgeTime",
            "FreeLookHeadingOverrideHandle",
            "CameraProxySettingHandle",
            "CameraHeadingOverrideDisabled",
            "HoverHeadingDirection",
            "HoverDampingVelocity",
            "IsIdle",
            "InputOverrideModifierHandle",
            "EnemyDeadTimer",
            "EnemyFireProjectileTurnComplete",
            "EnemyFireProjectileWindUpComplete",
            "LightspeedDashTarget",
            "LightspeedDashInvulnerable",
            "BurstAttackDurationTimer",
            "CatchReleaseActive",
            "ChaosControlActive",
            "OneShotCanTriggerJump",
            "OneShotCanTriggerBoost",
            "SpinDashChargeTime" };
        // Independent CRC32 values for exact original ASCII strings, retaining the original missing XOR-out.
        private static readonly int[] NativeNameIds = { -1242669405, 279921463, 1107892414, -202115333, -33025985, 933955119, 1491024364, 920450870, -1430983741, -752147185, 447888426, -1743977434, -51618727, -858789791, 147929724, -1998255108, 988831392, 1515065593, -24658978, -562149845, -255551082, 1416691327, 882041788, 13387631, 1708502640, -1218240785, -1267374683, -1799124959, 553798010, -686935455, -805905078, 1924515244, -459912533, -346637324, 135774025, 649496367, -154887470, 837225254, -2124975285, -811790027, 1269722534, 1675641199, 199317841, 1923479138, -616960253, 78884544, -1290931282, 182723614, -1749078234, -66346739, 472909988, 868919774, 1682300975, -472524211, -268914804, -702073299, 837349822, 1206458933, -380855725, -2103541146, -1047041161, 1521732251, 702453419, 527244176, 364659006, -600963334, 2062743815, -501957495, -259332432, -1410422871, 1712153557, 1014693507, 559691540, 1343414454, -1286066214, -1901899778, -840871581, -542332331, 1823282334, 1639531561, -1806790259, -1398782277, 753602308, -228132571, -1275132216, 1259025556, 4286775, 717907344, -739427668, -503901658, 488449916, 578701763, 897302375, 1540998522, 1937072721, 1248658602, 717907344, 998321389, -733050955, 1741361508, -445301869, -2025205064, -2123471365, -946049140, -1463020664, 1672297648, 1118926083, -383452337, -733793102, -196801195, -1466686979, -1532269263, -2063926858, -226319133, -1412138237, 2028974713, 1832005890, -1051725851, -541955292, -862698000, -1395121328, -268280492, -386510040, 1407645842, -2093372797, -1929626734, -1302327891, 1830163229, -1446016282, 456667710, 2137943935, 1281731986, 1216743086, -942771974, -1367026660, 1485362729, 1195662515, -1434825983, -2058724656, 1700243160, -163293195, 492235056, 455659060, 869032590, 1828667922, 2018907207, 572664398, -1947060140, 959957519, -527178519, -1535287332 };
        private static void Require(bool value, ref int checks, string message)
        { ++checks; if (!value) throw new InvalidOperationException(message); }
        public static int RunManaged()
        {
            int checks = 0;
            Type type = typeof(ActorFSMKeys);
            Require(type.FullName == "HardlightProject.ActorFSMKeys", ref checks, "original type");
            FieldInfo[] fields = type.GetFields(BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly);
            Require(fields.Length == 151, ref checks, "complete original field inventory");
            Require(type.IsPublic && type.IsAbstract && type.IsSealed &&
                (type.Attributes & TypeAttributes.BeforeFieldInit) != 0, ref checks, "original static/BFI type flags");
            Require(type.TypeInitializer != null && type.TypeInitializer.IsPrivate && type.TypeInitializer.IsStatic &&
                type.TypeInitializer.GetParameters().Length == 0, ref checks, "one genuine static initializer");
            for (int i = 0; i < fields.Length; ++i)
            {
                FieldInfo field = fields[i];
                Require(field.Name == FieldNames[i], ref checks, "original field order " + i);
                Require(field.FieldType == typeof(GraphStorageKey), ref checks, "key type " + i);
                Require(field.IsPublic && field.IsStatic && field.IsInitOnly, ref checks, "field flags " + i);
                GraphStorageKey key = (GraphStorageKey)field.GetValue(null);
                Require(key.GraphId == 0, ref checks, "default graph " + i);
                Require(key.NodeId == 0, ref checks, "default node " + i);
                Require(key.NameId == NativeNameIds[i], ref checks, "native literal CRC " + i);
                Require(GraphNameLookup.LookupNameUsingId(key.NameId) == NativeLiterals[i], ref checks, "native literal lookup " + i);
                Require(key.ToString() == "null_null_" + NativeLiterals[i], ref checks, "full key presentation " + i);
            }
            // The supplied release intentionally assigns the same RailIsValid name
            // to TransporterIsValid. Preserve the actual authored storage alias.
            Require(ActorFSMKeys.TransporterIsValid.Equals(ActorFSMKeys.RailIsValid), ref checks, "original transporter/rail alias");
            Require(ActorFSMKeys.TransporterIsValid.GetHashCode() == ActorFSMKeys.RailIsValid.GetHashCode(), ref checks, "alias hash");
            Require(!ActorFSMKeys.TransporterIsValid.Equals(ActorFSMKeys.AbilitiesInUse), ref checks, "unrelated key remains distinct");
            var storage = new FSMStorage(0);
            storage.SetValue(ActorFSMKeys.TransporterIsValid, 123);
            Require(storage.GetValue<int>(ActorFSMKeys.RailIsValid) == 123, ref checks, "real FSM alias read");
            storage.SetValue(ActorFSMKeys.RailIsValid, 456);
            Require(storage.GetValue<int>(ActorFSMKeys.TransporterIsValid) == 456, ref checks, "real FSM alias overwrite");
            return checks;
        }
        public static int Run() => RunManaged();
    }
}
