using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.ExceptionServices;
using Hardlight;
using HardlightProject;
using UnityEngine;

namespace ProjectLucid.Verification
{
    public static partial class CameraInputDisablerVerification
    {
        const BindingFlags Declared = BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly;
        static void Require(bool condition, string message) { if (!condition) throw new InvalidOperationException("Original camera/disabler fixture: " + message); }
        static FieldInfo Field(Type owner, string name, Type type, int flags)
        { FieldInfo field = owner.GetField(name, Declared); Require(field != null && field.DeclaringType == owner && field.FieldType == type && (int)field.Attributes == flags, "exact field " + owner.FullName + "." + name); return field; }
        static MethodInfo Method(Type owner, string name, Type result, int flags, params Type[] args)
        { MethodInfo method = owner.GetMethod(name, Declared, null, args, null); Require(method != null && method.DeclaringType == owner && method.ReturnType == result && (int)method.Attributes == flags && !method.IsGenericMethod, "exact method " + owner.FullName + "." + name); return method; }
        static Action<T> Camera<T>(CameraInputBrain brain, string name)
        { return (Action<T>)Delegate.CreateDelegate(typeof(Action<T>), brain, Method(typeof(CameraInputBrain), name, typeof(void), 129, typeof(T))); }
        static void Invoke(MethodInfo method, object target)
        { try { method.Invoke(target, null); } catch (TargetInvocationException e) { if (e.InnerException == null) throw; ExceptionDispatchInfo.Capture(e.InnerException).Throw(); throw; } }
        static void Fault<T>(Action action) where T : Exception
        { try { action(); } catch (Exception e) { Require(e.GetType() == typeof(T), "exact fault kind"); return; } throw new InvalidOperationException("Expected original fault"); }
        static void SameFault(Action action, Exception sentinel)
        { try { action(); } catch (Exception e) { Require(ReferenceEquals(e, sentinel), "original callback exception identity"); return; } throw new InvalidOperationException("Expected owned callback fault"); }
        // Every cleanup runs independently, including when acquisition or an assertion fails.
        static void Finish(Action body, params Action[] cleanup)
        { var failures = new List<Exception>(); try { body(); } catch (Exception e) { failures.Add(e); } foreach (Action action in cleanup) try { action(); } catch (Exception e) { failures.Add(e); } if (failures.Count == 1) ExceptionDispatchInfo.Capture(failures[0]).Throw(); if (failures.Count > 1) throw new AggregateException(failures); }
        static void Destroy(UnityEngine.Object value) { if (!ReferenceEquals(value, null)) UnityEngine.Object.DestroyImmediate(value); }
        static void Dispose(IDisposable value) { if (value != null) value.Dispose(); }
        static void Prepare()
        {
            CheckCompleteCurrentDeclarationsAndBodies();
            Require(typeof(CameraInputBrain).Assembly.GetName().Name == "Game.Runtime" && typeof(GameInputDisabler).Assembly == typeof(CameraInputBrain).Assembly && typeof(InputSystem).Assembly == typeof(CameraInputBrain).Assembly && typeof(ControlMapping).Assembly.GetName().Name == "HLInput.Runtime" && typeof(InputDebounce).Assembly == typeof(ControlMapping).Assembly && typeof(ProcessManager).Assembly.GetName().Name == "HLUnityCore.Runtime" && typeof(StackableData).Assembly == typeof(ProcessManager).Assembly && typeof(GameInput).Assembly.GetName().Name == "HLAutoGenerated", "genuine current provider assemblies");
        }
        static FieldInfo MovementField() { return Field(typeof(CameraInputBrain), "m_controllerMovement", typeof(Vector2), 1); }
        static Vector2 Movement(CameraInputBrain brain) { return (Vector2)MovementField().GetValue(brain); }
        static void Axes(CameraInputBrain brain, float x, float y) { Vector2 value = Movement(brain); Require(value.x.Equals(x) && value.y.Equals(y), "exact retained/published axes"); }
        static FieldInfo RequestedField() { return Field(typeof(CameraInputBrain), "m_movementDebounceRequested", typeof(bool), 1); }
        static FieldInfo HorizontalField() { return Field(typeof(CameraInputBrain), "m_movementDebounceHorizontal", typeof(InputDebounce), 1); }
        static FieldInfo VerticalField() { return Field(typeof(CameraInputBrain), "m_movementDebounceVertical", typeof(InputDebounce), 1); }
        static InputDebounce Horizontal(CameraInputBrain brain) { return (InputDebounce)HorizontalField().GetValue(brain); }
        static InputDebounce Vertical(CameraInputBrain brain) { return (InputDebounce)VerticalField().GetValue(brain); }
        static bool Requested(CameraInputBrain brain) { return (bool)RequestedField().GetValue(brain); }
        static Action DeferredOriginalCapture(CameraInputBrain brain, Vector2 thresholds, Vector2 timers)
        {
            Type closure = typeof(CameraInputBrain).GetNestedType("<>c__DisplayClass20_0", Declared); Require(closure != null, "complete original generated closure");
            object target = Activator.CreateInstance(closure, true); // Its real constructor; no uninitialized object allocation.
            FieldInfo owner = Field(closure, "<>4__this", typeof(CameraInputBrain), 6), first = Field(closure, "movementThresholds", typeof(Vector2), 6), second = Field(closure, "movementTimers", typeof(Vector2), 6);
            Require(owner.GetValue(target) == null && ((Vector2)first.GetValue(target)).Equals(default(Vector2)) && ((Vector2)second.GetValue(target)).Equals(default(Vector2)), "original capture constructor defaults");
            owner.SetValue(target, brain); first.SetValue(target, thresholds); second.SetValue(target, timers);
            return (Action)Delegate.CreateDelegate(typeof(Action), target, Method(closure, "<SubscribeMovementSecondary>b__0", typeof(void), 131));
        }
        public static int VerifyCameraAxesAndSnapCallbacks()
        {
            Prepare(); var brain = new CameraInputBrain(); Require(brain.Enabled && !brain.MaintainHeading && !brain.SecondaryEnabled && !Requested(brain) && Horizontal(brain) == null && Vertical(brain) == null && brain.OnSnapButtonPressed == null && brain.OnSnapButtonReleased == null, "whole original constructor defaults"); Axes(brain, 0f, 0f);
            var composite = Camera<Vector2>(brain, "RegisterCompositeMovement"); composite(new Vector2(0.5f, -0.75f)); Axes(brain, 0.5f, -0.75f);
            composite(new Vector2(0.0001f, float.NaN)); Axes(brain, 0.5f, -0.75f); composite(new Vector2(-0.9f, 0f)); Axes(brain, -0.9f, -0.75f);
            brain.Enabled = false; composite(new Vector2(0.8f, 0.8f)); Axes(brain, -0.9f, -0.75f); Camera<float>(brain, "AddCameraLeftMovement")(1f); Axes(brain, -0.9f, -0.75f);
            int pressed = 0, released = 0; brain.OnSnapButtonPressed = () => pressed++; brain.OnSnapButtonReleased = (first, second) => { Require(first && !second, "original snap release true/false arguments"); released++; };
            Camera<float>(brain, "SnapBehindTargetPressed")(float.NaN); Camera<float>(brain, "SnapBehindTargetRelease")(0f); Require(pressed == 1 && released == 1, "disabled camera still invokes snap callbacks");
            Camera<float>(brain, "MaintainHeadingPressed")(0f); Require(brain.MaintainHeading, "heading pressed has no movement gate"); Camera<float>(brain, "MaintainHeadingRelease")(float.NaN); Require(!brain.MaintainHeading, "heading release ignores input value");
            brain.OnSnapButtonPressed = null; brain.OnSnapButtonReleased = null; Camera<float>(brain, "SnapBehindTargetPressed")(1f); Camera<float>(brain, "SnapBehindTargetRelease")(1f);
            brain.Enabled = true; Camera<float>(brain, "AddCameraLeftMovement")(-0.4f); Camera<float>(brain, "AddCameraRightMovement")(0.6f); Camera<float>(brain, "AddCameraDownMovement")(0.3f); Camera<float>(brain, "AddCameraUpMovement")(-0.7f); Axes(brain, 0.6f, -0.7f);
            Camera<float>(brain, "AddCameraLeftMovementSecondary")(0.4f); Camera<float>(brain, "AddCameraDownMovementSecondary")(0.6f); Axes(brain, -0.4f, -0.6f); Require(!brain.SecondaryEnabled, "secondary callbacks do not require subscriptions enabled");
            Camera<float>(brain, "AddCameraRightMovementSecondary")(0.7f); Camera<float>(brain, "AddCameraUpMovementSecondary")(0.8f); Axes(brain, 0.7f, 0.8f);
            Vector2 before = brain.GetAndClearMovement(); Require(before.x == 0.7f && before.y == 0.8f, "capture axes before zero clear"); Axes(brain, 0f, 0f); var snapFault = new InvalidOperationException("Owned original snap fault"); brain.OnSnapButtonReleased = (first, second) => { Require(first && !second, "faulting release retains arguments"); throw snapFault; }; SameFault(() => Camera<float>(brain, "SnapBehindTargetRelease")(1f), snapFault); return 15;
        }
        public static int VerifyOriginalDeferredDebounceBodyAndFaultOrder()
        {
            Prepare(); var brain = new CameraInputBrain(); SubscriptionCustody custody = null, faultingCustody = null; int checks = 0;
            Finish(() =>
            {
            custody = new SubscriptionCustody(brain); Action callback = DeferredOriginalCapture(brain, new Vector2(0.2f, 0.3f), new Vector2(0.5f, 0.75f)); callback();
            InputDebounce h = Horizontal(brain), v = Vertical(brain); Require(Requested(brain) && h != null && v != null && !ReferenceEquals(h, v) && h.Input == 0f && v.Input == 0f, "real capture publishes request and distinct real debounce objects");
            Camera<Vector2>(brain, "RegisterCompositeMovement")(new Vector2(0.6f, -0.7f)); brain.Update(10f); Require(!Requested(brain) && ReferenceEquals(h, Horizontal(brain)) && ReferenceEquals(v, Vertical(brain)) && h.Input == 0.6f && v.Input == -0.7f && !h.TimeExceeded && !v.TimeExceeded, "requested frame seeds both providers and skips time advancement"); Axes(brain, 0.6f, -0.7f);
            brain.Update(0.5f); Axes(brain, 0f, 0f); Require(ReferenceEquals(h, Horizontal(brain)) && h.TimeExceeded && !h.TimeExceededContinuous, "equality pulse retains horizontal debounce and suppresses axis");
            Camera<Vector2>(brain, "RegisterCompositeMovement")(new Vector2(0.6f, -0.7f)); brain.Update(0.25f); Require(Horizontal(brain) == null && ReferenceEquals(v, Vertical(brain)) && v.TimeExceeded && !v.TimeExceededContinuous, "strict greater-than expiry differs from pulse equality"); Axes(brain, 0.6f, 0f);
            Camera<Vector2>(brain, "RegisterCompositeMovement")(new Vector2(0.6f, -0.7f)); brain.Update(0.01f); Require(Vertical(brain) == null, "vertical real provider expires after equality"); Axes(brain, 0.6f, -0.7f);
            callback(); custody.Mutate(brain.UnsubscribeMovementSecondary); Require(!Requested(brain) && Horizontal(brain) == null && Vertical(brain) == null && !brain.SecondaryEnabled, "unsubscribe clears before return"); callback(); Require(Requested(brain) && Horizontal(brain) != null && Vertical(brain) != null && !brain.SecondaryEnabled, "already deferred callback has no unsubscribe cancellation guard");
            brain.GetAndClearMovement(); brain.Update(10f); brain.Update(0.1f); Require(Horizontal(brain) == null && Vertical(brain) == null, "zero input drops both real below-threshold providers");
            var faulting = new CameraInputBrain(); faultingCustody = new SubscriptionCustody(faulting); Action nullOwner = DeferredOriginalCapture(null, Vector2.one, Vector2.one); Fault<NullReferenceException>(nullOwner);
            h = new InputDebounce(0.2f, 1f, 0f); HorizontalField().SetValue(faulting, h); RequestedField().SetValue(faulting, true); Camera<Vector2>(faulting, "RegisterCompositeMovement")(new Vector2(0.8f, 0.9f)); Fault<NullReferenceException>(() => faulting.Update(2f)); Require(Requested(faulting) && h.Input == 0.8f && h.ThresholdExceeded && Vertical(faulting) == null, "horizontal seed precedes vertical null fault; request clear skipped");
            faultingCustody.Mutate(faulting.UnsubscribeMovementSecondary); checks = 10;
            }, () => Dispose(faultingCustody), () => Dispose(custody)); return checks;
        }

        static readonly string[] ScalarMaps = { "s_onButtonsHeld", "s_onButtonsDown", "s_onButtonsUp", "s_onAxis", "s_onAxisStart", "s_onAxisEnd", "s_onSwipe", "s_onScrollWheel" };
        static readonly string[] VectorMaps = { "s_onPointer", "s_onTap", "s_onTouch", "s_onTouchRelease", "s_onMultiTouchRelease", "s_onVectorisedGameInput" };
        static IDictionary InputDictionary(string name)
        { FieldInfo field = typeof(ControlMapping).GetField(name, Declared); Require(field != null && (int)field.Attributes == 49 && field.FieldType.GetGenericTypeDefinition() == typeof(Dictionary<,>), "real readonly input dictionary container"); return (IDictionary)field.GetValue(null); }
        static object InputKey(IDictionary dictionary, GameInput input, int joystick)
        { Type type = dictionary.GetType().GetGenericArguments()[0]; object key = Activator.CreateInstance(type); Field(type, "GameInput", typeof(GameInput), 6).SetValue(key, input); Field(type, "JoystickIndex", typeof(int), 6).SetValue(key, joystick); return key; }
        static IList Callbacks(object action)
        { MethodInfo method = action.GetType().GetMethod("GetInvocationList", BindingFlags.Instance | BindingFlags.Public); Require(method != null, "genuine callback-list provider"); return (IList)method.Invoke(action, null); }
        // Shared providers may retain pending work after a failed invocation.
        // Read the genuine complete base fields; never drain or replace a list.
        sealed class FastActionState
        {
            readonly object action; readonly FieldInfo active; readonly FieldInfo[] fields; readonly IList[] lists; readonly object[][] contents; readonly bool wasActive;
            public FastActionState(object action, Type expectedType)
            {
                Require(action != null && action.GetType() == expectedType && expectedType.IsGenericType && expectedType.GetGenericTypeDefinition() == typeof(FastAction<>), "exact shared FastAction provider"); this.action = action;
                Type owner = expectedType.BaseType; Require(owner != null && owner.Assembly == typeof(ProcessManager).Assembly && expectedType.Assembly == owner.Assembly && owner.IsGenericType && owner.GetGenericTypeDefinition() == typeof(FastActionBase<,>) && owner.GetGenericArguments()[0] == expectedType, "complete genuine FastAction base owner");
                Type callback = typeof(Action<>).MakeGenericType(expectedType.GetGenericArguments()[0]); Require(owner.GetGenericArguments()[1] == callback && owner.GetFields(Declared).OrderBy(x => x.MetadataToken).Select(x => x.Name).SequenceEqual(new[] { "m_invocationList", "m_invocationActive", "m_removedList", "m_addedList" }), "exact full runtime FastAction fields including private queues");
                Type list = typeof(List<>).MakeGenericType(callback); fields = new[] { Field(owner, "m_invocationList", list, 36), Field(owner, "m_removedList", list, 33), Field(owner, "m_addedList", list, 33) }; active = Field(owner, "m_invocationActive", typeof(bool), 4);
                lists = fields.Select(field => (IList)field.GetValue(action)).ToArray(); Require(lists.All(value => value != null && value.GetType() == list), "genuine nonnull callback and queue lists");
                contents = lists.Select(value => value.Cast<object>().ToArray()).ToArray(); wasActive = (bool)active.GetValue(action); RequireIdle();
            }
            public void RequireIdle()
            {
                for (int i = 0; i < fields.Length; i++) Require(ReferenceEquals(fields[i].GetValue(action), lists[i]), "all three original list identities retained");
                Require(!wasActive && !(bool)active.GetValue(action) && lists[1].Count == 0 && lists[2].Count == 0, "shared action must be inactive with no pending removals or additions before mutation");
            }
            public void RequireEmpty() { RequireIdle(); Require(lists[0].Count == 0, "only an inactive empty owned generated action may be removed"); }
            public void RequireRestored()
            {
                RequireIdle(); Require((bool)active.GetValue(action) == wasActive, "original shared invocation flag restored");
                for (int i = 0; i < lists.Length; i++) { Require(lists[i].Count == contents[i].Length, "all three original ordered list counts restored"); for (int j = 0; j < contents[i].Length; j++) Require(ReferenceEquals(lists[i][j], contents[i][j]), "every original callback and pending-list entry retained in order"); }
            }
        }
        sealed class SubscriptionCustody : IDisposable
        {
            readonly CameraInputBrain brain; readonly IDictionary[] dictionaries; readonly DictionaryEntry[][] entries; readonly FastActionState[][] states;
            public SubscriptionCustody(CameraInputBrain brain)
            {
                this.brain = brain; dictionaries = ScalarMaps.Concat(VectorMaps).Select(InputDictionary).ToArray(); entries = dictionaries.Select(x => Entries(x)).ToArray();
                states = entries.Select((rows, index) => rows.Select(row => new FastActionState(row.Value, dictionaries[index].GetType().GetGenericArguments()[1])).ToArray()).ToArray();
                // The constructor has only observed shared fields. A rejection
                // occurs before any original subscribe/unsubscribe operation.
                for (int i = 0; i < dictionaries.Length; i++) { Require(dictionaries[i].Count == entries[i].Length, "unchanged dictionary during read-only acquisition"); for (int j = 0; j < entries[i].Length; j++) { DictionaryEntry old = entries[i][j]; Require(dictionaries[i].Contains(old.Key) && ReferenceEquals(dictionaries[i][old.Key], old.Value), "original key/action identity before mutation"); states[i][j].RequireRestored(); } }
            }
            public void Mutate(Action mutation)
            {
                string[] names = ScalarMaps.Concat(VectorMaps).ToArray();
                for (int i = 0; i < dictionaries.Length; i++)
                {
                    IDictionary dictionary = dictionaries[i]; Require(ReferenceEquals(InputDictionary(names[i]), dictionary), "original readonly dictionary identity before mutation");
                    for (int j = 0; j < entries[i].Length; j++) { DictionaryEntry old = entries[i][j]; Require(dictionary.Contains(old.Key) && ReferenceEquals(dictionary[old.Key], old.Value), "every borrowed shared action retained before mutation"); states[i][j].RequireIdle(); }
                    foreach (DictionaryEntry row in Entries(dictionary)) new FastActionState(row.Value, dictionary.GetType().GetGenericArguments()[1]).RequireIdle();
                }
                mutation();
            }
            public void Dispose()
            {
                var actions = new List<Action> { () => Mutate(brain.Shutdown), () => Mutate(brain.UnsubscribeMovementSecondary) };
                for (int i = 0; i < dictionaries.Length; i++)
                {
                    int index = i; actions.Add(() =>
                    {
                        IDictionary dictionary = dictionaries[index]; Require(ReferenceEquals(InputDictionary(ScalarMaps.Concat(VectorMaps).ElementAt(index)), dictionary), "original readonly dictionary identity during cleanup"); foreach (DictionaryEntry row in Entries(dictionary)) if (!entries[index].Any(old => Equals(old.Key, row.Key))) { new FastActionState(row.Value, dictionary.GetType().GetGenericArguments()[1]).RequireEmpty(); dictionary.Remove(row.Key); }
                        Require(dictionary.Count == entries[index].Length, "exact pre-fixture dictionary cardinality");
                        for (int j = 0; j < entries[index].Length; j++) { DictionaryEntry old = entries[index][j]; Require(dictionary.Contains(old.Key) && ReferenceEquals(dictionary[old.Key], old.Value), "every pre-existing key/action restored without dispatch"); states[index][j].RequireRestored(); }
                    });
                }
                Finish(() => { }, actions.ToArray());
            }
        }
        static Action<T>[] Owned<T>(string map, GameInput input, CameraInputBrain brain)
        { IDictionary dictionary = InputDictionary(map); object key = InputKey(dictionary, input, -1); Require(dictionary.Contains(key), "original subscription key"); return Callbacks(dictionary[key]).Cast<Action<T>>().Where(x => x != null && ReferenceEquals(x.Target, brain)).ToArray(); }
        static void Subscriber<T>(string map, GameInput input, CameraInputBrain brain, params string[] methods)
        { Action<T>[] callbacks = Owned<T>(map, input, brain); Require(callbacks.Length == methods.Length && callbacks.Select(x => x.Method.Name).SequenceEqual(methods), "ordered owned subscription callback identities"); }
        public static int VerifyOriginalCameraRegistrationAndShutdown()
        {
            Prepare(); var brain = new CameraInputBrain(); SubscriptionCustody custody = null; int checks = 0;
            Finish(() =>
            {
                custody = new SubscriptionCustody(brain); custody.Mutate(brain.Initialise); custody.Mutate(brain.Initialise);
                GameInput[] inputs = { GameInput.CameraLeft, GameInput.CameraRight, GameInput.CameraUp, GameInput.CameraDown }; string[] names = { "AddCameraLeftMovement", "AddCameraRightMovement", "AddCameraUpMovement", "AddCameraDownMovement" };
                for (int i = 0; i < inputs.Length; i++) foreach (string map in new[] { "s_onButtonsHeld", "s_onAxis", "s_onSwipe", "s_onScrollWheel" }) { Subscriber<float>(map, inputs[i], brain, names[i]); checks++; }
                foreach (string map in VectorMaps) { Subscriber<Vector2>(map, GameInput.CameraMovementComposite, brain, "RegisterCompositeMovement"); checks++; }
                Subscriber<float>("s_onButtonsDown", GameInput.CameraSnapBehindTarget, brain, "SnapBehindTargetPressed"); Subscriber<float>("s_onButtonsUp", GameInput.CameraSnapBehindTarget, brain, "SnapBehindTargetRelease"); Subscriber<float>("s_onAxisStart", GameInput.CameraSnapBehindTarget, brain, "SnapBehindTargetPressed"); Subscriber<float>("s_onAxisEnd", GameInput.CameraSnapBehindTarget, brain, "SnapBehindTargetRelease");
                foreach (string map in new[] { "s_onSwipe", "s_onScrollWheel" }) Subscriber<float>(map, GameInput.CameraSnapBehindTarget, brain, "SnapBehindTargetPressed", "SnapBehindTargetRelease");
                Subscriber<float>("s_onButtonsDown", GameInput.CameraMaintainHeading, brain, "MaintainHeadingPressed"); Subscriber<float>("s_onButtonsUp", GameInput.CameraMaintainHeading, brain, "MaintainHeadingRelease"); Subscriber<float>("s_onAxisStart", GameInput.CameraMaintainHeading, brain, "MaintainHeadingPressed"); Subscriber<float>("s_onAxisEnd", GameInput.CameraMaintainHeading, brain, "MaintainHeadingRelease");
                foreach (string map in new[] { "s_onSwipe", "s_onScrollWheel" }) Subscriber<float>(map, GameInput.CameraMaintainHeading, brain, "MaintainHeadingPressed", "MaintainHeadingRelease"); checks += 12;
                // Execute only this brain's real typed delegate, never the shared FastAction invocation list.
                Owned<float>("s_onAxis", GameInput.CameraLeft, brain).Single()(0.6f); Axes(brain, 0.6f, 0f);
                custody.Mutate(brain.Shutdown); foreach (string map in ScalarMaps.Concat(VectorMaps)) foreach (DictionaryEntry row in InputDictionary(map)) Require(!Callbacks(row.Value).Cast<Delegate>().Any(x => x != null && ReferenceEquals(x.Target, brain)), "shutdown removes every owned callback"); checks++;
            }, () => Dispose(custody)); return checks;
        }
        static IDictionary Registry() { FieldInfo field = typeof(ProcessManager).GetField("s_systemDictionary", Declared); Require(field != null && (int)field.Attributes == 49, "original readonly registry container"); return (IDictionary)field.GetValue(null); }
        static DictionaryEntry[] Entries(IDictionary dictionary) { var rows = new List<DictionaryEntry>(); foreach (DictionaryEntry row in dictionary) rows.Add(row); return rows.ToArray(); }
        static IDictionary TypedCache(object info) { FieldInfo field = info.GetType().GetField("SystemRefDictionary", Declared); Require(field != null && (int)field.Attributes == 38, "original readonly typed cache container"); return (IDictionary)field.GetValue(info); }
        static SystemRef Untyped(object info) { return (SystemRef)Field(info.GetType(), "SystemRef", typeof(SystemRef), 38).GetValue(info); }
        static SystemRef<InputSystem> PrepareSystemReference()
        {
            IDictionary registry = Registry(); string name = typeof(InputSystem).ToString(); DictionaryEntry[] prior = Entries(registry); object old = registry.Contains(name) ? registry[name] : null; DictionaryEntry[] oldCache = old == null ? new DictionaryEntry[0] : Entries(TypedCache(old));
            SystemRef<InputSystem> reference = ProcessManager.GetSystemRef<InputSystem>(null, true);
            Require(reference != null && registry.Contains(name), "genuine first-use reference association"); foreach (DictionaryEntry row in prior) Require(registry.Contains(row.Key) && ReferenceEquals(registry[row.Key], row.Value), "all prior system rows preserved");
            Require(registry.Count == prior.Length + (old == null ? 1 : 0), "only original first-use row may be added"); object info = registry[name]; if (old != null) Require(ReferenceEquals(old, info), "original row retained"); IDictionary cache = TypedCache(info);
            foreach (DictionaryEntry row in oldCache) Require(cache.Contains(row.Key) && ReferenceEquals(cache[row.Key], row.Value), "prior typed references retained"); Require(cache.Contains(name) && ReferenceEquals(cache[name], reference), "real typed reference association"); return reference;
        }
        sealed class ReferenceLease : IDisposable
        {
            readonly object target; readonly FieldInfo[] fields; readonly object[] values;
            public ReferenceLease(object target)
            {
                this.target = target; Type owner = target.GetType(); while (owner != null && (!owner.IsGenericType || owner.GetGenericTypeDefinition() != typeof(SystemRef<>))) owner = owner.BaseType; Require(owner != null, "real SystemRef base"); Type argument = owner.GetGenericArguments()[0];
                string[] names = { "OnSystemStartup", "OnSystemShutdown", "m_actionOnSystemValid", "m_system", "m_isystem" }; Type[] types = { typeof(Action<>).MakeGenericType(argument), typeof(Action<>).MakeGenericType(argument), typeof(FastAction<>).MakeGenericType(argument), argument, typeof(ISystem) };
                fields = names.Select((name, index) => Field(owner, name, types[index], 1)).ToArray(); values = fields.Select(field => field.GetValue(target)).ToArray();
                try { foreach (FieldInfo field in fields) field.SetValue(target, null); } catch (Exception primary) { Finish(() => { ExceptionDispatchInfo.Capture(primary).Throw(); }, Dispose); throw; }
            }
            public void Dispose() { Finish(() => { }, fields.Select((field, index) => (Action)(() => { field.SetValue(target, values[index]); Require(ReferenceEquals(field.GetValue(target), values[index]), "each borrowed reference field restored"); })).ToArray()); }
        }
        sealed class RegistryLease : IDisposable
        {
            readonly IDictionary registry, cache; readonly string name; readonly object info; readonly DictionaryEntry[] rows, registryRows; readonly List<ReferenceLease> references = new List<ReferenceLease>();
            public readonly SystemRef<InputSystem> Typed;
            public RegistryLease(SystemRef<InputSystem> typed)
            {
                Typed = typed; name = typeof(InputSystem).ToString(); registry = Registry(); registryRows = Entries(registry); info = registry[name]; cache = TypedCache(info); rows = Entries(cache); var targets = new List<object> { Untyped(info) };
                foreach (DictionaryEntry row in rows) if (!targets.Any(x => ReferenceEquals(x, row.Value))) targets.Add(row.Value);
                try { foreach (object target in targets) references.Add(new ReferenceLease(target)); Identity(); Require(ReferenceEquals(typed.GetSafe(), null), "owned lease revokes borrowed mutable values without replacing cache"); } catch (Exception primary) { Finish(() => { ExceptionDispatchInfo.Capture(primary).Throw(); }, Dispose); throw; }
            }
            public void Identity()
            {
                Require(registry.Count == registryRows.Length && cache.Count == rows.Length && ReferenceEquals(registry[name], info) && ReferenceEquals(TypedCache(info), cache), "registry/cache cardinality and associations retained"); foreach (DictionaryEntry row in registryRows) Require(registry.Contains(row.Key) && ReferenceEquals(registry[row.Key], row.Value), "every registry row retained"); foreach (DictionaryEntry row in rows) Require(cache.Contains(row.Key) && ReferenceEquals(cache[row.Key], row.Value), "every typed-cache row retained");
            }
            public void Dispose() { Finish(() => { }, references.Select(x => (Action)x.Dispose).Concat(new Action[] { Identity }).ToArray()); }
        }
        static readonly GameInput OwnedA = (GameInput)(int.MinValue + 160), OwnedB = (GameInput)(int.MinValue + 161);
        static void NoSharedReleaseHandlers()
        {
            Require(!Enum.IsDefined(typeof(GameInput), OwnedA) && !Enum.IsDefined(typeof(GameInput), OwnedB), "distinctive owned enum values");
            foreach (string name in new[] { "s_onButtonsUp", "s_onAxisEnd" }) foreach (DictionaryEntry row in InputDictionary(name))
            { GameInput input = (GameInput)Field(row.Key.GetType(), "GameInput", typeof(GameInput), 6).GetValue(row.Key); Require(input != OwnedA && input != OwnedB, "owned disabler inputs have no unrelated release handlers"); }
        }
        sealed class OwnedDisabler : IDisposable
        {
            RegistryLease lease; GameObject owned; readonly List<Tuple<GameInput, Action<GameInput, bool>>> callbacks = new List<Tuple<GameInput, Action<GameInput, bool>>>();
            public GameInputDisabler Value; public InputSystem System; public ControlMapping Mapping;
            public List<StackableDataHandle> Handles { get { return (List<StackableDataHandle>)Field(typeof(GameInputDisabler), "m_stackableDataHandles", typeof(List<StackableDataHandle>), 33).GetValue(Value); } }
            public OwnedDisabler()
            {
                try
                {
                    NoSharedReleaseHandlers(); lease = new RegistryLease(PrepareSystemReference()); owned = new GameObject("Owned original game-input disabler fixture"); owned.SetActive(false); System = owned.AddComponent<InputSystem>(); Value = owned.AddComponent<GameInputDisabler>();
                    Require(!owned.activeInHierarchy && Value.enabled && Handles.Count == 0 && ReferenceEquals(Field(typeof(GameInputDisabler), "m_inputSystemRef", typeof(SystemRef<InputSystem>), 33).GetValue(Value), lease.Typed) && ReferenceEquals(lease.Typed.GetSafe(), null), "genuine inactive constructors/cache/defaults");
                    Require(Field(typeof(GameInputDisabler), "m_gameInputs", typeof(GameInput[]), 1).GetValue(Value) == null && !(bool)Field(typeof(GameInputDisabler), "m_activateOnEnable", typeof(bool), 1).GetValue(Value) && Field(typeof(GameInputDisabler), "m_controlMapping", typeof(ControlMapping), 1).GetValue(Value) == null, "original authored defaults");
                    Mapping = ScriptableObject.CreateInstance<ControlMapping>(); Mapping.InitialiseStackableData(); SetMapping(Mapping); Inputs(new[] { OwnedA, OwnedB });
                }
                catch (Exception primary) { Finish(() => { ExceptionDispatchInfo.Capture(primary).Throw(); }, Dispose); throw; }
            }
            public void Inputs(GameInput[] inputs) { Field(typeof(GameInputDisabler), "m_gameInputs", typeof(GameInput[]), 1).SetValue(Value, inputs); }
            public void SetMapping(ControlMapping mapping) { Field(typeof(GameInputDisabler), "m_controlMapping", typeof(ControlMapping), 1).SetValue(Value, mapping); }
            public void Subscribe(GameInput input, Action<GameInput, bool> action) { callbacks.Add(Tuple.Create(input, action)); Mapping.SubscribeInputDisabled(input, action, false); }
            public void UnsubscribeOwnedCallbacks() { Finish(() => { }, callbacks.Select(pair => (Action)(() => Mapping.UnsubscribeInputDisabled(pair.Item1, pair.Item2))).ToArray()); }
            public void OnEnable() { Invoke(Method(typeof(GameInputDisabler), "OnEnable", typeof(void), 129), Value); }
            public void PublishSystem()
            { Field(typeof(InputSystem), "m_controlMapping", typeof(ControlMapping), 1).SetValue(System, Mapping); Invoke(Method(typeof(InputSystem), "Awake", typeof(void), 129), System); lease.Identity(); }
            public void Dispose()
            {
                var cleanup = new List<Action>(); foreach (var pair in callbacks) { var capture = pair; cleanup.Add(() => { if (!ReferenceEquals(Mapping, null)) Mapping.UnsubscribeInputDisabled(capture.Item1, capture.Item2); }); }
                cleanup.Add(() => { if (!ReferenceEquals(Value, null)) SetMapping(null); }); cleanup.Add(() => { if (!ReferenceEquals(Value, null)) Value.Action_ReenableGameInputs(); });
                cleanup.Add(() => { if (!ReferenceEquals(System, null)) Invoke(Method(typeof(InputSystem), "OnDestroy", typeof(void), 129), System); }); cleanup.Add(() => Destroy(owned));
                cleanup.Add(() => { if (!ReferenceEquals(Mapping, null)) Mapping.ShutdownStackableData(); }); cleanup.Add(() => Destroy(Mapping)); cleanup.Add(() => CameraInputDisablerVerification.Dispose(lease)); Finish(() => { }, cleanup.ToArray());
            }
        }
        public static int VerifyDisablerGuardsAndOriginalEnableCallbacks()
        {
            Prepare(); OwnedDisabler owned = null; int checks = 0;
            Finish(() =>
            {
                owned = new OwnedDisabler(); owned.Inputs(null); owned.Value.enabled = false; owned.Value.Action_DisableGameInputs(); Require(owned.Handles.Count == 0, "disabled Behaviour guard precedes authored null array"); checks++;
                owned.Value.enabled = true; owned.SetMapping(null); owned.Value.Action_DisableGameInputs(); Require(owned.Handles.Count == 0, "Unity-null mapping guard precedes authored null array"); checks++;
                owned.SetMapping(owned.Mapping); owned.Handles.Add(new StackableDataHandle()); owned.Value.Action_DisableGameInputs(); Require(owned.Handles.Count == 1, "nonempty original list guard precedes null array"); owned.SetMapping(null); owned.Value.Action_ReenableGameInputs(); Require(owned.Handles.Count == 0, "null mapping releases list without provider calls"); checks++;
                owned.SetMapping(owned.Mapping); Fault<NullReferenceException>(owned.Value.Action_DisableGameInputs); Require(owned.Handles.Count == 0, "authored null array faults after all three guards"); checks++;
                owned.Inputs(new[] { OwnedA }); owned.OnEnable(); Require(Field(typeof(GameInputDisabler), "m_controlMapping", typeof(ControlMapping), 1).GetValue(owned.Value) == null && owned.Handles.Count == 0, "failed genuine TryGet publishes null before authored false guard"); checks++;
                owned.PublishSystem(); Field(typeof(GameInputDisabler), "m_activateOnEnable", typeof(bool), 1).SetValue(owned.Value, true); owned.OnEnable(); Require(owned.Handles.Count == 1 && owned.Mapping.IsGameInputDisabled(OwnedA), "real TryGet/getter publishes mapping before authored auto-disable"); checks++;
                Invoke(Method(typeof(GameInputDisabler), "OnDisable", typeof(void), 129), owned.Value); Require(owned.Handles.Count == 0 && !owned.Mapping.IsGameInputDisabled(OwnedA), "explicit original OnDisable releases");
                owned.Value.Action_DisableGameInputs(); Invoke(Method(typeof(GameInputDisabler), "OnDestroy", typeof(void), 129), owned.Value); Require(owned.Handles.Count == 0 && !owned.Mapping.IsGameInputDisabled(OwnedA), "explicit original OnDestroy releases"); checks += 2;
            }, () => Dispose(owned)); return checks;
        }
        public static int VerifyDisablerCapturedArrayAndPartialAddFault()
        {
            Prepare(); OwnedDisabler owned = null; int checks = 0;
            Finish(() =>
            {
                owned = new OwnedDisabler(); int first = 0, second = 0; var sentinel = new InvalidOperationException("Owned original add callback fault");
                owned.Subscribe(OwnedA, (input, disabled) => { Require(input == OwnedA, "owned first input"); if (disabled) { first++; Require(owned.Handles.Count == 0 && owned.Mapping.IsGameInputDisabled(OwnedA), "override published before first handle append"); owned.Inputs(new[] { OwnedA }); } });
                owned.Subscribe(OwnedB, (input, disabled) => { if (disabled) { second++; Require(owned.Handles.Count == 1 && owned.Mapping.IsGameInputDisabled(OwnedB), "second override published before throwing, first handle retained"); throw sentinel; } });
                SameFault(owned.Value.Action_DisableGameInputs, sentinel); Require(first == 1 && second == 1 && owned.Handles.Count == 1, "captured original two-element array survives authored field replacement and partial fault"); checks++;
                owned.Value.Action_DisableGameInputs(); Require(first == 1 && second == 1 && owned.Handles.Count == 1, "subsequent disable returns at retained partial list"); checks++;
                owned.Value.Action_ReenableGameInputs(); Require(owned.Handles.Count == 0 && !owned.Mapping.IsGameInputDisabled(OwnedA) && owned.Mapping.IsGameInputDisabled(OwnedB), "only returned first handle released; faulting override remains orphaned in owned data"); checks++;
            }, () => Dispose(owned)); return checks;
        }
        public static int VerifyDisablerReentrancyAndReleaseFaults()
        {
            Prepare(); OwnedDisabler owned = null; int checks = 0;
            Finish(() =>
            {
                owned = new OwnedDisabler(); owned.Inputs(new[] { OwnedA }); bool nested = false; int additions = 0;
                owned.Subscribe(OwnedA, (input, disabled) => { if (disabled) { additions++; Require(owned.Handles.Count == 0, "add callback precedes handle append"); if (!nested) { nested = true; owned.Value.Action_DisableGameInputs(); } } });
                owned.Value.Action_DisableGameInputs(); Require(additions == 2 && owned.Handles.Count == 2 && !ReferenceEquals(owned.Handles[0], owned.Handles[1]), "bounded reentrant disable appends inner handle before outer handle"); checks++;
                // Remove this owned callback through the genuine API before releasing the two overrides.
                owned.UnsubscribeOwnedCallbacks(); owned.Value.Action_ReenableGameInputs(); Require(owned.Handles.Count == 0 && !owned.Mapping.IsGameInputDisabled(OwnedA), "both real override handles released after reentrancy"); checks++;
            }, () => Dispose(owned));
            owned = null;
            Finish(() =>
            {
                owned = new OwnedDisabler(); owned.Value.Action_DisableGameInputs(); var sentinel = new InvalidOperationException("Owned original remove callback fault"); bool fail = true; int notifications = 0;
                owned.Subscribe(OwnedA, (input, disabled) => { if (!disabled) { notifications++; Require(owned.Handles.Count == 2 && !owned.Mapping.IsGameInputDisabled(OwnedA), "remove publishes provider mutation before callback and list clear"); if (fail) throw sentinel; } });
                SameFault(owned.Value.Action_ReenableGameInputs, sentinel); Require(owned.Handles.Count == 2 && !owned.Mapping.IsGameInputDisabled(OwnedA) && owned.Mapping.IsGameInputDisabled(OwnedB), "remove fault retains complete handle list after first provider removal"); checks++;
                fail = false; owned.Value.Action_ReenableGameInputs(); Require(owned.Handles.Count == 0 && !owned.Mapping.IsGameInputDisabled(OwnedB) && notifications == 1, "retry skips already removed handle, completes second and clears list"); checks++;
            }, () => Dispose(owned));
            owned = null;
            Finish(() =>
            {
                owned = new OwnedDisabler(); owned.Value.Action_DisableGameInputs(); bool mutate = true;
                owned.Subscribe(OwnedA, (input, disabled) => { if (!disabled && mutate) { mutate = false; owned.Handles.Add(new StackableDataHandle()); } });
                Fault<InvalidOperationException>(owned.Value.Action_ReenableGameInputs); Require(owned.Handles.Count == 3 && !owned.Mapping.IsGameInputDisabled(OwnedA) && owned.Mapping.IsGameInputDisabled(OwnedB), "real live list enumerator faults after owned callback version mutation"); checks++;
                owned.Value.Action_ReenableGameInputs(); Require(owned.Handles.Count == 0 && !owned.Mapping.IsGameInputDisabled(OwnedB), "retry completes genuine removal and ignores detached handle"); checks++;
            }, () => Dispose(owned)); return checks;
        }
    }
}
