using System;
using System.Collections;
using System.Globalization;
using System.Reflection;
using System.Runtime.CompilerServices;

namespace ProjectLucid
{
public static partial class HardlightEnumStringsVerification
{
    private static int checks;
    private static void Check(bool condition, string message)
    {
        if (!condition) throw new Exception(message);
        ++checks;
    }
    private sealed class Row
    {
        internal readonly string Enum, Field, Comparer;
        internal readonly int[] Keys;
        internal readonly string[] Literals, Names;
        internal Row(string e, string f, string c, int[] k, string[] l, string[] n)
        { Enum=e; Field=f; Comparer=c; Keys=k; Literals=l; Names=n; }
    }
    public static void Run() { Execute(); UnityEngine.Debug.Log("Original enum string registry verified checks=" + checks); }
    public static int RunManaged() { Execute(); return checks; }
    private static void Execute()
    {
        checks = 0;
        Assembly a=typeof(HardlightProject.ApplicationSettings).Assembly;
        Type helper=a.GetType("HardlightProject.HardlightEnumExtensions", true);
        Type comparers=a.GetType("HardlightProject.HardlightEnumComparers", true);
        Check(a.GetName().Name=="HLAutoGenerated", "assembly identity");
        Check(helper.IsPublic && helper.IsAbstract && helper.IsSealed, "static class flags");
        Check((helper.Attributes & TypeAttributes.BeforeFieldInit)!=0, "original BeforeFieldInit");
        var attrs=helper.GetCustomAttributesData();
        int attrIndex=0, extensions=0;
        foreach (var attr in attrs)
        {
            if (attr.AttributeType.FullName=="Unity.IL2CPP.CompilerServices.Il2CppSetOptionAttribute")
            {
                Check((int)attr.ConstructorArguments[0].Value==ExpectedOptions[attrIndex++], "ordered original IL2CPP option");
                Check((bool)attr.ConstructorArguments[1].Value==false, "original false IL2CPP option");
            }
            else if (attr.AttributeType==typeof(ExtensionAttribute)) ++extensions;
            else throw new Exception("Unexpected helper attribute: "+attr.AttributeType);
        }
        Check(attrIndex==214 && extensions==1 && attrs.Count==215, "original complete helper attributes");
        FieldInfo[] fields=helper.GetFields(BindingFlags.Static|BindingFlags.Public|BindingFlags.NonPublic);
        Array.Sort(fields, (x,y)=>x.MetadataToken.CompareTo(y.MetadataToken));
        Check(fields.Length==107, "complete original private static field count");
        Check(helper.GetMethods(BindingFlags.Public|BindingFlags.Static|BindingFlags.DeclaredOnly).Length==107, "complete original GetString overload count");
        Check(helper.TypeInitializer!=null && helper.TypeInitializer.GetMethodBody().GetILAsByteArray().Length>0, "complete initializer present");
        RuntimeHelpers.RunClassConstructor(helper.TypeHandle);
        int entries=0;
        for(int r=0;r<ExpectedRows.Length;++r)
        {
            Row row=ExpectedRows[r]; FieldInfo field=fields[r];
            Type e=a.GetType(row.Enum,true);
            Check(field.Name==row.Field, "original ordered field name");
            Check(field.IsPrivate && field.IsStatic && !field.IsInitOnly, "mutable private static field");
            Check(e.IsEnum && Enum.GetUnderlyingType(e)==typeof(int), "original enum Int32 width");
            Check(e.GetFields(BindingFlags.Public|BindingFlags.Static).Length==row.Keys.Length, "complete maintained enum constants");
            Check((int)e.Attributes==257 && e.GetCustomAttributesData().Count==0, "native enum flags and attributes");
            Check(field.FieldType.GetGenericArguments()[0]==e && field.FieldType.GetGenericArguments()[1]==typeof(string), "exact dictionary key/value types");
            IDictionary dictionary=(IDictionary)field.GetValue(null);
            Check(dictionary!=null && dictionary.Count==row.Keys.Length, "native initializer entry count");
            object comparer=field.FieldType.GetProperty("Comparer").GetValue(dictionary,null);
            Check(object.ReferenceEquals(comparer,comparers.GetField(row.Comparer).GetValue(null)), "authored comparer object reuse");
            MethodInfo get=helper.GetMethod("GetString",BindingFlags.Public|BindingFlags.Static,null,new[]{e},null);
            Check(get!=null && get.ReturnType==typeof(string), "exact original overload signature");
            Check(get.IsDefined(typeof(ExtensionAttribute),false), "extension metadata");
            for(int i=0;i<row.Keys.Length;++i)
            {
                object key=Enum.ToObject(e,row.Keys[i]);
                Check(Enum.GetName(e,key)==row.Names[i], "maintained constant identity at native numeric value");
                object value=dictionary[key];
                Check((string)value==row.Literals[i], "actual native literal at native numeric key");
                object result=get.Invoke(null,new[]{key});
                Check(object.ReferenceEquals(result,value), "known lookup returns original dictionary reference");
                ++entries;
            }
            Check(dictionary.Count==row.Keys.Length, "known lookups preserve dictionary");
            foreach(int keyValue in new[]{0x1234,int.MaxValue,int.MinValue,-1,0})
            {
                object key=Enum.ToObject(e,keyValue);
                if(dictionary.Contains(key)) continue;
                int oldCount=dictionary.Count;
                string expected="0x"+unchecked((uint)keyValue).ToString("X8",CultureInfo.InvariantCulture);
                string result=(string)get.Invoke(null,new[]{key});
                Check(result==expected, "unknown enum uses original padded hex format");
                Check(dictionary.Count==oldCount+1 && object.ReferenceEquals(dictionary[key],result), "unknown result cached through indexer");
                Check(object.ReferenceEquals(get.Invoke(null,new[]{key}),result), "repeat unknown returns cached reference");
                dictionary.Remove(key);
            }
            object known=Enum.ToObject(e,row.Keys[0]);
            object original=dictionary[known];
            string injected=new string(new[]{'m','u','t','a','t','e','d'});
            dictionary[known]=injected;
            Check(object.ReferenceEquals(get.Invoke(null,new[]{known}),injected), "existing mutation observed");
            dictionary[known]=null;
            Check(get.Invoke(null,new[]{known})==null && dictionary.Contains(known), "existing null is present and returned");
            dictionary[known]=original;
            // Whole field replacement proves the helper reads the current mutable dictionary.
            IDictionary replacement=(IDictionary)Activator.CreateInstance(field.FieldType);
            field.SetValue(null,replacement);
            try
            {
                string value=(string)get.Invoke(null,new[]{known});
                string expected="0x"+unchecked((uint)row.Keys[0]).ToString("X8",CultureInfo.InvariantCulture);
                Check(value==expected && replacement.Count==1 && object.ReferenceEquals(replacement[known],value), "replacement dictionary receives authored fallback");
                Check(object.ReferenceEquals(get.Invoke(null,new[]{known}),value), "replacement fallback cached");
            }
            finally {field.SetValue(null,dictionary);}
            Check(dictionary.Count==row.Keys.Length, "private checks restore original dictionary");
        }
        Check(entries==2676, "all original native entries exercised");
        Check(HardlightProject.HardlightEnumExtensions.GetString(HardlightProject.ApplicationSettings.SceneOperation)=="SceneOperation", "AppFSMKeys SceneOpKey dependency");

    }
}
}
