using System;
using System.Linq;
using System.Reflection;
using HardlightProject;
using UnityEngine;
using Unity.IL2CPP.CompilerServices;
namespace ProjectLucid.Editor
{
 public static class HashedGroupConfigurationCurrentFacts
 {
  const BindingFlags Declared=BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance|BindingFlags.Static|BindingFlags.DeclaredOnly;
  static readonly string[] AttributeBlobs=new string[] {"01000200540e0866696c654e616d651848617368656447726f7570436f6e66696775726174696f6e540e086d656e754e616d6538486172646c6967687450726f6a6563742f446566696e6974696f6e446174612f48617368656447726f7570436f6e66696775726174696f6e","01000200000002000000","01000100000002000000"};
  internal static void Require(bool value,string text){if(!value)throw new InvalidOperationException("HashedGroupConfiguration current-emission setup hold: "+text);}
  internal static bool Scope(Type type,string scope)
  {
   if(scope=="Game.Runtime.dll")return type==typeof(HashedGroupConfiguration)&&type.Assembly.GetName().Name=="Game.Runtime";
   if(scope=="UnityEngine.CoreModule")return(type==typeof(ScriptableObject)||type==typeof(UnityEngine.Object)||type==typeof(CreateAssetMenuAttribute))&&type.Assembly==typeof(ScriptableObject).Assembly;
   if(scope=="HLUnityCore.Runtime")return(type==typeof(Il2CppSetOptionAttribute)||type==typeof(Option))&&type.Assembly==typeof(Il2CppSetOptionAttribute).Assembly;
   if(scope=="netstandard")return type==typeof(void)||type==typeof(bool)||type==typeof(int)||type==typeof(float)||type==typeof(string)||type==typeof(object)||type==typeof(Attribute);
   return false;
  }
  static void Annotations(Type owner)
  {
   var all=owner.GetCustomAttributesData();Require(all.Count==3,"complete exact three owner annotations");var menu=all[0];Require(menu.AttributeType==typeof(CreateAssetMenuAttribute)&&menu.Constructor==typeof(CreateAssetMenuAttribute).GetConstructor(Type.EmptyTypes)&&menu.ConstructorArguments.Count==0&&menu.NamedArguments.Count==2,"genuine exact asset-menu annotation declaration");string[] names={"fileName","menuName"},values={"HashedGroupConfiguration","HardlightProject/DefinitionData/HashedGroupConfiguration"};for(int i=0;i<2;i++){var named=menu.NamedArguments[i];var property=named.MemberInfo as PropertyInfo;Require(!named.IsField&&property!=null&&property.DeclaringType==typeof(CreateAssetMenuAttribute)&&property.Name==names[i]&&property.PropertyType==typeof(string)&&named.TypedValue.ArgumentType==typeof(string)&&named.TypedValue.Value is string text&&text==values[i],"complete exact ordered asset-menu string property");}
   for(int i=1;i<3;i++){var option=all[i];Require(option.AttributeType==typeof(Il2CppSetOptionAttribute)&&option.Constructor==typeof(Il2CppSetOptionAttribute).GetConstructor(new[]{typeof(Option),typeof(object)})&&option.NamedArguments.Count==0&&option.ConstructorArguments.Count==2&&option.ConstructorArguments[0].ArgumentType==typeof(Option)&&Convert.ToInt32(option.ConstructorArguments[0].Value)==(i==1?2:1)&&option.ConstructorArguments[1].ArgumentType==typeof(bool),"exact ordered genuine option annotation");object boxed=option.ConstructorArguments[1].Value;Require(boxed is bool value&&!value,"literal false original option value");}
  }
  public static void RequireWholeCurrentEmission()
  {
   Type owner=typeof(HashedGroupConfiguration);Assembly assembly=owner.Assembly;Require(assembly.GetName().Name=="Game.Runtime"&&assembly.ManifestModule.Name=="Game.Runtime.dll","genuine loaded Game assembly/module; dynamically bound below");Require(typeof(ScriptableObject).Assembly.GetName().Name=="UnityEngine.CoreModule"&&typeof(UnityEngine.Object).Assembly==typeof(ScriptableObject).Assembly&&typeof(CreateAssetMenuAttribute).Assembly==typeof(ScriptableObject).Assembly,"exact genuine Unity provider family");Require(typeof(Il2CppSetOptionAttribute).Assembly.GetName().Name=="HLUnityCore.Runtime"&&typeof(Option).Assembly==typeof(Il2CppSetOptionAttribute).Assembly,"exact genuine Core annotation provider family");
   Require(owner.BaseType==typeof(ScriptableObject)&&(int)owner.Attributes==1048577&&!owner.IsGenericType&&owner.GetGenericArguments().Length==0&&owner.GetInterfaces().Length==0&&owner.GetFields(Declared).Length==0&&owner.GetProperties(Declared).Length==0&&owner.GetEvents(Declared).Length==0&&owner.GetNestedTypes(Declared).Length==0&&owner.GetMethods(Declared).Length==0,"complete ordinary fieldless non-generic owner inventory and exact base");Annotations(owner);
   var constructors=owner.GetConstructors(Declared);Require(constructors.Length==1,"whole sole original constructor");ConstructorInfo constructor=constructors[0];Require(constructor.DeclaringType==owner&&constructor.Name==".ctor"&&!constructor.IsStatic&&!constructor.IsGenericMethod&&constructor.GetParameters().Length==0&&(int)constructor.Attributes==6278&&(int)constructor.GetMethodImplementationFlags()==0&&constructor.CallingConvention==(CallingConventions.Standard|CallingConventions.HasThis)&&constructor.GetCustomAttributesData().Count==0,"complete exact original constructor flags/impl/convention/parameters/attributes");
   MethodBody body=constructor.GetMethodBody();Require(body!=null&&body.MaxStackSize==8&&!body.InitLocals&&body.LocalSignatureMetadataToken==0&&body.LocalVariables.Count==0&&body.ExceptionHandlingClauses.Count==0,"exact tiny header/physical nil local projection/no locals/no EH; projection unobserved until actual trial");byte[] cil=body.GetILAsByteArray();Require(cil.Length==7&&cil[0]==2&&cil[1]==40&&cil[6]==42,"every literal noncell constructor CIL byte");int token=BitConverter.ToInt32(cil,2);Require((token&unchecked((int)0xff000000))==0x0a000000&&(token&0x00ffffff)>0,"exact MemberRef table before resolving sole relocatable four-byte cell");var provider=constructor.Module.ResolveMember(token)as ConstructorInfo;Require(provider!=null&&provider.DeclaringType==typeof(ScriptableObject)&&provider.Name==".ctor"&&!provider.IsStatic&&!provider.IsGenericMethod&&provider.GetParameters().Length==0&&(int)provider.Attributes==6278&&(int)provider.GetMethodImplementationFlags()==0&&provider.GetCustomAttributesData().Count==0&&provider.CallingConvention==(CallingConventions.Standard|CallingConventions.HasThis),"exact genuine ScriptableObject constructor scoped member/full signature/HasThis/static/generic shape");var image=new CurrentHashedImage(assembly);image.RequireOwner(owner,AttributeBlobs);image.RequireMethod(constructor,body);image.RequireMember(token,provider);image.RequireUnchanged();
  }
 }
 internal sealed class CurrentHashedImage
 {
  readonly string path;readonly byte[] bytes;readonly Module module;readonly int[] counts=new int[64],offsets=new int[43],sizes=new int[43];readonly int stringWidth,guidWidth,blobWidth,strings,guid,blobs,blobEnd;readonly int[] sectionRva,sectionVirtual,sectionRaw,sectionSize;
  static void Need(bool x,string text){HashedGroupConfigurationCurrentFacts.Require(x,"dynamic actual Game module file: "+text);}
  int Read(int at,int width){Need(at>=0&&width>0&&width<=4&&at<=bytes.Length-width,"bounded physical cell");uint x=0;for(int i=0;i<width;i++)x|=(uint)bytes[at+i]<<(8*i);Need(x<=int.MaxValue,"bounded positive cell");return(int)x;}
  uint U32(int at){Need(at>=0&&at<=bytes.Length-4,"bounded DWORD");return(uint)(bytes[at]|bytes[at+1]<<8|bytes[at+2]<<16|bytes[at+3]<<24);}
  int Index(int table){return counts[table]>=65536?4:2;}
  int Coded(int bits,params int[] tables){return tables.Max(x=>counts[x])>=(1<<(16-bits))?4:2;}
  int Rva(int address){for(int i=0;i<sectionRva.Length;i++)if(address>=sectionRva[i]&&address-sectionRva[i]<Math.Max(sectionVirtual[i],sectionSize[i])){int x=sectionRaw[i]+address-sectionRva[i];Need(x>=0&&x<bytes.Length,"mapped physical RVA");return x;}throw new InvalidOperationException("Game leaf current-emission setup hold: unmapped assembly-file RVA");}
  string String(int index){Need(index>=0&&strings+index<bytes.Length,"bounded string index");int end=strings+index;while(end<bytes.Length&&bytes[end]!=0)end++;Need(end<bytes.Length,"terminated physical string");return System.Text.Encoding.UTF8.GetString(bytes,strings+index,end-strings-index);}
  internal CurrentHashedImage(Assembly assembly)
  {
   module=assembly.ManifestModule;path=assembly.Location;Need(!string.IsNullOrEmpty(path)&&System.IO.File.Exists(path),"genuine loaded assembly has a readable actual file");bytes=System.IO.File.ReadAllBytes(path);Need(AssemblyName.GetAssemblyName(path).FullName==assembly.GetName().FullName,"exact file/loaded assembly identity");Need(bytes.Length>=64,"complete PE header");int pe=Read(60,4);Need(U32(pe)==0x00004550,"PE signature");int sections=Read(pe+6,2),optional=pe+24,optionalSize=Read(pe+20,2);int magic=Read(optional,2);Need(magic==0x10b||magic==0x20b,"actual PE32/PE32+ format");int directory=optional+(magic==0x10b?96:112),sectionTable=optional+optionalSize;
   sectionRva=new int[sections];sectionVirtual=new int[sections];sectionRaw=new int[sections];sectionSize=new int[sections];for(int i=0;i<sections;i++){int at=sectionTable+i*40;sectionVirtual[i]=Read(at+8,4);sectionRva[i]=Read(at+12,4);sectionSize[i]=Read(at+16,4);sectionRaw[i]=Read(at+20,4);Need(sectionRaw[i]<=bytes.Length-sectionSize[i],"complete physical section range");}
   int cli=Rva(Read(directory+14*8,4)),metadata=Rva(Read(cli+8,4));Need(U32(metadata)==0x424a5342,"CLI metadata signature");int q=metadata+16+Read(metadata+12,4);q=(q+3)&~3;int streamCount=Read(q+2,2);q+=4;int table=-1,stringsAt=-1,guidAt=-1,blobsAt=-1,blobsEnd=-1;
   for(int i=0;i<streamCount;i++){int relative=Read(q,4),length=Read(q+4,4),end=q+8;while(end<bytes.Length&&bytes[end]!=0)end++;Need(end<bytes.Length,"terminated stream name");string name=System.Text.Encoding.ASCII.GetString(bytes,q+8,end-q-8);q=(end+4)&~3;Need(relative>=0&&metadata+relative<=bytes.Length-length,"complete metadata stream");if(name=="#~")table=metadata+relative;else if(name=="#Strings")stringsAt=metadata+relative;else if(name=="#GUID")guidAt=metadata+relative;else if(name=="#Blob"){blobsAt=metadata+relative;blobsEnd=blobsAt+length;}}
   Need(table>=0&&stringsAt>=0&&guidAt>=0&&blobsAt>=0,"actual compressed tables/strings/GUID streams");strings=stringsAt;guid=guidAt;blobs=blobsAt;blobEnd=blobsEnd;int heaps=Read(table+6,1);stringWidth=(heaps&1)!=0?4:2;guidWidth=(heaps&2)!=0?4:2;blobWidth=(heaps&4)!=0?4:2;uint low=U32(table+8),high=U32(table+12);q=table+24;
   for(int i=0;i<64;i++)if(((i<32?low:high)>>(i%32)&1)!=0){counts[i]=Read(q,4);q+=4;}
   sizes[0]=2+stringWidth+3*guidWidth;sizes[1]=Coded(2,0,26,35,1)+2*stringWidth;sizes[2]=4+2*stringWidth+Coded(2,2,1,27)+Index(4)+Index(6);sizes[3]=Index(4);sizes[4]=2+stringWidth+blobWidth;sizes[5]=Index(6);sizes[6]=8+stringWidth+blobWidth+Index(8);sizes[7]=Index(8);sizes[8]=4+stringWidth;
   sizes[9]=Index(2)+Coded(2,2,1,27);sizes[10]=Coded(3,2,1,26,6,27)+stringWidth+blobWidth;sizes[11]=2+Coded(2,4,8,23)+blobWidth;sizes[12]=Coded(5,6,4,1,2,8,9,10,0,14,23,20,17,26,27,32,35,38,39,40,42,44,43)+Coded(3,6,10)+blobWidth;sizes[13]=Coded(1,4,8)+blobWidth;sizes[14]=2+Coded(2,2,6,32)+blobWidth;sizes[15]=6+Index(2);sizes[16]=4+Index(4);sizes[17]=blobWidth;
   sizes[18]=Index(2)+Index(20);sizes[19]=Index(20);sizes[20]=2+stringWidth+Coded(2,2,1,27);sizes[21]=Index(2)+Index(23);sizes[22]=Index(23);sizes[23]=2+stringWidth+blobWidth;sizes[24]=2+Index(6)+Coded(1,20,23);sizes[25]=Index(2)+2*Coded(1,6,10);sizes[26]=stringWidth;sizes[27]=blobWidth;sizes[28]=2+Coded(1,4,6)+stringWidth+Index(26);sizes[29]=4+Index(4);sizes[30]=8;sizes[31]=4;sizes[32]=16+blobWidth+2*stringWidth;sizes[33]=4;sizes[34]=12;sizes[35]=12+2*blobWidth+2*stringWidth;sizes[36]=4+Index(35);sizes[37]=12+Index(35);sizes[38]=4+stringWidth+blobWidth;sizes[39]=8+2*stringWidth+Coded(2,38,35,39);sizes[40]=8+stringWidth+Coded(2,38,35,39);sizes[41]=2*Index(2);sizes[42]=4+Coded(1,2,6)+stringWidth;
   for(int i=0;i<43;i++){offsets[i]=q;Need(counts[i]<=bytes.Length/sizes[i],"bounded complete table prefix");q+=counts[i]*sizes[i];Need(q<=bytes.Length,"complete physical table prefix");}Need(counts[0]==1,"single genuine Module row");int moduleRow=offsets[0];Need(String(Read(moduleRow+2,stringWidth))==assembly.ManifestModule.Name,"exact file/loaded Module name");int mvidIndex=Read(moduleRow+2+stringWidth,guidWidth);Need(mvidIndex>0&&guid+(mvidIndex-1)*16<=bytes.Length-16,"complete MVID GUID");byte[] value=new byte[16];Buffer.BlockCopy(bytes,guid+(mvidIndex-1)*16,value,0,16);Need(new Guid(value)==assembly.ManifestModule.ModuleVersionId,"dynamic file/loaded MVID equality");
  }
  void TypeIdentity(int token,Type type)
  {
   int table=(int)((uint)token>>24),rid=token&0x00ffffff;Need((table==1||table==2)&&rid>0&&rid<=counts[table],"closed physical TypeDef/TypeRef identity");int row=offsets[table]+(rid-1)*sizes[table],nameAt=row+(table==2?4:Coded(2,0,26,35,1));Need(String(Read(nameAt,stringWidth))==type.Name,"exact physical type name");string ns=String(Read(nameAt+stringWidth,stringWidth));
   if(table==2){Need(type.Assembly==module.Assembly&&type.MetadataToken==token,"exact dynamic physical/loaded TypeDef identity");int parent=0;for(int i=0;i<counts[41];i++){int at=offsets[41]+i*sizes[41];if(Read(at,Index(2))==rid){Need(parent==0,"single physical enclosing owner");parent=Read(at+Index(2),Index(2));}}if(parent==0)Need(type.DeclaringType==null&&ns==(type.Namespace??""),"exact top-level TypeDef namespace");else{Need(type.DeclaringType!=null&&ns=="","exact nested TypeDef namespace/owner presence");TypeIdentity(0x02000000|parent,type.DeclaringType);}return;}
   int scope=Read(row,Coded(2,0,26,35,1)),tag=scope&3,parentRid=scope>>2;Need(parentRid>0,"nonzero physical TypeRef scope");if(tag==3){Need(type.DeclaringType!=null&&ns=="","exact nested TypeRef namespace/owner presence");TypeIdentity(0x01000000|parentRid,type.DeclaringType);return;}Need(type.DeclaringType==null&&ns==(type.Namespace??""),"exact top-level TypeRef namespace");if(tag==0){Need(parentRid==1&&type.Assembly==module.Assembly,"exact physical Module scope");return;}Need(tag==2&&parentRid<=counts[35],"closed physical AssemblyRef scope");int assemblyRow=offsets[35]+(parentRid-1)*sizes[35],name=assemblyRow+12+blobWidth;string assemblyName=String(Read(name,stringWidth));Need(HashedGroupConfigurationCurrentFacts.Scope(type,assemblyName),"exact physical AssemblyRef/genuine type provider binding");Need(String(Read(name+stringWidth,stringWidth))==""&&Read(assemblyRow+8,4)==0&&Read(assemblyRow+12+blobWidth+2*stringWidth,blobWidth)==0,"exact neutral physical provider culture/flags/empty hash");int keyIndex=Read(assemblyRow+12,blobWidth);if(assemblyName=="netstandard"){Need(Read(assemblyRow,2)==2&&Read(assemblyRow+2,2)==1&&Read(assemblyRow+4,2)==0&&Read(assemblyRow+6,2)==0,"exact encoded netstandard2.1 facade version");int keyAt,keyEnd;Blob(keyIndex,out keyAt,out keyEnd);Need(keyEnd-keyAt==8&&BitConverter.ToString(bytes,keyAt,8).Replace("-","").ToLowerInvariant()=="cc7b13ffcd2ddd51","exact encoded netstandard facade public-key token");}else Need(Read(assemblyRow,2)==0&&Read(assemblyRow+2,2)==0&&Read(assemblyRow+4,2)==0&&Read(assemblyRow+6,2)==0&&keyIndex==0,"exact recorded zero-version/empty-key genuine Unity/Core provider assembly reference");
  }
  internal void RequireType(int token,Type type){TypeIdentity(token,type);}
  void MemberOwner(int table,int rid,Type owner)
  {
   Need(owner.Assembly==module.Assembly,"exact own physical member assembly");int found=0,cell=4+2*stringWidth+Coded(2,2,1,27)+(table==6?Index(4):0);for(int i=1;i<=counts[2];i++){int at=offsets[2]+(i-1)*sizes[2],start=Read(at+cell,Index(table)),end=i<counts[2]?Read(at+sizes[2]+cell,Index(table)):counts[table]+1;if(rid>=start&&rid<end){Need(found==0,"single physical member owner");found=i;}}Need(found>0,"owned physical member range");TypeIdentity(0x02000000|found,owner);
  }
  int Compressed(ref int at,int end)
  {
   Need(at<end,"complete compressed integer");int a=bytes[at++];if((a&128)==0)return a;if((a&192)==128){Need(at<end,"complete two-byte compressed integer");int x=((a&63)<<8)|bytes[at++];Need(x>=128,"canonical two-byte compressed integer");return x;}Need((a&224)==192&&at<=end-3,"complete four-byte compressed integer");int z=((a&31)<<24)|(bytes[at++]<<16)|(bytes[at++]<<8)|bytes[at++];Need(z>=16384,"canonical four-byte compressed integer");return z;
  }
  void Blob(int index,out int at,out int end){Need(index>0&&blobs+index<blobEnd,"actual nonzero signature blob index");at=blobs+index;int length=Compressed(ref at,blobEnd);Need(length>=0&&at<=blobEnd-length,"complete signature blob range");end=at+length;}
  Type SignatureType(ref int at,int end)
  {
   Need(at<end,"complete exact signature type");int code=bytes[at++];switch(code){case 1:return typeof(void);case 2:return typeof(bool);case 8:return typeof(int);case 12:return typeof(float);case 14:return typeof(string);case 28:return typeof(object);case 29:{Type element=SignatureType(ref at,end);Need(element!=typeof(void),"nonvoid exact SZARRAY element");return element.MakeArrayType();}case 17:case 18:{int coded=Compressed(ref at,end),tag=coded&3,rid=coded>>2;Need(tag<3&&rid>0,"exact signature TypeDefOrRef coded cell");int table=tag==0?2:tag==1?1:27;Need(rid<=counts[table],"bounded actual signature type RID");Type type=module.ResolveType((table<<24)|rid);TypeIdentity((table<<24)|rid,type);Need(!type.HasElementType&&!type.IsGenericType&&type!=typeof(void)&&type!=typeof(bool)&&type!=typeof(int)&&type!=typeof(float)&&type!=typeof(string)&&type!=typeof(object),"named non-element nongeneric17/18; intrinsic selected types require exact short codes1/2/8/12/14/28");Need(type.IsValueType==(code==17),"exact signature CLASS/VALUETYPE discriminator");return type;}default:throw new InvalidOperationException("Game leaf current-emission setup hold: unowned signature type code "+code);}
  }
  void MethodSignature(int index,MethodBase method)
  {
   int at,end;Blob(index,out at,out end);Need(at<end,"complete method signature calling byte");int calling=bytes[at++];Need((calling&15)==0&&(calling&16)==0&&(calling&128)==0&&!method.IsGenericMethod,"exact nongeneric DEFAULT method signature");bool hasThis=(calling&32)!=0,explicitThis=(calling&64)!=0;Need(hasThis==!method.IsStatic&&!explicitThis&&method.CallingConvention==(CallingConventions.Standard|(hasThis?CallingConventions.HasThis:0)),"exact physical calling/HasThis/ExplicitThis/static shape");int count=Compressed(ref at,end);Type returns=SignatureType(ref at,end);Need(returns==(method is MethodInfo info?info.ReturnType:typeof(void)),"exact physical return signature type");var parameters=method.GetParameters();Need(count==parameters.Length,"exact physical signature parameter count");for(int i=0;i<count;i++)Need(SignatureType(ref at,end)==parameters[i].ParameterType,"exact ordered physical signature parameter type");Need(at==end,"whole method signature blob consumed");
  }
  internal void RequireMember(int token,MemberInfo member)
  {
   int table=(int)((uint)token>>24),rid=token&0x00ffffff;Need(rid>0&&(table==4||table==6||table==10)&&rid<=counts[table],"bounded exact member operand table/RID");int row=offsets[table]+(rid-1)*sizes[table],signature;
   if(table==10){int width=Coded(3,2,1,26,6,27),parent=Read(row,width),tag=parent&7,parentRid=parent>>3;Need((tag==0||tag==1)&&parentRid>0&&parentRid<=counts[tag==0?2:1],"closed exact MemberRef declaring TypeDef/TypeRef");TypeIdentity(((tag==0?2:1)<<24)|parentRid,member.DeclaringType);Need(module.ResolveType(((tag==0?2:1)<<24)|parentRid)==member.DeclaringType&&String(Read(row+width,stringWidth))==member.Name,"exact physical MemberRef declaring type and name");signature=Read(row+width+stringWidth,blobWidth);}else if(table==6){MemberOwner(table,rid,member.DeclaringType);Need(member is MethodBase&&String(Read(row+8,stringWidth))==member.Name,"exact physical MethodDef operand name/kind");signature=Read(row+8+stringWidth,blobWidth);}else{MemberOwner(table,rid,member.DeclaringType);Need(member is FieldInfo&&String(Read(row+2,stringWidth))==member.Name&&Read(row,2)==(int)((FieldInfo)member).Attributes,"exact physical Field operand name/flags/kind");signature=Read(row+2+stringWidth,blobWidth);}
   if(member is MethodBase method)MethodSignature(signature,method);else{var field=member as FieldInfo;Need(field!=null,"exact field signature kind");int at,end;Blob(signature,out at,out end);Need(at<end&&bytes[at++]==6&&SignatureType(ref at,end)==field.FieldType&&at==end,"whole exact physical FIELD signature blob");}
  }
  void LocalSignature(int token,MethodBody body)
  {
   if(token==0){Need(body.LocalVariables.Count==0,"exact physical nil local signature has no locals");return;}Need((token&unchecked((int)0xff000000))==0x11000000,"exact actual StandAloneSig table");int rid=token&0x00ffffff;Need(rid>0&&rid<=counts[17],"bounded actual local signature RID");int at,end;Blob(Read(offsets[17]+(rid-1)*sizes[17],blobWidth),out at,out end);Need(at<end&&bytes[at++]==7,"exact LOCAL_SIG calling byte");int count=Compressed(ref at,end);Need(count==body.LocalVariables.Count,"complete physical local signature count");for(int i=0;i<count;i++)Need(!body.LocalVariables[i].IsPinned&&body.LocalVariables[i].LocalIndex==i&&SignatureType(ref at,end)==body.LocalVariables[i].LocalType,"exact ordered unpinned physical local signature type");Need(at==end,"whole StandAloneSig blob consumed");
  }
  internal void RequireMethod(MethodBase method,MethodBody body)
  {
   int token=method.MetadataToken;Need((token&unchecked((int)0xff000000))==0x06000000,"exact MethodDef table");int rid=token&0x00ffffff;Need(rid>0&&rid<=counts[6],"actual complete MethodDef RID");int row=offsets[6]+(rid-1)*sizes[6],address=Read(row,4);Need(address!=0&&Read(row+4,2)==(int)method.GetMethodImplementationFlags()&&Read(row+6,2)==(int)method.Attributes&&String(Read(row+8,stringWidth))==method.Name,"exact selected physical MethodDef/name/flags/impl");
   for(int i=0;i<counts[12];i++){int cell=Read(offsets[12]+i*sizes[12],Coded(5,6,4,1,2,8,9,10,0,14,23,20,17,26,27,32,35,38,39,40,42,44,43));Need((cell&31)!=0||(cell>>5)!=rid,"zero physical selected method custom attributes");}for(int i=0;i<counts[28];i++){int cell=Read(offsets[28]+i*sizes[28]+2,Coded(1,4,6));Need((cell&1)!=1||(cell>>1)!=rid,"zero physical selected method PInvoke mapping");}MemberOwner(6,rid,method.DeclaringType);MethodSignature(Read(row+8+stringWidth,blobWidth),method);
   int paramAt=row+8+stringWidth+blobWidth,start=Read(paramAt,Index(8)),end=rid<counts[6]?Read(row+sizes[6]+8+stringWidth+blobWidth,Index(8)):counts[8]+1;Need(start>0&&end>=start&&end<=counts[8]+1,"actual Param range");var parameters=method.GetParameters();Need(end-start==parameters.Length,"complete ordinary Param range; zero physical ReturnParam rows");for(int i=0;i<parameters.Length;i++){int p=offsets[8]+(start+i-1)*sizes[8];Need(Read(p,2)==(int)parameters[i].Attributes&&Read(p+2,2)==i+1&&String(Read(p+4,stringWidth))==parameters[i].Name,"exact physical ordinary Param sequence/flags/name; no sequence0 row");}
   int at=Rva(address),first=Read(at,1),header,code,stack,local;bool init;
   if((first&3)==2){header=1;code=first>>2;stack=8;local=0;init=false;}else{int flags=Read(at,2);Need((flags&3)==3&&(flags&8)==0&&(flags>>12)==3,"exact fat header and zero physical EH sections");header=12;stack=Read(at+2,2);code=Read(at+4,4);local=Read(at+8,4);init=(flags&16)!=0;}
   Need(stack==body.MaxStackSize&&init==body.InitLocals&&local==body.LocalSignatureMetadataToken&&body.ExceptionHandlingClauses.Count==0,"exact actual file/loaded body header/local token/zero EH");LocalSignature(local,body);byte[] actual=body.GetILAsByteArray();Need(actual.Length==code&&at+header<=bytes.Length-code,"whole physical CIL range");for(int i=0;i<code;i++)Need(bytes[at+header+i]==actual[i],"every actual file/loaded selected CIL byte");
  }
  internal void RequireOwner(Type owner,string[] attributeBlobs)
  {
   TypeIdentity(owner.MetadataToken,owner);int rid=owner.MetadataToken&0x00ffffff,row=offsets[2]+(rid-1)*sizes[2];Need(Read(row,4)==(int)owner.Attributes,"exact physical owner flags");int baseCell=Read(row+4+2*stringWidth,Coded(2,2,1,27)),tag=baseCell&3,baseRid=baseCell>>2;Need(tag<2&&baseRid>0,"closed exact physical base cell");TypeIdentity(((tag==0?2:1)<<24)|baseRid,owner.BaseType);
   int fieldsCell=row+4+2*stringWidth+Coded(2,2,1,27),fieldStart=Read(fieldsCell,Index(4)),methodStart=Read(fieldsCell+Index(4),Index(6));int fieldEnd=rid<counts[2]?Read(row+sizes[2]+4+2*stringWidth+Coded(2,2,1,27),Index(4)):counts[4]+1,methodEnd=rid<counts[2]?Read(row+sizes[2]+4+2*stringWidth+Coded(2,2,1,27)+Index(4),Index(6)):counts[6]+1;Need(fieldStart==fieldEnd&&methodEnd-methodStart==1&&owner.GetConstructors(BindingFlags.Public|BindingFlags.NonPublic|BindingFlags.Instance|BindingFlags.Static|BindingFlags.DeclaredOnly)[0].MetadataToken==(0x06000000|methodStart),"complete physical zero fields/sole constructor range");
   foreach(int table in new[]{9,18,21,25})for(int i=0;i<counts[table];i++)Need(Read(offsets[table]+i*sizes[table],Index(2))!=rid,"zero physical interface/event/property/override owner rows");for(int i=0;i<counts[15];i++)Need(Read(offsets[15]+i*sizes[15]+6,Index(2))!=rid,"zero physical owner class layout");for(int i=0;i<counts[41];i++)Need(Read(offsets[41]+i*sizes[41]+Index(2),Index(2))!=rid,"zero physical nested owner rows");for(int i=0;i<counts[42];i++){int cell=Read(offsets[42]+i*sizes[42]+4,Coded(1,2,6));Need(!((cell&1)==0&&(cell>>1)==rid)&&!((cell&1)==1&&(cell>>1)==methodStart),"zero physical owner/constructor generic parameters");}
   var attributes=owner.GetCustomAttributesData();int found=0;int parentWidth=Coded(5,6,4,1,2,8,9,10,0,14,23,20,17,26,27,32,35,38,39,40,42,44,43),constructorWidth=Coded(3,6,10);
   for(int i=0;i<counts[12];i++){int at=offsets[12]+i*sizes[12],parent=Read(at,parentWidth);if((parent&31)!=3||(parent>>5)!=rid)continue;Need(found<attributeBlobs.Length&&found<attributes.Count,"whole exact owner CA count");int constructor=Read(at+parentWidth,constructorWidth),constructorTag=constructor&7,constructorRid=constructor>>3;Need((constructorTag==2||constructorTag==3)&&constructorRid>0,"exact physical attribute constructor table");int token=((constructorTag==2?6:10)<<24)|constructorRid;var member=module.ResolveMethod(token);Need(member==attributes[found].Constructor,"exact physical/loaded ordered CA constructor identity");RequireMember(token,member);int start,end;Blob(Read(at+parentWidth+constructorWidth,blobWidth),out start,out end);Need(BitConverter.ToString(bytes,start,end-start).Replace("-","").ToLowerInvariant()==attributeBlobs[found],"whole exact stored owner annotation blob incl named property order/typed false values");found++;}Need(found==attributeBlobs.Length&&found==attributes.Count,"complete ordered physical/loaded owner annotations");
  }
  internal void RequireUnchanged(){Need(bytes.SequenceEqual(System.IO.File.ReadAllBytes(path)),"whole actual assembly file remains byte identical through selected metadata/body verification");}
 }

}
