using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Reflection.Emit;
using System.Security.Cryptography;
using System.Text;
using Hardlight;
using Hardlight.Enums;
using Hardlight.Utils;
using HardlightProject;
using Unity.IL2CPP.CompilerServices;
using UnityEditor;
using UnityEngine;
using UnityEngine.AddressableAssets;
using UnityEngine.ResourceManagement.AsyncOperations;

namespace ProjectLucid
{
    // RunManaged is the unchanged124 source/metadata/compiled-IL proof. RunEngine
    // creates genuine isolated engine fixtures; it never loads an authored asset
    // or initializes/loads the Addressables catalog. Engine checks run inside Unity.
    public static class MissionDisplayDefinitionVerification
    {
        private static int checks;
        private static void Require(bool condition, string description)
        {
            checks++;
            if (!condition) throw new InvalidOperationException(description);
        }

        public static int RunManaged()
        {
            checks = 0;
            Type music = typeof(MusicTrackDefinition), ornament = typeof(OrnamentDefinition);
            Require(music.Assembly.GetName().Name == "Game.Runtime" && ornament.Assembly == music.Assembly, "original Game.Runtime identity");
            Require(typeof(Strings).Assembly.GetName().Name == "HLAutoGenerated" && typeof(Strings).GetFields(BindingFlags.Public | BindingFlags.Static).Length == 1933, "genuine complete original Strings dependency");
            var stringFields = typeof(Strings).GetFields(BindingFlags.Public | BindingFlags.Static).OrderBy(f => f.MetadataToken);
            string canonical = string.Join("\n", stringFields.Select(f => f.Name + "\t" + f.GetRawConstantValue().ToString()));
            using (var sha = SHA256.Create())
                Require(BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(canonical))).Replace("-", "").ToLowerInvariant() == "6f6707b15c1bb60dd108ee1d6b61925ed1acaf3f60dcb186f9146cd89b5b9dea", "all original1933 ordered string enum names and signed values match metadata");
            Require(typeof(HashEnumAttribute).Assembly.GetName().Name == "HLUnityCore.Runtime", "original HashEnum attribute assembly identity");
            Require(typeof(AssetReferenceSprite).BaseType == typeof(AssetReferenceT<Sprite>) && typeof(AssetReferenceTexture).BaseType == typeof(AssetReferenceT<Texture>), "real Addressables typed reference inheritance");
            Require(typeof(ManagedAddressableAsset<>).Assembly == music.Assembly && !typeof(ManagedAddressableAsset<>).IsSerializable, "genuine nonserializable runtime wrapper identity");

            CheckType(music, new[] { typeof(Il2CppSetOptionAttribute), typeof(Il2CppSetOptionAttribute), typeof(CreateAssetMenuAttribute) });
            CheckType(ornament, new[] { typeof(Il2CppSetOptionAttribute), typeof(CreateAssetMenuAttribute), typeof(Il2CppSetOptionAttribute) });

            CheckFields(music,
                new[] { "m_identifier", "m_name", "m_composer", "m_image", "m_imageAsTexture", "m_alwaysUnlocked", "m_progressionUnlockWidget", "m_hiddenInJukebox", "m_imageAsset", "m_imageAssetTexture" },
                new[] { typeof(HLAudioClipIdentifier), typeof(Strings), typeof(Strings), typeof(AssetReferenceSprite), typeof(AssetReferenceTexture), typeof(bool), typeof(UIWidgetProgression), typeof(bool), typeof(ManagedAddressableAsset<Sprite>), typeof(ManagedAddressableAsset<Texture>) },
                new[] { new[] { typeof(HashEnumAttribute), typeof(SerializeField) }, new[] { typeof(SerializeField), typeof(HashEnumAttribute) }, new[] { typeof(SerializeField), typeof(HashEnumAttribute) }, new[] { typeof(SerializeField) }, new[] { typeof(SerializeField) }, new[] { typeof(SerializeField) }, new[] { typeof(SerializeField) }, new[] { typeof(SerializeField) }, Type.EmptyTypes, Type.EmptyTypes }, 8, -1);
            CheckFields(ornament,
                new[] { "m_identifier", "m_ornament", "m_category", "m_unlockedByAchievement", "m_localisedName", "m_localisedUnlockedLore", "m_localisedLockedTip", "m_actNumber", "m_thumbnailAsset", "m_thumbnailUncropped", "m_progressionUnlockWidget", "m_thumbnailUncroppedAsset", "ThumbnailAsset" },
                new[] { typeof(OrnamentIdentifier), typeof(AssetReferenceT<GameObject>), typeof(OrnamentCategory), typeof(AchievementIdentifier), typeof(Strings), typeof(Strings), typeof(Strings), typeof(int), typeof(AssetReferenceT<Texture>), typeof(AssetReferenceTexture), typeof(UIWidgetProgression), typeof(ManagedAddressableAsset<Texture>), typeof(ManagedAddressableAsset<Texture>) },
                new[] { new[] { typeof(SerializeField) }, new[] { typeof(SerializeField) }, new[] { typeof(SerializeField) }, new[] { typeof(ShowIfAttribute), typeof(SerializeField) }, new[] { typeof(SerializeField), typeof(HashEnumAttribute) }, new[] { typeof(SerializeField), typeof(HashEnumAttribute) }, new[] { typeof(SerializeField), typeof(HashEnumAttribute) }, new[] { typeof(SerializeField), typeof(ShowIfAttribute) }, new[] { typeof(SerializeField) }, new[] { typeof(SerializeField) }, new[] { typeof(TooltipAttribute), typeof(SerializeField) }, Type.EmptyTypes, Type.EmptyTypes }, 11, 12);

            foreach (string field in new[] { "m_identifier", "m_name", "m_composer" })
                CheckHashEnum(Field(music, field), null);
            foreach (string field in new[] { "m_localisedName", "m_localisedUnlockedLore", "m_localisedLockedTip" })
                CheckHashEnum(Field(ornament, field), typeof(Strings));
            CheckShowIf(Field(ornament, "m_unlockedByAchievement"), OrnamentCategory.Achievement, -460385562);
            CheckShowIf(Field(ornament, "m_actNumber"), OrnamentCategory.Story, -469943945);
            var tooltip = Field(ornament, "m_progressionUnlockWidget").GetCustomAttributesData().Single(a => a.AttributeType == typeof(TooltipAttribute));
            Require(tooltip.ConstructorArguments.Count == 1 && Equals(tooltip.ConstructorArguments[0].Value, "Widget to instantiate as part of the unlocked screen."), "original progression tooltip payload");

            CheckGetters(music, new[] { "ClipIdentifier", "Name", "Composer", "AlwaysUnlocked", "ProgressionUnlockWidget", "ImageAsset", "ImageAssetTexture", "HiddenInJukebox" }, new[] { "m_identifier", "m_name", "m_composer", "m_alwaysUnlocked", "m_progressionUnlockWidget", "m_imageAsset", "m_imageAssetTexture", "m_hiddenInJukebox" });
            CheckGetters(ornament, new[] { "OrnamentIdentifier", "Ornament", "OrnamentCategory", "LocalisedName", "LocalisedUnlockedLore", "LocalisedLockedTip", "UnlockedByAchievement", "ProgressionUnlockWidget", "ActNumber", "ThumbnailUncroppedAsset" }, new[] { "m_identifier", "m_ornament", "m_category", "m_localisedName", "m_localisedUnlockedLore", "m_localisedLockedTip", "m_unlockedByAchievement", "m_progressionUnlockWidget", "m_actNumber", "m_thumbnailUncroppedAsset" });
            CheckEnable(music, new[] { "m_image", "m_imageAsTexture" }, new[] { "m_imageAsset", "m_imageAssetTexture" }, new[] { typeof(Sprite), typeof(Texture) });
            CheckEnable(ornament, new[] { "m_thumbnailUncropped", "m_thumbnailAsset" }, new[] { "m_thumbnailUncroppedAsset", "ThumbnailAsset" }, new[] { typeof(Texture), typeof(Texture) });
            return checks;
        }

        private static FieldInfo Field(Type type, string name) => type.GetField(name, BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly);
        private static void CheckType(Type type, Type[] orderedAttributes)
        {
            Require(type.IsPublic && !type.IsSealed && !type.IsAbstract && type.BaseType == typeof(ScriptableObjectWithGuid), type.Name + " original complete type/base contract");
            Require(type.GetCustomAttributesData().Select(a => a.AttributeType).SequenceEqual(orderedAttributes), type.Name + " original ordered class attributes");
            var options = type.GetCustomAttributes<Il2CppSetOptionAttribute>(false).ToArray();
            Require(options.Length == 2 && options[0].Option == Option.NullChecks && options[1].Option == Option.ArrayBoundsChecks && Equals(options[0].Value, false) && Equals(options[1].Value, false), type.Name + " original IL2CPP options and values");
            var menu = type.GetCustomAttribute<CreateAssetMenuAttribute>(false);
            Require(menu.fileName == type.Name && menu.menuName == "HardlightProject/DefinitionData/Definitions/" + type.Name, type.Name + " original creation menu payload");
            var code = ReadIL(type.GetConstructor(Type.EmptyTypes)).ToArray();
            Require(code.Length == 3 && code[0].op == OpCodes.Ldarg_0 && code[1].op == OpCodes.Call && ((MethodBase)code[1].value).IsConstructor && ((MethodBase)code[1].value).DeclaringType == typeof(ScriptableObjectWithGuid) && code[2].op == OpCodes.Ret, type.Name + " native constructor only calls original GUID base, with no own enum/list/wrapper initialization");
        }
        private static void CheckFields(Type type, string[] names, Type[] types, Type[][] attributes, int serializedCount, int publicIndex)
        {
            var fields = type.GetFields(BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly).OrderBy(f => f.MetadataToken).ToArray();
            Require(fields.Select(f => f.Name).SequenceEqual(names), type.Name + " complete original own field order");
            for (int i = 0; i < fields.Length; i++)
            {
                var f = fields[i];
                Require(f.FieldType == types[i] && !f.IsStatic && !f.IsInitOnly && !f.IsLiteral && (i == publicIndex ? f.IsPublic : f.IsPrivate), type.Name + "." + f.Name + " original field type/visibility/mutability");
                Require(f.IsDefined(typeof(SerializeField), false) == (i < serializedCount) && f.IsNotSerialized == (i >= serializedCount && i != publicIndex), type.Name + "." + f.Name + " original serialization flags, without added exclusions");
                Require(f.GetCustomAttributesData().Where(a => a.AttributeType != typeof(NonSerializedAttribute)).Select(a => a.AttributeType).SequenceEqual(attributes[i]), type.Name + "." + f.Name + " original ordered field attributes");
            }
        }
        private static void CheckHashEnum(FieldInfo field, Type expected)
        {
            var data = field.GetCustomAttributesData().Single(a => a.AttributeType == typeof(HashEnumAttribute));
            Require(data.ConstructorArguments.Count == 1 && data.ConstructorArguments[0].ArgumentType == typeof(Type) && Equals(data.ConstructorArguments[0].Value, expected), field.Name + " exact original HashEnum type/null payload");
        }
        private static void CheckShowIf(FieldInfo field, OrnamentCategory category, int originalInt)
        {
            var data = field.GetCustomAttributesData().Single(a => a.AttributeType == typeof(ShowIfAttribute));
            var condition = data.ConstructorArguments[1];
            if (condition.Value is CustomAttributeTypedArgument boxed) condition = boxed;
            Require(data.ConstructorArguments.Count == 2 && Equals(data.ConstructorArguments[0].Value, "m_category") && condition.ArgumentType == typeof(OrnamentCategory) && Convert.ToInt32(condition.Value) == originalInt && (int)category == originalInt, field.Name + " exact original ShowIf enum/member payload");
        }
        private static void CheckGetters(Type type, string[] properties, string[] fields)
        {
            var declared = type.GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly);
            Require(declared.OrderBy(p => p.MetadataToken).Select(p => p.Name).SequenceEqual(properties), type.Name + " complete original property API/order");
            for (int i = 0; i < properties.Length; i++)
            {
                var p = type.GetProperty(properties[i]); var code = ReadIL(p.GetMethod).ToArray();
                Require(p.SetMethod == null && p.PropertyType == Field(type, fields[i]).FieldType && p.GetMethod.IsPublic && code.Length == 3 && code[0].op == OpCodes.Ldarg_0 && code[1].op == OpCodes.Ldfld && ((FieldInfo)code[1].value).Name == fields[i] && code[2].op == OpCodes.Ret, type.Name + "." + p.Name + " native direct getter preserves field/type/alias");
            }
        }
        private static void CheckEnable(Type type, string[] inputs, string[] outputs, Type[] genericTypes)
        {
            var method = type.GetMethod("OnEnable", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly);
            Require(method.IsFamily && !method.IsVirtual && method.GetParameters().Length == 0 && method.ReturnType == typeof(void), type.Name + " original protected nonvirtual lifecycle API");
            var code = ReadIL(method).ToArray();
            Require(code.Length == 11 && code[10].op == OpCodes.Ret, type.Name + " complete straight-line native wrapper setup without branches/calls/releases/loads");
            for (int i = 0; i < 2; i++)
            {
                int n = i * 5; var ctor = (ConstructorInfo)code[n + 3].value;
                Require(code[n].op == OpCodes.Ldarg_0 && code[n + 1].op == OpCodes.Ldarg_0 && code[n + 2].op == OpCodes.Ldfld && ((FieldInfo)code[n + 2].value).Name == inputs[i] && code[n + 3].op == OpCodes.Newobj && ctor.DeclaringType == typeof(ManagedAddressableAsset<>).MakeGenericType(genericTypes[i]) && ctor.GetParameters().Length == 1 && ctor.GetParameters()[0].ParameterType == typeof(AssetReferenceT<>).MakeGenericType(genericTypes[i]) && code[n + 4].op == OpCodes.Stfld && ((FieldInfo)code[n + 4].value).Name == outputs[i], type.Name + " wrapper " + i + " exact input/store/generic-constructor ordering, including null and replacement paths");
            }
        }
        private static IEnumerable<(OpCode op, object value)> ReadIL(MethodBase method)
        {
            var codes = typeof(OpCodes).GetFields(BindingFlags.Public | BindingFlags.Static).Where(f => f.FieldType == typeof(OpCode)).Select(f => (OpCode)f.GetValue(null)).ToDictionary(o => o.Value);
            byte[] il = method.GetMethodBody().GetILAsByteArray();
            for (int p = 0; p < il.Length;)
            {
                short key = il[p++]; if (key == 0xfe) key = (short)(0xfe00 | il[p++]);
                OpCode op = codes[key]; object value = null;
                switch (op.OperandType)
                {
                    case OperandType.InlineNone: break;
                    case OperandType.InlineField: value = method.Module.ResolveField(BitConverter.ToInt32(il, p)); p += 4; break;
                    case OperandType.InlineMethod: value = method.Module.ResolveMethod(BitConverter.ToInt32(il, p)); p += 4; break;
                    default: throw new InvalidOperationException("Unexpected bounded native-matched compiled IL: " + op);
                }
                yield return (op, value);
            }
        }
        private static int engineChecks;
        public const int ExpectedEngineChecks = 350;
        private static void EngineRequire(bool condition, string description)
        {
            ++engineChecks;
            if (!condition) throw new InvalidOperationException(description);
        }
        private static FieldInfo WrapperField<T>(string name) where T : UnityEngine.Object =>
            typeof(ManagedAddressableAsset<T>).GetField(name, BindingFlags.Instance | BindingFlags.NonPublic);
        private static bool EngineIdentity(UnityEngine.Object actual, UnityEngine.Object expected) =>
            expected == null ? actual == null && (ReferenceEquals(actual, null) || actual.GetInstanceID() == 0)
                : ReferenceEquals(actual, expected);
        private static void CheckWrapper<T>(ManagedAddressableAsset<T> wrapper, AssetReferenceT<T> reference,
            int count, T loaded, string label) where T : UnityEngine.Object
        {
            EngineRequire(wrapper != null && wrapper.GetType() == typeof(ManagedAddressableAsset<T>), label + " genuine complete wrapper type");
            EngineRequire(ReferenceEquals(WrapperField<T>("m_assetReference").GetValue(wrapper), reference), label + " exact retained package-reference identity");
            EngineRequire((int)WrapperField<T>("m_refCount").GetValue(wrapper) == count, label + " exact wrapper reference count");
            EngineRequire(EngineIdentity((T)WrapperField<T>("m_loadedAsset").GetValue(wrapper), loaded), label + " exact cached engine-object identity");
            EngineRequire(!((AsyncOperationHandle<T>)WrapperField<T>("m_assetHandle").GetValue(wrapper)).IsValid(), label + " no asset load or operation handle created");
        }
        private static void SeedOwnedCache<T>(ManagedAddressableAsset<T> wrapper, T value) where T : UnityEngine.Object
        {
            // These are real constructor-created wrappers and real engine objects.
            // Seed an isolated cached state without calling a catalog/provider/load API.
            WrapperField<T>("m_refCount").SetValue(wrapper, 7);
            WrapperField<T>("m_loadedAsset").SetValue(wrapper, value);
        }
        private static void Enable(ScriptableObject value) => value.GetType().GetMethod("OnEnable",
            BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly).Invoke(value, null);
        private static void Assign(ScriptableObject value, Dictionary<string, object> fields, string guid)
        {
            foreach (var field in fields) Field(value.GetType(), field.Key).SetValue(value, field.Value);
            typeof(ScriptableObjectWithGuid).GetField("m_guid", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(value, guid);
        }
        private static T SetSubObject<T>(T reference, string name, Type type) where T : AssetReference
        {
            reference.SubObjectName = name;
            typeof(AssetReference).GetField("m_SubObjectType", BindingFlags.Instance | BindingFlags.NonPublic).SetValue(reference, type.AssemblyQualifiedName);
            return reference;
        }
        private static bool SameReferenceValues(AssetReference actual, AssetReference expected)
        {
            var subType = typeof(AssetReference).GetField("m_SubObjectType", BindingFlags.Instance | BindingFlags.NonPublic);
            // Inline Unity serialization need not retain a derived managed type
            // assigned to a base-typed slot. The declared contract is checked by
            // CheckAuthored; these are the exact serialized package values.
            return actual != null && expected != null
                && actual.AssetGUID == expected.AssetGUID && actual.SubObjectName == expected.SubObjectName
                && Equals(subType.GetValue(actual), subType.GetValue(expected));
        }
        private static void CheckShape(ScriptableObject value, SerializedObject data)
        {
            data.Update();
            var own = value.GetType().GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly);
            foreach (var field in own)
            {
                var property = data.FindProperty(field.Name);
                bool authored = field.IsDefined(typeof(SerializeField), false);
                var kind = field.FieldType.IsEnum ? SerializedPropertyType.Enum : field.FieldType == typeof(bool)
                    ? SerializedPropertyType.Boolean : field.FieldType == typeof(int) ? SerializedPropertyType.Integer
                    : typeof(UnityEngine.Object).IsAssignableFrom(field.FieldType) ? SerializedPropertyType.ObjectReference : SerializedPropertyType.Generic;
                EngineRequire(authored ? property != null && property.propertyType == kind : property == null,
                    value.GetType().Name + "." + field.Name + " actual serialized shape/exclusion with unchanged original attributes");
            }
            var visible = new HashSet<string>();
            var iterator = data.GetIterator(); bool enter = true;
            while (iterator.NextVisible(enter)) { visible.Add(iterator.name); enter = false; }
            EngineRequire(new HashSet<string>(visible.Where(n => own.Any(f => f.Name == n))).SetEquals(
                own.Where(f => f.IsDefined(typeof(SerializeField), false)).Select(f => f.Name)),
                value.GetType().Name + " exact own authored fields in actual visible tree; public ThumbnailAsset receives no added exclusion attribute");
        }
        private static void CheckAuthored(ScriptableObject value, SerializedObject data, Dictionary<string, object> expected, string guid)
        {
            data.Update();
            foreach (var field in expected)
            {
                object actual = Field(value.GetType(), field.Key).GetValue(value);
                var property = data.FindProperty(field.Key);
                bool same;
                if (field.Value is AssetReference reference)
                {
                    var actualReference = actual as AssetReference;
                    same = Field(value.GetType(), field.Key).FieldType.IsInstanceOfType(actualReference)
                        && SameReferenceValues(actualReference, reference)
                        && property.FindPropertyRelative("m_AssetGUID").stringValue == reference.AssetGUID
                        && property.FindPropertyRelative("m_SubObjectName").stringValue == reference.SubObjectName
                        && property.FindPropertyRelative("m_SubObjectType").stringValue == (string)typeof(AssetReference)
                            .GetField("m_SubObjectType", BindingFlags.Instance | BindingFlags.NonPublic).GetValue(reference);
                }
                else if (field.Value is UnityEngine.Object engineObject)
                    same = EngineIdentity((UnityEngine.Object)actual, engineObject)
                        && EngineIdentity(property.objectReferenceValue, engineObject)
                        && property.objectReferenceInstanceIDValue == engineObject.GetInstanceID();
                else if (field.Value is bool boolean) same = Equals(actual, boolean) && property.boolValue == boolean;
                else same = Equals(actual, field.Value) && property.intValue == Convert.ToInt32(field.Value);
                EngineRequire(same, value.GetType().Name + "." + field.Key + " exact authored value in genuine field and SerializedObject");
            }
            EngineRequire(((ScriptableObjectWithGuid)value).GetGUID() == guid && data.FindProperty("m_guid").stringValue == guid,
                value.GetType().Name + " exact inherited authored GUID retained separately from engine identity");
        }
        private static void CheckJson(ScriptableObject value, string json, string guid)
        {
            foreach (var field in value.GetType().GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly))
                EngineRequire(json.Contains("\"" + field.Name + "\":") == field.IsDefined(typeof(SerializeField), false),
                    value.GetType().Name + "." + field.Name + " real JsonUtility authored inclusion/runtime exclusion");
            EngineRequire(json.Contains("\"m_guid\":\"" + guid + "\""), value.GetType().Name + " real JsonUtility inherited GUID");
        }

        // Engine lifecycle and serialization checks are separate from managed IL checks.
        // They do not establish authored asset bindings or catalog loading.
        public static int RunEngine()
        {
            engineChecks = 0;
            var owned = new List<UnityEngine.Object>();
            try
            {
                var music = ScriptableObject.CreateInstance<MusicTrackDefinition>(); owned.Add(music);
                var ornament = ScriptableObject.CreateInstance<OrnamentDefinition>(); owned.Add(ornament);
                var targetMusic = ScriptableObject.CreateInstance<MusicTrackDefinition>(); owned.Add(targetMusic);
                var targetOrnament = ScriptableObject.CreateInstance<OrnamentDefinition>(); owned.Add(targetOrnament);
                var sourceOwner = new GameObject("Project Lucid display-definition source fixture"); owned.Add(sourceOwner);
                var targetOwner = new GameObject("Project Lucid display-definition target fixture"); owned.Add(targetOwner);
                var sourceWidget = sourceOwner.AddComponent<UIWidgetProgression>();
                var targetWidget = targetOwner.AddComponent<UIWidgetProgression>();
                var texture = new Texture2D(2, 2) { name = "ProjectLucidDisplayOwnedTexture" }; owned.Add(texture);
                var sprite = Sprite.Create(texture, new Rect(0, 0, 2, 2), Vector2.zero); owned.Add(sprite);
                EngineRequire((UnityEngine.Object)music != null && music.GetType() == typeof(MusicTrackDefinition)
                    && music.ClipIdentifier == 0 && music.Name == 0 && music.Composer == 0 && !music.AlwaysUnlocked && !music.HiddenInJukebox,
                    "real Music constructor retains raw-zero enums/bools without invented Strings.NONE defaults");
                EngineRequire((UnityEngine.Object)ornament != null && ornament.GetType() == typeof(OrnamentDefinition)
                    && ornament.OrnamentIdentifier == 0 && ornament.OrnamentCategory == 0 && ornament.LocalisedName == 0
                    && ornament.LocalisedUnlockedLore == 0 && ornament.LocalisedLockedTip == 0 && ornament.UnlockedByAchievement == 0 && ornament.ActNumber == 0,
                    "real Ornament constructor retains original raw-zero authored scalars");
                EngineRequire(music.GetGUID() == "", "real Music genuine GUID base initializer");
                EngineRequire(ornament.GetGUID() == "", "real Ornament genuine GUID base initializer");
                EngineRequire(music.GetInstanceID() != targetMusic.GetInstanceID() && ornament.GetInstanceID() != targetOrnament.GetInstanceID(), "genuine distinct engine object identities");
                EngineRequire(ReferenceEquals(sourceWidget.gameObject, sourceOwner) && sourceWidget.MaskedTexture != null, "genuine source component constructor and owner");
                EngineRequire(ReferenceEquals(targetWidget.gameObject, targetOwner) && targetWidget.MaskedTexture != null
                    && !ReferenceEquals(sourceWidget.MaskedTexture, targetWidget.MaskedTexture), "genuine independent target component binder and owner");
                CheckWrapper(music.ImageAsset, (AssetReferenceSprite)Field(typeof(MusicTrackDefinition), "m_image").GetValue(music), 0, (Sprite)null, "automatic Music sprite enable");
                CheckWrapper(music.ImageAssetTexture, (AssetReferenceTexture)Field(typeof(MusicTrackDefinition), "m_imageAsTexture").GetValue(music), 0, (Texture)null, "automatic Music texture enable");
                CheckWrapper(ornament.ThumbnailUncroppedAsset, (AssetReferenceTexture)Field(typeof(OrnamentDefinition), "m_thumbnailUncropped").GetValue(ornament), 0, (Texture)null, "automatic Ornament uncropped enable");
                CheckWrapper(ornament.ThumbnailAsset, (AssetReferenceT<Texture>)Field(typeof(OrnamentDefinition), "m_thumbnailAsset").GetValue(ornament), 0, (Texture)null, "automatic Ornament public thumbnail enable");

                var image = SetSubObject(new AssetReferenceSprite("11111111111111111111111111111111"), "source_sprite", typeof(Sprite));
                var sharedTexture = SetSubObject(new AssetReferenceTexture("22222222222222222222222222222222"), "source_texture", typeof(Texture));
                var model = SetSubObject(new AssetReferenceT<GameObject>("33333333333333333333333333333333"), "source_model", typeof(GameObject));
                var priorImage = SetSubObject(new AssetReferenceSprite("44444444444444444444444444444444"), "prior_sprite", typeof(Sprite));
                var priorTexture = SetSubObject(new AssetReferenceTexture("55555555555555555555555555555555"), "prior_texture", typeof(Texture));
                var priorModel = SetSubObject(new AssetReferenceT<GameObject>("66666666666666666666666666666666"), "prior_model", typeof(GameObject));
                var musicValues = new Dictionary<string, object> {
                    { "m_identifier", (HLAudioClipIdentifier)1234567 }, { "m_name", (Strings)(-2345678) }, { "m_composer", (Strings)3456789 },
                    { "m_image", image }, { "m_imageAsTexture", sharedTexture }, { "m_alwaysUnlocked", true },
                    { "m_progressionUnlockWidget", sourceWidget }, { "m_hiddenInJukebox", true } };
                var ornamentValues = new Dictionary<string, object> {
                    { "m_identifier", (OrnamentIdentifier)(-4567890) }, { "m_ornament", model }, { "m_category", OrnamentCategory.Achievement },
                    { "m_unlockedByAchievement", (AchievementIdentifier)5678901 }, { "m_localisedName", (Strings)(-6789012) },
                    { "m_localisedUnlockedLore", (Strings)7890123 }, { "m_localisedLockedTip", (Strings)(-8901234) }, { "m_actNumber", -17 },
                    { "m_thumbnailAsset", sharedTexture }, { "m_thumbnailUncropped", sharedTexture }, { "m_progressionUnlockWidget", sourceWidget } };
                var priorMusicValues = new Dictionary<string, object>(musicValues) {
                    ["m_identifier"] = (HLAudioClipIdentifier)(-1234567), ["m_name"] = (Strings)2345678, ["m_composer"] = (Strings)(-3456789),
                    ["m_image"] = priorImage, ["m_imageAsTexture"] = priorTexture, ["m_alwaysUnlocked"] = false,
                    ["m_progressionUnlockWidget"] = targetWidget, ["m_hiddenInJukebox"] = false };
                var priorOrnamentValues = new Dictionary<string, object>(ornamentValues) {
                    ["m_identifier"] = (OrnamentIdentifier)4567890, ["m_ornament"] = priorModel, ["m_category"] = OrnamentCategory.Story,
                    ["m_unlockedByAchievement"] = (AchievementIdentifier)(-5678901), ["m_localisedName"] = (Strings)6789012,
                    ["m_localisedUnlockedLore"] = (Strings)(-7890123), ["m_localisedLockedTip"] = (Strings)8901234, ["m_actNumber"] = 29,
                    ["m_thumbnailAsset"] = priorTexture, ["m_thumbnailUncropped"] = priorTexture, ["m_progressionUnlockWidget"] = targetWidget };
                const string musicGuid = "authored-music-fixture", ornamentGuid = "authored-ornament-fixture";
                Assign(music, musicValues, musicGuid); Assign(ornament, ornamentValues, ornamentGuid);
                Assign(targetMusic, priorMusicValues, "prior-music-guid"); Assign(targetOrnament, priorOrnamentValues, "prior-ornament-guid");
                Enable(music); Enable(ornament); Enable(targetMusic); Enable(targetOrnament);
                CheckWrapper(music.ImageAsset, image, 0, (Sprite)null, "assigned Music sprite enable");
                CheckWrapper(music.ImageAssetTexture, sharedTexture, 0, (Texture)null, "assigned Music texture enable");
                CheckWrapper(ornament.ThumbnailUncroppedAsset, sharedTexture, 0, (Texture)null, "assigned Ornament uncropped enable");
                CheckWrapper(ornament.ThumbnailAsset, sharedTexture, 0, (Texture)null, "assigned Ornament public thumbnail enable");
                CheckWrapper(targetMusic.ImageAsset, priorImage, 0, (Sprite)null, "prior target Music sprite enable");
                CheckWrapper(targetMusic.ImageAssetTexture, priorTexture, 0, (Texture)null, "prior target Music texture enable");
                CheckWrapper(targetOrnament.ThumbnailUncroppedAsset, priorTexture, 0, (Texture)null, "prior target Ornament uncropped enable");
                CheckWrapper(targetOrnament.ThumbnailAsset, priorTexture, 0, (Texture)null, "prior target Ornament public thumbnail enable");
                EngineRequire(ReferenceEquals(Field(typeof(MusicTrackDefinition), "m_imageAsTexture").GetValue(music), sharedTexture)
                    && ReferenceEquals(Field(typeof(OrnamentDefinition), "m_thumbnailUncropped").GetValue(ornament), sharedTexture)
                    && ReferenceEquals(Field(typeof(OrnamentDefinition), "m_thumbnailAsset").GetValue(ornament), sharedTexture), "three authored slots retain one genuinely aliased package reference");
                EngineRequire(!ReferenceEquals(music.ImageAssetTexture, ornament.ThumbnailUncroppedAsset)
                    && !ReferenceEquals(music.ImageAssetTexture, ornament.ThumbnailAsset)
                    && !ReferenceEquals(ornament.ThumbnailUncroppedAsset, ornament.ThumbnailAsset), "aliased inputs still create three independent real wrapper owners");

                var oldImage = music.ImageAsset; var oldTexture = music.ImageAssetTexture;
                var oldUncropped = ornament.ThumbnailUncroppedAsset; var oldThumbnail = ornament.ThumbnailAsset;
                SeedOwnedCache(oldImage, sprite); SeedOwnedCache(oldTexture, (Texture)texture);
                SeedOwnedCache(oldUncropped, (Texture)texture); SeedOwnedCache(oldThumbnail, (Texture)texture);
                Enable(music); Enable(ornament);
                CheckWrapper(oldImage, image, 7, sprite, "replaced prior Music sprite owner");
                CheckWrapper(oldTexture, sharedTexture, 7, (Texture)texture, "replaced prior Music texture owner");
                CheckWrapper(oldUncropped, sharedTexture, 7, (Texture)texture, "replaced prior Ornament uncropped owner");
                CheckWrapper(oldThumbnail, sharedTexture, 7, (Texture)texture, "replaced prior Ornament public thumbnail owner");
                CheckWrapper(music.ImageAsset, image, 0, (Sprite)null, "repeated Music sprite enable");
                CheckWrapper(music.ImageAssetTexture, sharedTexture, 0, (Texture)null, "repeated Music texture enable");
                CheckWrapper(ornament.ThumbnailUncroppedAsset, sharedTexture, 0, (Texture)null, "repeated Ornament uncropped enable");
                CheckWrapper(ornament.ThumbnailAsset, sharedTexture, 0, (Texture)null, "repeated Ornament public thumbnail enable");
                EngineRequire(!ReferenceEquals(oldImage, music.ImageAsset), "Music repeat replaces sprite wrapper without releasing old owner");
                EngineRequire(!ReferenceEquals(oldTexture, music.ImageAssetTexture), "Music repeat replaces texture wrapper without releasing old owner");
                EngineRequire(!ReferenceEquals(oldUncropped, ornament.ThumbnailUncroppedAsset), "Ornament repeat replaces uncropped wrapper without releasing old owner");
                EngineRequire(!ReferenceEquals(oldThumbnail, ornament.ThumbnailAsset), "Ornament repeat replaces public thumbnail wrapper without releasing old owner");

                var sourceImage = music.ImageAsset; var sourceTexture = music.ImageAssetTexture;
                var sourceUncropped = ornament.ThumbnailUncroppedAsset; var sourceThumbnail = ornament.ThumbnailAsset;
                var targetImage = targetMusic.ImageAsset; var targetTexture = targetMusic.ImageAssetTexture;
                var targetUncropped = targetOrnament.ThumbnailUncroppedAsset; var targetThumbnail = targetOrnament.ThumbnailAsset;
                sourceWidget.SetMaskedImage(texture); targetWidget.SetMaskedImage(texture);
                var sourceBinder = sourceWidget.MaskedTexture; var targetBinder = targetWidget.MaskedTexture;
                int calls = 0; Action<UIWidgetProgression> sourceCallback = _ => ++calls, targetCallback = _ => ++calls;
                sourceWidget.AnimateOutComplete = sourceCallback; targetWidget.AnimateOutComplete = targetCallback;
                int musicId = music.GetInstanceID(), ornamentId = ornament.GetInstanceID();
                int targetMusicId = targetMusic.GetInstanceID(), targetOrnamentId = targetOrnament.GetInstanceID();
                using (var musicData = new SerializedObject(music))
                using (var ornamentData = new SerializedObject(ornament))
                using (var targetMusicData = new SerializedObject(targetMusic))
                using (var targetOrnamentData = new SerializedObject(targetOrnament))
                {
                    CheckShape(music, musicData); CheckShape(ornament, ornamentData);
                    CheckAuthored(music, musicData, musicValues, musicGuid); CheckAuthored(ornament, ornamentData, ornamentValues, ornamentGuid);
                    CheckAuthored(targetMusic, targetMusicData, priorMusicValues, "prior-music-guid"); CheckAuthored(targetOrnament, targetOrnamentData, priorOrnamentValues, "prior-ornament-guid");
                    string musicJson = JsonUtility.ToJson(music), ornamentJson = JsonUtility.ToJson(ornament);
                    CheckJson(music, musicJson, musicGuid); CheckJson(ornament, ornamentJson, ornamentGuid);
                    JsonUtility.FromJsonOverwrite(musicJson, targetMusic); JsonUtility.FromJsonOverwrite(ornamentJson, targetOrnament);
                    EngineRequire(music.GetInstanceID() == musicId && targetMusic.GetInstanceID() == targetMusicId, "real Music JSON overwrite retains source/target engine identities");
                    EngineRequire(ornament.GetInstanceID() == ornamentId && targetOrnament.GetInstanceID() == targetOrnamentId, "real Ornament JSON overwrite retains source/target engine identities");
                    CheckAuthored(targetMusic, targetMusicData, musicValues, musicGuid); CheckAuthored(targetOrnament, targetOrnamentData, ornamentValues, ornamentGuid);
                    CheckAuthored(music, musicData, musicValues, musicGuid); CheckAuthored(ornament, ornamentData, ornamentValues, ornamentGuid);
                    EngineRequire(ReferenceEquals(targetMusic.ImageAsset, targetImage), "JSON leaves target Music sprite runtime wrapper unchanged");
                    EngineRequire(ReferenceEquals(targetMusic.ImageAssetTexture, targetTexture), "JSON leaves target Music texture runtime wrapper unchanged");
                    EngineRequire(ReferenceEquals(targetOrnament.ThumbnailUncroppedAsset, targetUncropped), "JSON leaves target Ornament uncropped runtime wrapper unchanged");
                    EngineRequire(ReferenceEquals(targetOrnament.ThumbnailAsset, targetThumbnail), "JSON excludes unannotated public ThumbnailAsset and leaves its runtime identity unchanged");
                    CheckWrapper(targetImage, priorImage, 0, (Sprite)null, "JSON target retained Music sprite owner");
                    CheckWrapper(targetTexture, priorTexture, 0, (Texture)null, "JSON target retained Music texture owner");
                    CheckWrapper(targetUncropped, priorTexture, 0, (Texture)null, "JSON target retained Ornament uncropped owner");
                    CheckWrapper(targetThumbnail, priorTexture, 0, (Texture)null, "JSON target retained public thumbnail owner");
                    EngineRequire(ReferenceEquals(music.ImageAsset, sourceImage), "JSON leaves source Music sprite runtime wrapper unchanged");
                    EngineRequire(ReferenceEquals(music.ImageAssetTexture, sourceTexture), "JSON leaves source Music texture runtime wrapper unchanged");
                    EngineRequire(ReferenceEquals(ornament.ThumbnailUncroppedAsset, sourceUncropped), "JSON leaves source Ornament uncropped runtime wrapper unchanged");
                    EngineRequire(ReferenceEquals(ornament.ThumbnailAsset, sourceThumbnail), "JSON leaves source public ThumbnailAsset runtime identity unchanged");
                    CheckWrapper(sourceImage, image, 0, (Sprite)null, "JSON source retained Music sprite owner");
                    CheckWrapper(sourceTexture, sharedTexture, 0, (Texture)null, "JSON source retained Music texture owner");
                    CheckWrapper(sourceUncropped, sharedTexture, 0, (Texture)null, "JSON source retained Ornament uncropped owner");
                    CheckWrapper(sourceThumbnail, sharedTexture, 0, (Texture)null, "JSON source retained public thumbnail owner");
                    EngineRequire(ReferenceEquals(sourceWidget.MaskedTexture, sourceBinder) && ReferenceEquals(targetWidget.MaskedTexture, targetBinder)
                        && ReferenceEquals(sourceBinder.Value, texture) && ReferenceEquals(targetBinder.Value, texture)
                        && ReferenceEquals(sourceWidget.AnimateOutComplete, sourceCallback) && ReferenceEquals(targetWidget.AnimateOutComplete, targetCallback)
                        && calls == 0 && ReferenceEquals(sourceWidget.gameObject, sourceOwner) && ReferenceEquals(targetWidget.gameObject, targetOwner), "definition serialization retains real referenced components, binders, callbacks and owners without invoking them");
                }
                Enable(targetMusic); Enable(targetOrnament);
                CheckWrapper(targetMusic.ImageAsset, (AssetReferenceSprite)Field(typeof(MusicTrackDefinition), "m_image").GetValue(targetMusic), 0, (Sprite)null, "post-JSON target Music sprite enable");
                CheckWrapper(targetMusic.ImageAssetTexture, (AssetReferenceTexture)Field(typeof(MusicTrackDefinition), "m_imageAsTexture").GetValue(targetMusic), 0, (Texture)null, "post-JSON target Music texture enable");
                CheckWrapper(targetOrnament.ThumbnailUncroppedAsset, (AssetReferenceTexture)Field(typeof(OrnamentDefinition), "m_thumbnailUncropped").GetValue(targetOrnament), 0, (Texture)null, "post-JSON target Ornament uncropped enable");
                CheckWrapper(targetOrnament.ThumbnailAsset, (AssetReferenceT<Texture>)Field(typeof(OrnamentDefinition), "m_thumbnailAsset").GetValue(targetOrnament), 0, (Texture)null, "post-JSON target Ornament public thumbnail enable");
                EngineRequire(!ReferenceEquals(targetMusic.ImageAsset, targetImage), "post-JSON enable replaces stale target Music sprite owner");
                EngineRequire(!ReferenceEquals(targetMusic.ImageAssetTexture, targetTexture), "post-JSON enable replaces stale target Music texture owner");
                EngineRequire(!ReferenceEquals(targetOrnament.ThumbnailUncroppedAsset, targetUncropped), "post-JSON enable replaces stale target Ornament uncropped owner");
                EngineRequire(!ReferenceEquals(targetOrnament.ThumbnailAsset, targetThumbnail), "post-JSON enable replaces stale public thumbnail owner");
                Field(typeof(MusicTrackDefinition), "m_image").SetValue(music, null); Field(typeof(MusicTrackDefinition), "m_imageAsTexture").SetValue(music, null);
                Field(typeof(MusicTrackDefinition), "m_progressionUnlockWidget").SetValue(music, null);
                Field(typeof(OrnamentDefinition), "m_thumbnailUncropped").SetValue(ornament, null); Field(typeof(OrnamentDefinition), "m_thumbnailAsset").SetValue(ornament, null);
                Field(typeof(OrnamentDefinition), "m_ornament").SetValue(ornament, null); Field(typeof(OrnamentDefinition), "m_progressionUnlockWidget").SetValue(ornament, null);
                Enable(music); Enable(ornament);
                CheckWrapper(music.ImageAsset, null, 0, (Sprite)null, "Music null input sprite enable");
                CheckWrapper(music.ImageAssetTexture, null, 0, (Texture)null, "Music null input texture enable");
                CheckWrapper(ornament.ThumbnailUncroppedAsset, null, 0, (Texture)null, "Ornament null input uncropped enable");
                CheckWrapper(ornament.ThumbnailAsset, null, 0, (Texture)null, "Ornament null input public thumbnail enable");
                EngineRequire(!ReferenceEquals(music.ImageAsset, sourceImage), "null input still replaces Music sprite wrapper");
                EngineRequire(!ReferenceEquals(music.ImageAssetTexture, sourceTexture), "null input still replaces Music texture wrapper");
                EngineRequire(!ReferenceEquals(ornament.ThumbnailUncroppedAsset, sourceUncropped), "null input still replaces Ornament uncropped wrapper");
                EngineRequire(!ReferenceEquals(ornament.ThumbnailAsset, sourceThumbnail), "null input still replaces public thumbnail wrapper");
                EngineRequire(EngineIdentity(music.ProgressionUnlockWidget, null), "Music getter retains genuine engine-null progression reference");
                EngineRequire(EngineIdentity(ornament.ProgressionUnlockWidget, null), "Ornament getter retains genuine engine-null progression reference");
                EngineRequire(ornament.Ornament == null, "Ornament getter retains null real package reference without fallback");
            }
            finally
            {
                for (int i = owned.Count - 1; i >= 0; --i)
                    if (owned[i] != null) UnityEngine.Object.DestroyImmediate(owned[i]);
            }
            EngineRequire(owned.All(value => value == null), "all genuine owned fixtures destroyed in finally");
            if (engineChecks != ExpectedEngineChecks) throw new InvalidOperationException("Unexpected display-definition engine check count: " + engineChecks);
            return engineChecks;
        }
        public static void Run()
        {
            int managed = RunManaged(), engine = RunEngine();
            Debug.Log("Project Lucid mission display-definition proof: source checks=" + managed + "; real engine lifecycle/serialization checks=" + engine
                + "; isolated objects/package references only, no authored owner binding or catalog loading claim");
        }
    }
}
