using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Reflection.Emit;
using System.Security.Cryptography;
using System.Text;
using Hardlight;
using Hardlight.Enums;
using Hardlight.Utils;
using HardlightProject;
using Unity.IL2CPP.CompilerServices;
using UnityEngine;

namespace ProjectLucid
{
    // Bounded proof for five native-derived leaf bodies and an existing maintained definition. This does not execute a mission or authored startup.
    public static class MissionFieldLeavesVerification
    {
        private static int checks;
        private static void Require(bool condition, string description)
        {
            if (!condition) throw new InvalidOperationException(description);
            checks++;
        }
        public static int RunManaged()
        {
            checks = 0;
            var enumFields = typeof(Strings).GetFields(BindingFlags.Public | BindingFlags.Static).OrderBy(f => f.MetadataToken).ToArray();
            Require(typeof(Strings).Assembly.GetName().Name == "HLAutoGenerated" && Enum.GetUnderlyingType(typeof(Strings)) == typeof(int), "original complete localisation enum assembly and underlying type");
            Require(enumFields.Length == 1933 && enumFields.All(f => f.IsLiteral && f.FieldType == typeof(Strings)), "complete original1933 enum literals, without invented methods");
            string canonical = string.Join("\n", enumFields.Select(f => f.Name + "\t" + f.GetRawConstantValue().ToString()));
            using (var sha = SHA256.Create())
                Require(BitConverter.ToString(sha.ComputeHash(Encoding.UTF8.GetBytes(canonical))).Replace("-", "").ToLowerInvariant() == "6f6707b15c1bb60dd108ee1d6b61925ed1acaf3f60dcb186f9146cd89b5b9dea", "all original ordered enum names and signed values match metadata");
            Type island = typeof(GameplayIslandDefinition);
            Type tips = typeof(GameTipsDefinition);
            Type start = typeof(LevelStartPositionDefinition);
            Require(island.Assembly.GetName().Name == "Game.Runtime" && tips.Assembly == island.Assembly && start.Assembly == island.Assembly, "original Game.Runtime identity");
            Require(island.BaseType == typeof(ScriptableObjectWithGuid) && start.BaseType == typeof(ScriptableObjectWithGuid), "original GUID base identities");
            Require(tips.BaseType == typeof(ScriptableObject), "tips has plain ScriptableObject base");
            FieldInfo[] fields(Type t) => t.GetFields(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.Static | BindingFlags.DeclaredOnly).OrderBy(f => f.MetadataToken).ToArray();
            Require(fields(island).Select(f => f.Name).SequenceEqual(new[] { "m_localisedId", "m_visibleIslands" }), "island original complete own field order");
            Require(fields(tips).Select(f => f.Name).SequenceEqual(new[] { "m_tipIds" }), "tips original complete own field order");
            Require(fields(start).Length == 0, "start definition genuinely has no own fields");
            Require(fields(island)[0].FieldType == typeof(Strings) && fields(island)[1].FieldType == typeof(List<GameplayIslandDefinition>), "island original complete field types");
            Require(fields(tips)[0].FieldType == typeof(List<Strings>), "tips original field type");
            Require(fields(island).Concat(fields(tips)).All(f => f.IsPrivate && f.IsDefined(typeof(SerializeField), false)), "all original own field visibility and SerializeField attributes");
            Require(fields(island)[0].IsDefined(typeof(HashEnumAttribute), false) && fields(tips)[0].IsDefined(typeof(HashEnumAttribute), false), "original HashEnum attribute identity");
            foreach (Type t in new[] { island, tips, start })
            {
                var options = t.GetCustomAttributes<Il2CppSetOptionAttribute>(false).ToArray();
                Require(options.Length == 2 && options.Any(a => a.Option == Option.NullChecks && a.Value.Equals(false)) && options.Any(a => a.Option == Option.ArrayBoundsChecks && a.Value.Equals(false)), t.Name + " original player IL2CPP options");
                var menu = t.GetCustomAttribute<CreateAssetMenuAttribute>(false);
                Require(menu != null && menu.fileName == t.Name && menu.menuName == "HardlightProject/DefinitionData/Definitions/" + t.Name, t.Name + " original creation metadata");
            }
            var islandCode = ReadIL(island.GetConstructor(Type.EmptyTypes)).ToArray();
            Require(islandCode.Count(i => i.op == OpCodes.Stfld) == 1 && ((FieldInfo)islandCode.Single(i => i.op == OpCodes.Stfld).value).Name == "m_localisedId", "native constructor has only original key assignment");
            Require(islandCode.Any(i => i.op == OpCodes.Ldc_I4 && (int)i.value == -1225125244), "native Strings.NONE exact literal");
            Require(islandCode.FindIndex(i => i.op == OpCodes.Stfld) < islandCode.FindIndex(i => i.op == OpCodes.Call && ((MethodBase)i.value).DeclaringType == typeof(ScriptableObjectWithGuid)), "native key initializer precedes GUID base call");
            foreach (Type t in new[] { tips, start })
            {
                var code = ReadIL(t.GetConstructor(Type.EmptyTypes)).ToArray();
                Require(!code.Any(i => i.op == OpCodes.Stfld || i.op == OpCodes.Newobj), t.Name + " native constructor does not invent fields or lists");
                Require(code.Count(i => i.op == OpCodes.Call && ((MethodBase)i.value).IsConstructor && ((MethodBase)i.value).DeclaringType == t.BaseType) == 1, t.Name + " native exact base constructor");
            }
            RequireGetter(island.GetProperty("VisibleIslands"), "m_visibleIslands");
            RequireGetter(island.GetProperty("LocalisedId"), "m_localisedId");
            RequireGetter(tips.GetProperty("TipIds"), "m_tipIds");
            return checks;
        }
        private static void RequireGetter(PropertyInfo property, string field)
        {
            var code = ReadIL(property.GetMethod).Where(i => i.op != OpCodes.Nop).ToArray();
            Require(code.Length == 3 && code[0].op == OpCodes.Ldarg_0 && code[1].op == OpCodes.Ldfld && ((FieldInfo)code[1].value).Name == field && code[2].op == OpCodes.Ret, property.Name + " native direct field getter");
        }
        private static IEnumerable<(OpCode op, object value)> ReadIL(MethodBase method)
        {
            byte[] il = method.GetMethodBody().GetILAsByteArray();
            var codes = typeof(OpCodes).GetFields(BindingFlags.Public | BindingFlags.Static).Where(f => f.FieldType == typeof(OpCode)).Select(f => (OpCode)f.GetValue(null)).ToDictionary(o => o.Value);
            for (int p = 0; p < il.Length;)
            {
                short key = il[p++];
                if (key == 0xfe) key = (short)(0xfe00 | il[p++]);
                OpCode op = codes[key]; object value = null;
                switch (op.OperandType)
                {
                    case OperandType.InlineNone: break;
                    case OperandType.ShortInlineI: value = (sbyte)il[p++]; break;
                    case OperandType.InlineI: value = BitConverter.ToInt32(il, p); p += 4; break;
                    case OperandType.InlineField: value = method.Module.ResolveField(BitConverter.ToInt32(il,p)); p += 4; break;
                    case OperandType.InlineMethod: value = method.Module.ResolveMethod(BitConverter.ToInt32(il,p)); p += 4; break;
                    default: throw new InvalidOperationException("Unexpected bounded constructor/getter IL: " + op);
                }
                yield return (op,value);
            }
        }
        public static void Run()
        {
            RunManaged();
            var island = ScriptableObject.CreateInstance<GameplayIslandDefinition>();
            var other = ScriptableObject.CreateInstance<GameplayIslandDefinition>();
            var tips = ScriptableObject.CreateInstance<GameTipsDefinition>();
            var start = ScriptableObject.CreateInstance<LevelStartPositionDefinition>();
            try
            {
                Require(island.LocalisedId == Strings.NONE && (int)island.LocalisedId == -1225125244, "native key default on genuine Unity instance");
                Require(island.VisibleIslands == null && tips.TipIds == null, "native list fields remain null on genuine instances");
                var visible = new List<GameplayIslandDefinition> { other, island, other };
                typeof(GameplayIslandDefinition).GetField("m_visibleIslands", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(island, visible);
                Require(ReferenceEquals(island.VisibleIslands, visible), "getter retains original list identity");
                visible.Add(null);
                Require(island.VisibleIslands.Count == 4 && island.VisibleIslands[3] == null, "getter exposes duplicates/self/null and live changes");
                var strings = new List<Strings> { Strings.NONE, (Strings)0, Strings.NONE };
                typeof(GameTipsDefinition).GetField("m_tipIds", BindingFlags.NonPublic | BindingFlags.Instance).SetValue(tips, strings);
                Require(ReferenceEquals(tips.TipIds, strings) && tips.TipIds.Count == 3, "tips list identity/duplicate/default keys preserved");
                string json = JsonUtility.ToJson(island);
                Require(json.Contains("m_localisedId") && json.Contains("m_visibleIslands"), "genuine Unity island serializes both original own fields");
                Require(JsonUtility.ToJson(tips).Contains("m_tipIds"), "genuine Unity tips serializes its original own field");
                Require(start is ScriptableObjectWithGuid && start != null, "genuine empty marker retains original GUID base");
                Debug.Log("Project Lucid mission field leaves: PASS checks=" + checks);
            }
            finally
            {
                UnityEngine.Object.DestroyImmediate(start); UnityEngine.Object.DestroyImmediate(tips);
                UnityEngine.Object.DestroyImmediate(other); UnityEngine.Object.DestroyImmediate(island);
            }
        }
    }
    internal static class MissionProofArrayHelpers
    {
        internal static int FindIndex<T>(this T[] array, Func<T, bool> predicate) => Array.FindIndex(array, x => predicate(x));
    }
}
