using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using Hardlight;
using HardlightProject;
using Unity.IL2CPP.CompilerServices;
using UnityEngine;

namespace ProjectLucid.Editor
{
    public static class OriginalLayerComparisonVerification
    {
        private const BindingFlags Own = BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static | BindingFlags.Instance | BindingFlags.DeclaredOnly;
        private static void Check(bool condition, string witness, ref int checks)
        { if (!condition) throw new InvalidOperationException(witness); ++checks; }

        public static int RunOriginalDeclarations()
        {
            int checks = 0;
            Type[] owners = { typeof(LayerMaskExtensions), typeof(ComparisonTypeExtensions) };
            string[] fullNames = { "Hardlight.LayerMaskExtensions", "HardlightProject.ComparisonTypeExtensions" };
            string[] assemblies = { "HLUnityCore.Runtime", "Game.Runtime" };
            for (int i = 0; i < owners.Length; i++)
            {
                Type type = owners[i];
                Check(type.FullName == fullNames[i] && type.Assembly.GetName().Name == assemblies[i]
                    && (int)type.Attributes == 1048961, "original fieldless extension owner identity", ref checks);
                Check(type.BaseType == typeof(object) && type.IsAbstract && type.IsSealed
                    && type.GetFields(Own).Length == 0 && type.GetProperties(Own).Length == 0
                    && type.GetNestedTypes(Own).Length == 0, "complete static owner shape", ref checks);
                Check(type.GetMethods(Own).Length == (i == 0 ? 4 : 2) && type.GetConstructors(Own).Length == 0,
                    "complete original method count", ref checks);
                Check(type.IsDefined(typeof(ExtensionAttribute), false), "authentic extension owner marker", ref checks);
            }
            Method(owners[0], "AddLayer", typeof(void), new[] { typeof(LayerMask).MakeByRefType(), typeof(int) }, new[] { "mask", "layer" }, ref checks);
            Method(owners[0], "RemoveLayer", typeof(void), new[] { typeof(LayerMask).MakeByRefType(), typeof(int) }, new[] { "mask", "layer" }, ref checks);
            Method(owners[0], "IncludesLayer", typeof(bool), new[] { typeof(LayerMask), typeof(int) }, new[] { "mask", "layer" }, ref checks);
            Method(owners[0], "IncludesLayer", typeof(bool), new[] { typeof(LayerMask), typeof(GameObject) }, new[] { "mask", "gameObject" }, ref checks);
            Method(owners[1], "Evaluate", typeof(bool), new[] { typeof(ComparisonType), typeof(float), typeof(float) }, new[] { "comparisonType", "value", "criteria" }, ref checks);
            Method(owners[1], "Evaluate", typeof(bool), new[] { typeof(ComparisonType), typeof(int), typeof(int) }, new[] { "comparisonType", "value", "criteria" }, ref checks);
            var options = owners[1].GetCustomAttributesData().Where(x => x.AttributeType == typeof(Il2CppSetOptionAttribute)).ToArray();
            Check(options.Length == 2 && (int)options[0].ConstructorArguments[0].Value == 1
                && (int)options[1].ConstructorArguments[0].Value == 2
                && options.All(x => x.ConstructorArguments[1].Value is bool value && !value),
                "original Comparison options Null then ArrayBounds false", ref checks);
            Check(!owners[0].IsDefined(typeof(Il2CppSetOptionAttribute), false), "original Layer owner has no compiler-option attributes", ref checks);
            ComparisonType[] ops = Operations();
            int[] literals = { 0, 637544632, -1672765598, 803474623, 2070626358, 1167406326, -784979190 };
            for (int i = 0; i < ops.Length; i++) Check((int)ops[i] == literals[i], "original serialized comparison literal", ref checks);
            Check(typeof(ComparisonType).Assembly.GetName().Name == "HLAutoGenerated"
                && Enum.GetUnderlyingType(typeof(ComparisonType)) == typeof(int)
                && Enum.GetValues(typeof(ComparisonType)).Length == 7, "genuine original enum owner and complete literals", ref checks);
            return checks;
        }
        private static void Method(Type owner, string name, Type result, Type[] types, string[] names, ref int checks)
        {
            MethodInfo method = owner.GetMethod(name, Own, null, types, null);
            Check(method != null && (int)method.Attributes == 150 && method.ReturnType == result && !method.IsGenericMethod,
                "original public static method declaration", ref checks);
            Check(method.IsDefined(typeof(ExtensionAttribute), false), "authentic extension method marker", ref checks);
            ParameterInfo[] parameters = method.GetParameters();
            Check(parameters.Select(p => p.ParameterType).SequenceEqual(types)
                && parameters.All(p => (int)p.Attributes == 0 && !p.HasDefaultValue), "original ref/value parameters without defaults", ref checks);
            Check(parameters.Select(p => p.Name).SequenceEqual(names), "original parameter names", ref checks);
        }
        private static ComparisonType[] Operations()
            => new[] { ComparisonType.None, ComparisonType.Equal, ComparisonType.NotEqual,
                ComparisonType.GreaterThan, ComparisonType.GreaterThanEqual, ComparisonType.LessThan, ComparisonType.LessThanEqual };

        private readonly struct MaskVector
        {
            public readonly uint Initial, Added, Removed;
            public readonly int Layer;
            public readonly bool InitiallyIncluded;
            public MaskVector(uint initial, int layer, uint added, uint removed, bool included)
            { Initial = initial; Layer = layer; Added = added; Removed = removed; InitiallyIncluded = included; }
        }
        public static int RunFixedLayerBitVectors()
        {
            int checks = 0;
            // Fixed output words, independently pinned to original LSLV/LSRV and BTS/BTR/BT low-five-bit
            // witnesses. The fixture does not compute expected words with the implementation.
            MaskVector[] rows = {
                new MaskVector(0, 0, 1, 0, false), new MaskVector(0, 31, 0x80000000u, 0, false),
                new MaskVector(0, -1, 0x80000000u, 0, false), new MaskVector(0, 32, 1, 0, false),
                new MaskVector(0, -32, 1, 0, false), new MaskVector(0, 33, 2, 0, false),
                new MaskVector(0, int.MinValue, 1, 0, false), new MaskVector(0, int.MaxValue, 0x80000000u, 0, false),
                new MaskVector(0xffffffffu, 31, 0xffffffffu, 0x7fffffffu, true),
                new MaskVector(0x80000001u, -1, 0x80000001u, 1, true),
                new MaskVector(0x55555555u, -31, 0x55555557u, 0x55555555u, false),
                new MaskVector(0xaaaaaaaau, 0, 0xaaaaaaabu, 0xaaaaaaaau, false),
                new MaskVector(0xaaaaaaabu, 32, 0xaaaaaaabu, 0xaaaaaaaau, true)
            };
            foreach (MaskVector row in rows)
            {
                LayerMask mask = unchecked((int)row.Initial);
                Check(mask.IncludesLayer(row.Layer) == row.InitiallyIncluded, "original initial inclusion", ref checks);
                mask.AddLayer(row.Layer);
                Check(unchecked((uint)mask.value) == row.Added, "ref caller receives fixed added word", ref checks);
                Check(mask.IncludesLayer(row.Layer), "wrapped layer included after add", ref checks);
                mask.AddLayer(row.Layer);
                Check(unchecked((uint)mask.value) == row.Added, "adding existing bit is idempotent", ref checks);
                mask.RemoveLayer(row.Layer);
                Check(unchecked((uint)mask.value) == row.Removed, "ref caller receives fixed removed word", ref checks);
                Check(!mask.IncludesLayer(row.Layer), "wrapped bit excluded after remove", ref checks);
                mask.RemoveLayer(row.Layer);
                Check(unchecked((uint)mask.value) == row.Removed, "removing absent bit is idempotent", ref checks);
            }
            return checks;
        }

        public static int RunAuthoredGameObjectLayers()
        {
            int checks = 0;
            GameObject authored = null;
            try
            {
                authored = new GameObject("OriginalLayerComparison_PrivateFixture");
                authored.hideFlags = HideFlags.HideAndDontSave;
                LayerMask mask = unchecked((int)0x80000001u);
                int[] layers = { 0, 1, 30, 31 };
                bool[] included = { true, false, false, true };
                for (int i = 0; i < layers.Length; i++)
                {
                    authored.layer = layers[i];
                    Check(authored.layer == layers[i], "real GameObject stores authored layer", ref checks);
                    Check(mask.IncludesLayer(authored) == included[i], "GameObject overload reads real authored layer", ref checks);
                    Check(unchecked((uint)mask.value) == 0x80000001u, "value overload leaves caller mask unchanged", ref checks);
                }
                // Original Get_layer occurs before inclusion; even an empty mask does
                // not short-circuit a null object. Only newly-created object is destroyed.
                NullObjectFault((LayerMask)0, ref checks);
                NullObjectFault((LayerMask)(-1), ref checks);
            }
            finally { if (authored != null) UnityEngine.Object.DestroyImmediate(authored); }
            return checks;
        }
        private static void NullObjectFault(LayerMask mask, ref int checks)
        {
            try { mask.IncludesLayer((GameObject)null); }
            catch (NullReferenceException) { ++checks; return; }
            throw new InvalidOperationException("original unguarded GameObject.layer null fault");
        }

        private readonly struct FloatVector
        {
            public readonly uint Left, Right;
            public readonly string Truth;
            public FloatVector(uint left, uint right, string truth) { Left = left; Right = right; Truth = truth; }
        }
        private static float Bits(uint bits) => BitConverter.ToSingle(BitConverter.GetBytes(bits), 0);
        public static int RunFixedFloatComparisons()
        {
            int checks = 0;
            // Columns: None,Equal,NotEqual,Greater,GreaterEqual,Less,LessEqual.
            // Truth strings are fixed independent witnesses: close binary32 inputs
            // remain approximately equal while their ordered comparisons differ.
            FloatVector[] rows = {
                new FloatVector(0xc0000000u, 0xbf800000u, "1010011"),
                new FloatVector(0x40000000u, 0x3f800000u, "1011100"),
                new FloatVector(0x3f800000u, 0x3f800000u, "1100101"),
                new FloatVector(0x3f800000u, 0x3f800004u, "1100011"),
                new FloatVector(0x3f800004u, 0x3f800000u, "1101100"),
                new FloatVector(0x3f800000u, 0x3f800011u, "1010011"),
                new FloatVector(0, 0, "1100101"), new FloatVector(0x80000000u, 0, "1100101"),
                new FloatVector(0, 0x1e3ce508u, "1010011"),
                new FloatVector(0x7fc00000u, 0x7fc00000u, "1010000"),
                new FloatVector(0x7fc00000u, 0x3f800000u, "1010000"),
                new FloatVector(0x3f800000u, 0x7fc00000u, "1010000"),
                new FloatVector(0x7f800000u, 0x7f800000u, "1010101"),
                new FloatVector(0xff800000u, 0xff800000u, "1010101"),
                new FloatVector(0x7f800000u, 0xff800000u, "1011100"),
                new FloatVector(0xff800000u, 0x7f800000u, "1010011"),
                new FloatVector(0x7f800000u, 0x7f7fffffu, "1011100"),
                new FloatVector(0x7f7fffffu, 0x7f800000u, "1010011"),
                new FloatVector(0x7f7fffffu, 0x7f7fffffu, "1100101"),
                new FloatVector(0xff7fffffu, 0x7f7fffffu, "1010011"),
                new FloatVector(0x60ad78ecu, 0x60ad78edu, "1100011"),
                new FloatVector(0x1e3ce508u, 0, "1011100")
            };
            ComparisonType[] ops = Operations();
            foreach (FloatVector row in rows)
                for (int i = 0; i < ops.Length; i++)
                    Check(ops[i].Evaluate(Bits(row.Left), Bits(row.Right)) == (row.Truth[i] == '1'),
                        "fixed native float relation " + ops[i] + " " + row.Left.ToString("X8") + "/" + row.Right.ToString("X8"), ref checks);
            return checks;
        }

        public static int RunFixedSignedIntegerComparisons()
        {
            int checks = 0;
            int[] left = { int.MinValue, int.MaxValue, int.MinValue, int.MaxValue, -1, 0, 0, 1, 7, -7, int.MinValue + 1, int.MaxValue };
            int[] right = { int.MaxValue, int.MinValue, int.MinValue, int.MaxValue, 0, -1, 0, 1, 5, -5, int.MinValue, int.MaxValue - 1 };
            string[] truth = { "1010011", "1011100", "1100101", "1100101", "1010011", "1011100", "1100101", "1100101", "1011100", "1010011", "1011100", "1011100" };
            ComparisonType[] ops = Operations();
            for (int row = 0; row < left.Length; row++)
                for (int i = 0; i < ops.Length; i++)
                    Check(ops[i].Evaluate(left[row], right[row]) == (truth[row][i] == '1'), "fixed signed integer relation " + ops[i], ref checks);
            return checks;
        }
        public static int RunOriginalUnknownOperationErrors()
        {
            int checks = 0;
            int[] invalid = { 123, -1, int.MinValue };
            string[] formatted = { "0x0000007B", "0xFFFFFFFF", "0x80000000" };
            // The genuine GetString caches unknown values in its mutable table.
            // Preserve that runtime behavior while isolating this fixture's misses
            // from the complete original table verification and other consumers.
            FieldInfo tableField = typeof(HardlightEnumExtensions).GetField("ComparisonTypeEnumToString",
                BindingFlags.NonPublic | BindingFlags.Static);
            var table = (Dictionary<ComparisonType, string>)tableField.GetValue(null);
            var before = new Dictionary<ComparisonType, string>(table);
            try
            {
                foreach (int value in invalid) table.Remove((ComparisonType)value);
                for (int row = 0; row < invalid.Length; row++)
                    for (int overload = 0; overload < 2; overload++)
                    {
                        ArgumentOutOfRangeException failure = null;
                        try
                        {
                            if (overload == 0) ((ComparisonType)invalid[row]).Evaluate(1f, 2f);
                            else ((ComparisonType)invalid[row]).Evaluate(int.MinValue, int.MaxValue);
                        }
                        catch (ArgumentOutOfRangeException error) { failure = error; }
                        Check(failure != null && failure.ParamName == "comparisonType", "original exception and parameter name", ref checks);
                        Check(failure.ActualValue is ComparisonType boxed && (int)boxed == invalid[row], "original boxed enum actual value", ref checks);
                        Check(failure.Message.StartsWith("Comparison type " + formatted[row] + " is not implemented for "
                            + (overload == 0 ? "float." : "int."), StringComparison.Ordinal), "original literal/GetString exception message", ref checks);
                    }
            }
            finally
            {
                table.Clear();
                foreach (var entry in before) table.Add(entry.Key, entry.Value);
                if (!ReferenceEquals(tableField.GetValue(null), table) || table.Count != before.Count
                    || before.Any(entry => !table.TryGetValue(entry.Key, out string value) || !ReferenceEquals(value, entry.Value)))
                    throw new InvalidOperationException("Original comparison string table identity and entries must survive fixture isolation");
            }
            return checks;
        }
    }
}
