using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Mono.Cecil;
using Unity.CompilationPipeline.Common.Diagnostics;
using Unity.CompilationPipeline.Common.ILPostProcessing;

namespace ProjectLucid.CodeGen
{
    // Original marker interfaces genuinely have no
    // members. Restore only the original concrete MethodDef flag bits; no method
    // bodies, marker contracts, fields, scopes, tokens or symbols are rewritten.
    public sealed class CodecMethodFlagsPostProcessor : ILPostProcessor
    {
        public override ILPostProcessor GetInstance() => new CodecMethodFlagsPostProcessor();
        public override bool WillProcess(ICompiledAssembly assembly) => assembly.Name == "HLAutoGenerated";

        public override ILPostProcessResult Process(ICompiledAssembly assembly)
        {
            if (!WillProcess(assembly)) return null;
            try
            {
                byte[] result = CodecFlags.Restore(assembly.InMemoryAssembly.PeData, assembly.References);
                return new ILPostProcessResult(new InMemoryAssembly(result, assembly.InMemoryAssembly.PdbData));
            }
            catch (Exception error) when (error is InvalidDataException || error is IOException || error is InvalidOperationException || error is AssemblyResolutionException || error is BadImageFormatException || error is OverflowException || error is ArgumentException || error is IndexOutOfRangeException)
            {
                // Never return partially patched bytes. Unity's Error diagnostic
                // must stop compilation until the exact source graph is present.
                return new ILPostProcessResult(assembly.InMemoryAssembly, new List<DiagnosticMessage> {
                    new DiagnosticMessage { DiagnosticType = DiagnosticType.Error, MessageData = "Codec metadata restoration refused: " + error.Message }
                });
            }
        }
    }

    internal static class CodecFlags
    {
        private const ushort AddedFlags = 0x0160; // Final | Virtual | NewSlot
        private sealed class Contract
        {
            internal readonly string Name;
            internal readonly int Flags;
            internal readonly string[] Fields, Methods;
            internal Contract(string name, int flags, string[] fields, string[] methods)
            { Name = name; Flags = flags; Fields = fields; Methods = methods; }
        }

        private static readonly Contract[] Contracts = new Contract[] {
            new Contract("ClientDataAPI.LocalisedString", 1048833, new string[] {
                "ID|32854|System.Int32|netstandard|-1700661691",
                "NUM_ARGS_DEFAULT|54|System.Int32|netstandard|-",
                "m_id|1|System.String|netstandard|-",
                "m_content|1|System.String|netstandard|-",
                "m_numArgs|1|System.Int32|netstandard|-",
                "s_encodeInstance|17|ClientDataAPI.LocalisedString|HLAutoGenerated.dll|-",
                "m_poolAcquired|1|System.Boolean|netstandard|-",
                "s_poolNumAcquired|17|System.Int32|netstandard|-",
                "s_poolSize|17|System.Int32|netstandard|-",
                "s_poolInstances|17|ClientDataAPI.LocalisedString[]|HLAutoGenerated.dll|-",
            }, new string[] {
                "get_MessageId|2182|System.Int32|netstandard|",
                "get_Id|2182|System.String|netstandard|",
                "set_Id|2182|System.Void|netstandard|System.String@netstandard#0",
                "get_Content|2182|System.String|netstandard|",
                "set_Content|2182|System.Void|netstandard|System.String@netstandard#0",
                "get_NumArgs|2182|System.Int32|netstandard|",
                "set_NumArgs|2182|System.Void|netstandard|System.Int32@netstandard#0",
                "GetEncodingInstance|150|ClientDataAPI.LocalisedString|HLAutoGenerated.dll|",
                ".ctor|6278|System.Void|netstandard|",
                "Reset|134|System.Void|netstandard|",
                "PoolAcquire|150|ClientDataAPI.LocalisedString|HLAutoGenerated.dll|",
                "PoolRelease|134|System.Void|netstandard|",
                "PoolNumAcquired|150|System.Int32|netstandard|",
                "PoolResize|150|System.Void|netstandard|System.Int32@netstandard#0",
                "encodedLength|134|System.Int32|netstandard|",
                "encode|134|System.Byte[]|netstandard|",
                "encode|134|System.Void|netstandard|NetworkBuffer&@HLNetworking.Runtime#0",
                "encode|129|System.Void|netstandard|NetworkBuffer&@HLNetworking.Runtime#0,System.Int32@netstandard#0",
                "decode|150|ClientDataAPI.LocalisedString|HLAutoGenerated.dll|System.Byte[]@netstandard#0",
                "decode|150|ClientDataAPI.LocalisedString|HLAutoGenerated.dll|System.Byte[]@netstandard#0,System.Int32@netstandard#0,System.Int32@netstandard#0",
                "decode|150|ClientDataAPI.LocalisedString|HLAutoGenerated.dll|NetworkBuffer&@HLNetworking.Runtime#0,System.Int32@netstandard#0",
                "decode|150|ClientDataAPI.LocalisedString|HLAutoGenerated.dll|NetworkBuffer&@HLNetworking.Runtime#0",
                "decodeInto|134|System.Void|netstandard|NetworkBuffer&@HLNetworking.Runtime#0",
                ".cctor|6289|System.Void|netstandard|",
            }),
            new Contract("ClientDataAPI.StringTable", 1048833, new string[] {
                "ID|32854|System.Int32|netstandard|146798109",
                "LANGUAGE_DEFAULT|54|System.Int32|netstandard|-",
                "m_language|1|System.Int32|netstandard|-",
                "m_strings|1|ClientDataAPI.LocalisedString[]|HLAutoGenerated.dll|-",
                "m_hash|1|System.String|netstandard|-",
                "s_encodeInstance|17|ClientDataAPI.StringTable|HLAutoGenerated.dll|-",
                "m_poolAcquired|1|System.Boolean|netstandard|-",
                "s_poolNumAcquired|17|System.Int32|netstandard|-",
                "s_poolSize|17|System.Int32|netstandard|-",
                "s_poolInstances|17|ClientDataAPI.StringTable[]|HLAutoGenerated.dll|-",
            }, new string[] {
                "get_MessageId|2182|System.Int32|netstandard|",
                "get_Language|2182|System.Int32|netstandard|",
                "set_Language|2182|System.Void|netstandard|System.Int32@netstandard#0",
                "get_Strings|2182|ClientDataAPI.LocalisedString[]|HLAutoGenerated.dll|",
                "set_Strings|2182|System.Void|netstandard|ClientDataAPI.LocalisedString[]@HLAutoGenerated.dll#0",
                "get_Hash|2182|System.String|netstandard|",
                "set_Hash|2182|System.Void|netstandard|System.String@netstandard#0",
                "GetEncodingInstance|150|ClientDataAPI.StringTable|HLAutoGenerated.dll|",
                ".ctor|6278|System.Void|netstandard|",
                "Reset|134|System.Void|netstandard|",
                "PoolAcquire|150|ClientDataAPI.StringTable|HLAutoGenerated.dll|",
                "PoolRelease|134|System.Void|netstandard|",
                "PoolNumAcquired|150|System.Int32|netstandard|",
                "PoolResize|150|System.Void|netstandard|System.Int32@netstandard#0",
                "encodedLength|134|System.Int32|netstandard|",
                "encode|134|System.Byte[]|netstandard|",
                "encode|134|System.Void|netstandard|NetworkBuffer&@HLNetworking.Runtime#0",
                "encode|129|System.Void|netstandard|NetworkBuffer&@HLNetworking.Runtime#0,System.Int32@netstandard#0",
                "decode|150|ClientDataAPI.StringTable|HLAutoGenerated.dll|System.Byte[]@netstandard#0",
                "decode|150|ClientDataAPI.StringTable|HLAutoGenerated.dll|System.Byte[]@netstandard#0,System.Int32@netstandard#0,System.Int32@netstandard#0",
                "decode|150|ClientDataAPI.StringTable|HLAutoGenerated.dll|NetworkBuffer&@HLNetworking.Runtime#0,System.Int32@netstandard#0",
                "decode|150|ClientDataAPI.StringTable|HLAutoGenerated.dll|NetworkBuffer&@HLNetworking.Runtime#0",
                "decodeInto|134|System.Void|netstandard|NetworkBuffer&@HLNetworking.Runtime#0",
                ".cctor|6289|System.Void|netstandard|",
            }),
            new Contract("ClientDataAPI.SupportedLanguage", 1048833, new string[] {
                "ID|32854|System.Int32|netstandard|-1632469498",
                "LANGUAGE_DEFAULT|54|System.Int32|netstandard|-",
                "LOCALISED_NAME_DEFAULT|54|System.Int32|netstandard|-",
                "m_language|1|System.Int32|netstandard|-",
                "m_localisedName|1|System.Int32|netstandard|-",
                "m_isRTL|1|System.Boolean|netstandard|-",
                "s_encodeInstance|17|ClientDataAPI.SupportedLanguage|HLAutoGenerated.dll|-",
                "m_poolAcquired|1|System.Boolean|netstandard|-",
                "s_poolNumAcquired|17|System.Int32|netstandard|-",
                "s_poolSize|17|System.Int32|netstandard|-",
                "s_poolInstances|17|ClientDataAPI.SupportedLanguage[]|HLAutoGenerated.dll|-",
            }, new string[] {
                "get_MessageId|2182|System.Int32|netstandard|",
                "get_Language|2182|System.Int32|netstandard|",
                "set_Language|2182|System.Void|netstandard|System.Int32@netstandard#0",
                "get_LocalisedName|2182|System.Int32|netstandard|",
                "set_LocalisedName|2182|System.Void|netstandard|System.Int32@netstandard#0",
                "get_IsRTL|2182|System.Boolean|netstandard|",
                "set_IsRTL|2182|System.Void|netstandard|System.Boolean@netstandard#0",
                "GetEncodingInstance|150|ClientDataAPI.SupportedLanguage|HLAutoGenerated.dll|",
                ".ctor|6278|System.Void|netstandard|",
                "Reset|134|System.Void|netstandard|",
                "PoolAcquire|150|ClientDataAPI.SupportedLanguage|HLAutoGenerated.dll|",
                "PoolRelease|134|System.Void|netstandard|",
                "PoolNumAcquired|150|System.Int32|netstandard|",
                "PoolResize|150|System.Void|netstandard|System.Int32@netstandard#0",
                "encodedLength|134|System.Int32|netstandard|",
                "encode|134|System.Byte[]|netstandard|",
                "encode|134|System.Void|netstandard|NetworkBuffer&@HLNetworking.Runtime#0",
                "encode|129|System.Void|netstandard|NetworkBuffer&@HLNetworking.Runtime#0,System.Int32@netstandard#0",
                "decode|150|ClientDataAPI.SupportedLanguage|HLAutoGenerated.dll|System.Byte[]@netstandard#0",
                "decode|150|ClientDataAPI.SupportedLanguage|HLAutoGenerated.dll|System.Byte[]@netstandard#0,System.Int32@netstandard#0,System.Int32@netstandard#0",
                "decode|150|ClientDataAPI.SupportedLanguage|HLAutoGenerated.dll|NetworkBuffer&@HLNetworking.Runtime#0,System.Int32@netstandard#0",
                "decode|150|ClientDataAPI.SupportedLanguage|HLAutoGenerated.dll|NetworkBuffer&@HLNetworking.Runtime#0",
                "decodeInto|134|System.Void|netstandard|NetworkBuffer&@HLNetworking.Runtime#0",
                ".cctor|6289|System.Void|netstandard|",
            }),
            new Contract("ClientDataAPI.LocalisationDefinitions", 1048833, new string[] {
                "ID|32854|System.Int32|netstandard|1007235840",
                "m_supportedLanguages|1|ClientDataAPI.SupportedLanguage[]|HLAutoGenerated.dll|-",
                "m_stringTable|1|ClientDataAPI.StringTable|HLAutoGenerated.dll|-",
                "s_encodeInstance|17|ClientDataAPI.LocalisationDefinitions|HLAutoGenerated.dll|-",
                "m_poolAcquired|1|System.Boolean|netstandard|-",
                "s_poolNumAcquired|17|System.Int32|netstandard|-",
                "s_poolSize|17|System.Int32|netstandard|-",
                "s_poolInstances|17|ClientDataAPI.LocalisationDefinitions[]|HLAutoGenerated.dll|-",
            }, new string[] {
                "get_MessageId|2182|System.Int32|netstandard|",
                "get_SupportedLanguages|2182|ClientDataAPI.SupportedLanguage[]|HLAutoGenerated.dll|",
                "set_SupportedLanguages|2182|System.Void|netstandard|ClientDataAPI.SupportedLanguage[]@HLAutoGenerated.dll#0",
                "get_StringTable|2182|ClientDataAPI.StringTable|HLAutoGenerated.dll|",
                "set_StringTable|2182|System.Void|netstandard|ClientDataAPI.StringTable@HLAutoGenerated.dll#0",
                "GetEncodingInstance|150|ClientDataAPI.LocalisationDefinitions|HLAutoGenerated.dll|",
                ".ctor|6278|System.Void|netstandard|",
                "Reset|134|System.Void|netstandard|",
                "PoolAcquire|150|ClientDataAPI.LocalisationDefinitions|HLAutoGenerated.dll|",
                "PoolRelease|134|System.Void|netstandard|",
                "PoolNumAcquired|150|System.Int32|netstandard|",
                "PoolResize|150|System.Void|netstandard|System.Int32@netstandard#0",
                "encodedLength|134|System.Int32|netstandard|",
                "encode|134|System.Byte[]|netstandard|",
                "encode|134|System.Void|netstandard|NetworkBuffer&@HLNetworking.Runtime#0",
                "encode|129|System.Void|netstandard|NetworkBuffer&@HLNetworking.Runtime#0,System.Int32@netstandard#0",
                "decode|150|ClientDataAPI.LocalisationDefinitions|HLAutoGenerated.dll|System.Byte[]@netstandard#0",
                "decode|150|ClientDataAPI.LocalisationDefinitions|HLAutoGenerated.dll|System.Byte[]@netstandard#0,System.Int32@netstandard#0,System.Int32@netstandard#0",
                "decode|150|ClientDataAPI.LocalisationDefinitions|HLAutoGenerated.dll|NetworkBuffer&@HLNetworking.Runtime#0,System.Int32@netstandard#0",
                "decode|150|ClientDataAPI.LocalisationDefinitions|HLAutoGenerated.dll|NetworkBuffer&@HLNetworking.Runtime#0",
                "decodeInto|134|System.Void|netstandard|NetworkBuffer&@HLNetworking.Runtime#0",
                ".cctor|6289|System.Void|netstandard|",
            }),
        };

        internal static byte[] Restore(byte[] original, string[] references)
        {
            if (original == null) throw new InvalidDataException("No PE image.");
            var targets = new List<MethodDefinition>();
            bool? alreadyPatched = null;
            using (var resolver = new ExactResolver(references))
            using (var input = new MemoryStream(original, false))
            using (var module = ModuleDefinition.ReadModule(input, new ReaderParameters { AssemblyResolver = resolver, ReadingMode = ReadingMode.Immediate }))
            {
                Require(module.Assembly.Name.Name == "HLAutoGenerated", "Wrong assembly identity.");
                Require(!module.Assembly.Name.HasPublicKey && module.Assembly.Name.Version == new Version(0, 0, 0, 0), "Unexpected assembly signing/version.");
                foreach (var contract in Contracts)
                {
                    var type = module.Types.SingleOrDefault(t => t.FullName == contract.Name);
                    Require(type != null, "Missing codec " + contract.Name);
                    Require((int)type.Attributes == contract.Flags && type.BaseType.FullName == "System.Object" && type.BaseType.Scope.Name == "netstandard", "Changed codec type/base flags.");
                    Scope(type.BaseType);
                    Require(!type.HasGenericParameters && !type.HasNestedTypes, "Unexpected codec generics/nested types.");
                    Require(type.Events.Count == 0 && type.Properties.Count == (type.Name == "LocalisationDefinitions" ? 3 : 4), "Changed codec properties/events.");
                    string[] propertyNames = type.Name == "LocalisedString" ? new[] { "MessageId", "Id", "Content", "NumArgs" }
                        : type.Name == "StringTable" ? new[] { "MessageId", "Language", "Strings", "Hash" }
                        : type.Name == "SupportedLanguage" ? new[] { "MessageId", "Language", "LocalisedName", "IsRTL" }
                        : new[] { "MessageId", "SupportedLanguages", "StringTable" };
                    for (int i = 0; i < type.Properties.Count; ++i)
                    {
                        var property = type.Properties[i];
                        Scope(property.PropertyType);
                        Require(property.Name == propertyNames[i] && property.Attributes == 0 && property.CustomAttributes.Count == 0 && property.Parameters.Count == 0 && property.OtherMethods.Count == 0 && property.GetMethod != null && property.GetMethod.DeclaringType == type && property.GetMethod.Name == "get_" + property.Name && property.GetMethod.ReturnType.FullName == property.PropertyType.FullName && (property.Name == "MessageId" ? property.SetMethod == null : property.SetMethod != null && property.SetMethod.DeclaringType == type && property.SetMethod.Name == "set_" + property.Name && property.SetMethod.Parameters.Count == 1 && property.SetMethod.Parameters[0].ParameterType.FullName == property.PropertyType.FullName), "Changed property metadata.");
                    }
                    Require(type.Interfaces.Count == 2, "Changed marker interface count.");
                    var markerNames = new[] { "EncodableMessage", "DecodableMessage" };
                    for (int i = 0; i < markerNames.Length; ++i)
                    {
                        Require(type.Interfaces[i].CustomAttributes.Count == 0, "Changed interface implementation metadata.");
                        var marker = type.Interfaces[i].InterfaceType;
                        Require(marker.FullName == markerNames[i] && marker.Scope.Name == "HLNetworking.Runtime", "Changed marker interface identity/order.");
                        var declaration = marker.Resolve();
                        Require(declaration != null && (int)declaration.Attributes == 161 && declaration.BaseType == null && declaration.Methods.Count == 0 && declaration.Fields.Count == 0 && declaration.Properties.Count == 0 && declaration.Events.Count == 0 && declaration.Interfaces.Count == 0 && declaration.CustomAttributes.Count == 0 && declaration.GenericParameters.Count == 0, "Marker interfaces must remain genuinely empty.");
                    }
                    Require(type.Fields.Count == contract.Fields.Length && type.Methods.Count == contract.Methods.Length, "Changed codec member count.");
                    Require(type.CustomAttributes.Count == 2, "Changed codec attributes.");
                    for (int i = 0; i < 2; ++i)
                    {
                        var attribute = type.CustomAttributes[i];
                        Require(attribute.AttributeType.FullName == "Unity.IL2CPP.CompilerServices.Il2CppSetOptionAttribute" && attribute.AttributeType.Scope is AssemblyNameReference attributeScope && attributeScope.FullName == "HLUnityCore.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" && attribute.ConstructorArguments.Count == 2 && Convert.ToInt32(attribute.ConstructorArguments[0].Value) == (type.Name == "LocalisationDefinitions" ? 2 - i : i + 1) && attribute.ConstructorArguments[0].Type.FullName == "Unity.IL2CPP.CompilerServices.Option" && attribute.ConstructorArguments[0].Type.Scope is AssemblyNameReference optionScope && optionScope.FullName == "HLUnityCore.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" && attribute.ConstructorArguments[1].Type.FullName == "System.Object" && attribute.ConstructorArguments[1].Value is CustomAttributeArgument && ((CustomAttributeArgument)attribute.ConstructorArguments[1].Value).Type.FullName == "System.Boolean" && ((CustomAttributeArgument)attribute.ConstructorArguments[1].Value).Value is bool && !(bool)((CustomAttributeArgument)attribute.ConstructorArguments[1].Value).Value && attribute.Fields.Count == 0 && attribute.Properties.Count == 0, "Changed IL2CPP options.");
                    }
                    for (int i = 0; i < type.Fields.Count; ++i)
                    {
                        var field = type.Fields[i];
                        Require(FieldKey(field) == contract.Fields[i] && field.CustomAttributes.Count == 0, "Changed codec field " + field.Name + ": " + FieldKey(field) + " != " + contract.Fields[i] + "; attributes=" + field.CustomAttributes.Count);
                        Scope(field.FieldType);
                    }
                    for (int i = 0; i < type.Methods.Count; ++i)
                    {
                        var method = type.Methods[i];
                        bool target = IsTarget(method);
                        var flags = (ushort)method.Attributes;
                        ushort expected = (ushort)int.Parse(contract.Methods[i].Split('|')[1]);
                        if (target)
                        {
                            bool patched = flags == (expected | AddedFlags);
                            Require(flags == expected || patched, "Unexpected codec method flags " + method.FullName);
                            Require(!alreadyPatched.HasValue || alreadyPatched.Value == patched, "Partially restored codec flags.");
                            alreadyPatched = patched;
                            targets.Add(method);
                        }
                        Require(MethodKey(method, target ? expected : flags) == contract.Methods[i], "Changed codec signature/order " + method.FullName);
                        Require(method.ImplAttributes == 0 && method.HasBody && method.GenericParameters.Count == 0 && method.Overrides.Count == 0, "Changed codec body/implementation contracts.");
                        Scope(method.ReturnType);
                        foreach (var parameter in method.Parameters)
                        {
                            Scope(parameter.ParameterType);
                            Require(!parameter.HasConstant && parameter.CustomAttributes.Count == 0, "Changed parameter metadata.");
                        }
                        Require(method.CustomAttributes.Count == 0, "Changed method attributes.");
                        foreach (var attribute in method.CustomAttributes)
                            Require(attribute.AttributeType.FullName == "System.Runtime.CompilerServices.CompilerGeneratedAttribute" && attribute.ConstructorArguments.Count == 0, "Changed accessor attribute.");
                    }
                }
                Require(targets.Count == 20, "Expected exactly twenty native method identities.");
                var copy = (byte[])original.Clone();
                var table = new MethodTable(copy);
                foreach (var method in targets)
                {
                    int offset = table.FlagsOffset(method.MetadataToken.RID);
                    ushort existing = table.U16(offset);
                    Require(existing == (ushort)method.Attributes, "PE/Cecil MethodDef disagreement.");
                    table.SetU16(offset, (ushort)(existing | AddedFlags));
                }
                return copy;
            }
        }

        private static bool IsTarget(MethodDefinition m) => m.Name == "get_MessageId" || m.Name == "encodedLength" || m.Name == "decodeInto" || (m.Name == "encode" && m.IsPublic);
        private static string FieldKey(FieldDefinition f) => f.Name + "|" + (int)f.Attributes + "|" + f.FieldType.FullName + "|" + f.FieldType.Scope.Name + "|" + (f.HasConstant ? Convert.ToString(f.Constant, System.Globalization.CultureInfo.InvariantCulture) : "-");
        private static string MethodKey(MethodDefinition m, ushort flags) => m.Name + "|" + flags + "|" + m.ReturnType.FullName + "|" + m.ReturnType.Scope.Name + "|" + string.Join(",", m.Parameters.Select(p => p.ParameterType.FullName + "@" + p.ParameterType.Scope.Name + "#" + (int)p.Attributes));
        private static void Scope(TypeReference type)
        {
            while (type is TypeSpecification specification) type = specification.ElementType;
            if (type.Scope is ModuleDefinition module)
            {
                Require(module.Assembly.Name.FullName == "HLAutoGenerated, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null", "Changed local type scope.");
                return;
            }
            var scope = type.Scope as AssemblyNameReference;
            Require(scope != null, "Unsupported type scope.");
            string expected = scope.Name == "netstandard" ? "netstandard, Version=2.1.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"
                : scope.Name == "HLNetworking.Runtime" ? "HLNetworking.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null" : null;
            Require(expected != null && scope.FullName == expected, "Changed declared type scope.");
        }
        private static void Require(bool condition, string message) { if (!condition) throw new InvalidDataException(message); }

        private sealed class ExactResolver : IAssemblyResolver
        {
            private readonly string[] references;
            private readonly Dictionary<string, AssemblyDefinition> loaded = new Dictionary<string, AssemblyDefinition>();
            internal ExactResolver(string[] references) { this.references = references ?? new string[0]; }
            public AssemblyDefinition Resolve(AssemblyNameReference name) => Resolve(name, new ReaderParameters());
            public AssemblyDefinition Resolve(AssemblyNameReference name, ReaderParameters parameters)
            {
                if (loaded.TryGetValue(name.FullName, out var prior)) return prior;
                foreach (var path in references)
                {
                    string candidate = Path.GetFileNameWithoutExtension(path);
                    if (candidate != name.Name && candidate != name.Name + ".ref") continue;
                    var result = AssemblyDefinition.ReadAssembly(path, new ReaderParameters { AssemblyResolver = this });
                    if (result.Name.FullName != name.FullName) { result.Dispose(); continue; }
                    loaded.Add(name.FullName, result); return result;
                }
                throw new AssemblyResolutionException(name);
            }
            public void Dispose() { foreach (var assembly in loaded.Values) assembly.Dispose(); loaded.Clear(); }
        }

        // Locate MethodDef flag cells without reserializing the PE or PDB.
        // Every read is bounds checked. The only writes are twenty 16-bit flags.
        private sealed class MethodTable
        {
            private readonly byte[] image;
            private readonly int start, stride;
            private readonly uint count;
            internal MethodTable(byte[] image)
            {
                this.image = image;
                Require(U16(0) == 0x5a4d, "Missing DOS header.");
                int pe = checked((int)U32(0x3c));
                Require(U32(pe) == 0x00004550, "Missing PE header.");
                int sections = U16(pe + 6), optional = pe + 24, sectionTable = checked(optional + U16(pe + 20));
                ushort magic = U16(optional);
                Require(magic == 0x10b || magic == 0x20b, "Unsupported PE magic.");
                int directories = optional + (magic == 0x10b ? 96 : 112);
                Func<uint, int> rva = address => {
                    for (int i = 0; i < sections; ++i) {
                        int row = checked(sectionTable + i * 40); uint va = U32(row + 12), raw = U32(row + 16), ptr = U32(row + 20);
                        if (address >= va && (ulong)address - va < raw) return checked((int)(ptr + address - va));
                    }
                    throw new InvalidDataException("RVA outside file-backed sections.");
                };
                int cli = rva(U32(directories + 14 * 8)); int metadata = rva(U32(cli + 8));
                Require(U32(metadata) == 0x424a5342, "Missing CLR metadata.");
                int versionEnd = checked(metadata + 16 + (int)U32(metadata + 12));
                int header = checked((versionEnd + 3) & ~3); int streams = U16(header + 2), cursor = header + 4, tables = -1;
                for (int i = 0; i < streams; ++i) {
                    uint offset = U32(cursor); int name = cursor + 8, end = name;
                    while (Byte(end) != 0) ++end;
                    string label = System.Text.Encoding.ASCII.GetString(image, name, end - name);
                    if (label == "#~" || label == "#-") { Require(tables < 0, "Duplicate table stream."); tables = checked(metadata + (int)offset); }
                    cursor = checked((end + 4) & ~3);
                }
                Require(tables >= 0, "Missing table stream.");
                byte heaps = Byte(tables + 6); ulong valid = U64(tables + 8); cursor = tables + 24;
                var rows = new uint[64];
                for (int i = 0; i < 64; ++i) if ((valid & (1UL << i)) != 0) { rows[i] = U32(cursor); cursor += 4; }
                Func<int, int> index = id => rows[id] >= 65536 ? 4 : 2;
                Func<int, int[], int> coded = (bits, ids) => ids.Max(id => rows[id]) >= (1U << (16 - bits)) ? 4 : 2;
                int str = (heaps & 1) == 0 ? 2 : 4, guid = (heaps & 2) == 0 ? 2 : 4, blob = (heaps & 4) == 0 ? 2 : 4;
                int[] widths = { 2 + str + guid * 3, coded(2, new[] { 0, 26, 35, 1 }) + str * 2, 4 + str * 2 + coded(2, new[] { 2, 1, 27 }) + index(4) + index(6), index(4), 2 + str + blob, index(6) };
                for (int i = 0; i < 6; ++i) cursor = checked(cursor + (int)rows[i] * widths[i]);
                start = cursor; count = rows[6]; stride = 8 + str + blob + index(8);
                Bounds(start, checked((int)count * stride));
            }
            internal int FlagsOffset(uint rid) { Require(rid > 0 && rid <= count, "MethodDef RID outside table."); return checked(start + ((int)rid - 1) * stride + 6); }
            private void Bounds(int offset, int size) { Require(offset >= 0 && size >= 0 && (long)offset + size <= image.Length, "PE read outside image."); }
            private byte Byte(int offset) { Bounds(offset, 1); return image[offset]; }
            internal ushort U16(int offset) { Bounds(offset, 2); return (ushort)(image[offset] | image[offset + 1] << 8); }
            private uint U32(int offset) { Bounds(offset, 4); return (uint)(image[offset] | image[offset + 1] << 8 | image[offset + 2] << 16 | image[offset + 3] << 24); }
            private ulong U64(int offset) => U32(offset) | ((ulong)U32(offset + 4) << 32);
            internal void SetU16(int offset, ushort value) { Bounds(offset, 2); image[offset] = (byte)value; image[offset + 1] = (byte)(value >> 8); }
        }
    }
}
